// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat_test.proto

/*
Package chat_test is a generated protocol buffer package.

It is generated from these files:
	chat_test.proto

It has these top-level messages:
	ChatMessage
	Session
	VoidRsp
*/
package chat_test

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChatMessage struct {
	SenderSessionId string `protobuf:"bytes,1,opt,name=sender_session_id,json=senderSessionId" json:"sender_session_id,omitempty"`
	MessageData     string `protobuf:"bytes,3,opt,name=message_data,json=messageData" json:"message_data,omitempty"`
}

func (m *ChatMessage) Reset()                    { *m = ChatMessage{} }
func (m *ChatMessage) String() string            { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()               {}
func (*ChatMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChatMessage) GetSenderSessionId() string {
	if m != nil {
		return m.SenderSessionId
	}
	return ""
}

func (m *ChatMessage) GetMessageData() string {
	if m != nil {
		return m.MessageData
	}
	return ""
}

type Session struct {
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Session) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type VoidRsp struct {
}

func (m *VoidRsp) Reset()                    { *m = VoidRsp{} }
func (m *VoidRsp) String() string            { return proto.CompactTextString(m) }
func (*VoidRsp) ProtoMessage()               {}
func (*VoidRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*ChatMessage)(nil), "chat_test.ChatMessage")
	proto.RegisterType((*Session)(nil), "chat_test.Session")
	proto.RegisterType((*VoidRsp)(nil), "chat_test.VoidRsp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ChatTest service

type ChatTestClient interface {
	Connect(ctx context.Context, in *Session, opts ...grpc.CallOption) (ChatTest_ConnectClient, error)
	SendChat(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*VoidRsp, error)
}

type chatTestClient struct {
	cc *grpc.ClientConn
}

func NewChatTestClient(cc *grpc.ClientConn) ChatTestClient {
	return &chatTestClient{cc}
}

func (c *chatTestClient) Connect(ctx context.Context, in *Session, opts ...grpc.CallOption) (ChatTest_ConnectClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ChatTest_serviceDesc.Streams[0], c.cc, "/chat_test.ChatTest/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatTestConnectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatTest_ConnectClient interface {
	Recv() (*ChatMessage, error)
	grpc.ClientStream
}

type chatTestConnectClient struct {
	grpc.ClientStream
}

func (x *chatTestConnectClient) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatTestClient) SendChat(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*VoidRsp, error) {
	out := new(VoidRsp)
	err := grpc.Invoke(ctx, "/chat_test.ChatTest/SendChat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ChatTest service

type ChatTestServer interface {
	Connect(*Session, ChatTest_ConnectServer) error
	SendChat(context.Context, *ChatMessage) (*VoidRsp, error)
}

func RegisterChatTestServer(s *grpc.Server, srv ChatTestServer) {
	s.RegisterService(&_ChatTest_serviceDesc, srv)
}

func _ChatTest_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Session)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatTestServer).Connect(m, &chatTestConnectServer{stream})
}

type ChatTest_ConnectServer interface {
	Send(*ChatMessage) error
	grpc.ServerStream
}

type chatTestConnectServer struct {
	grpc.ServerStream
}

func (x *chatTestConnectServer) Send(m *ChatMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _ChatTest_SendChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatTestServer).SendChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat_test.ChatTest/SendChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatTestServer).SendChat(ctx, req.(*ChatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatTest_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chat_test.ChatTest",
	HandlerType: (*ChatTestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendChat",
			Handler:    _ChatTest_SendChat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _ChatTest_Connect_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chat_test.proto",
}

func init() { proto.RegisterFile("chat_test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x59, 0x04, 0xb7, 0x99, 0x0a, 0xc5, 0x41, 0xa4, 0x14, 0x04, 0xcd, 0xa9, 0x78, 0x28,
	0xa2, 0xa0, 0xf7, 0xd6, 0x8b, 0x07, 0x41, 0x5a, 0xf1, 0x24, 0x84, 0xb1, 0x19, 0xda, 0x05, 0x9b,
	0x94, 0xcc, 0xdc, 0xfc, 0xf3, 0xb2, 0x4d, 0x5c, 0x17, 0xc4, 0xeb, 0xf7, 0x5e, 0xbe, 0xcc, 0x0c,
	0x8c, 0xd6, 0x5b, 0x52, 0xa7, 0x2c, 0x3a, 0xdb, 0xa7, 0xa8, 0x11, 0x4d, 0x07, 0xec, 0x3b, 0x0c,
	0x17, 0x5b, 0xd2, 0x67, 0x16, 0xa1, 0x0d, 0xe3, 0x35, 0x9c, 0x0a, 0x07, 0xcf, 0xc9, 0x09, 0x8b,
	0x34, 0x31, 0xb8, 0xc6, 0x8f, 0xab, 0xcb, 0x6a, 0x6a, 0x96, 0xa3, 0x1c, 0xac, 0x32, 0x7f, 0xf2,
	0x78, 0x05, 0x27, 0xbb, 0xfc, 0xcc, 0x79, 0x52, 0x1a, 0x1f, 0x1d, 0x6a, 0xc3, 0xc2, 0x1e, 0x49,
	0xc9, 0x4e, 0xa1, 0x2e, 0x7d, 0xbc, 0x00, 0xf8, 0xa3, 0x34, 0xf2, 0x23, 0xb3, 0x06, 0xea, 0xb7,
	0xd8, 0xf8, 0xa5, 0xec, 0x6f, 0xbf, 0x60, 0xd0, 0x8e, 0xf4, 0xca, 0xa2, 0xf8, 0x00, 0xf5, 0x22,
	0x86, 0xc0, 0x6b, 0x45, 0x9c, 0xfd, 0xae, 0x51, 0xa4, 0x93, 0xf3, 0x1e, 0xeb, 0xad, 0x71, 0x53,
	0xe1, 0x3d, 0x0c, 0x56, 0x1c, 0x7c, 0x0b, 0xf1, 0x9f, 0xd6, 0xa4, 0x6f, 0x2c, 0x9f, 0xcf, 0x2d,
	0x9c, 0x29, 0x7f, 0xf2, 0x26, 0xd1, 0xce, 0xb7, 0x71, 0xca, 0xf9, 0xbc, 0x1b, 0xe9, 0xa5, 0xfa,
	0x38, 0x3e, 0x5c, 0xf1, 0xee, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x21, 0xbc, 0x4c, 0x58, 0x01,
	0x00, 0x00,
}
