// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth_test.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	auth_test.proto

It has these top-level messages:
	TLAuthSendCode
	TLAuthSentCode
	Auth_SentCode
	Bool
	TLBoolFalse
	TLBoolTrue
	TLTrue
	TLAuthSentCodeTypeApp
	TLAuthSentCodeTypeSms
	TLAuthSentCodeTypeCall
	TLAuthSentCodeTypeFlashCall
	Auth_SentCodeType
	Auth_CodeType
	TLAuthCodeTypeSms
	TLAuthCodeTypeCall
	TLAuthCodeTypeFlashCall
*/
package grpc_testing

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// auth.sendCode#86aef0ec flags:# allow_flashcall:flags.0?true phone_number:string current_number:flags.0?Bool api_id:int api_hash:string = auth.SentCode;
type TLAuthSendCode struct {
	Flags          int32  `protobuf:"varint,1,opt,name=flags" json:"flags,omitempty"`
	AllowFlashcall bool   `protobuf:"varint,2,opt,name=allow_flashcall,json=allowFlashcall" json:"allow_flashcall,omitempty"`
	PhoneNumber    string `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
	CurrentNumber  *Bool  `protobuf:"bytes,4,opt,name=current_number,json=currentNumber" json:"current_number,omitempty"`
	ApiId          int32  `protobuf:"varint,5,opt,name=api_id,json=apiId" json:"api_id,omitempty"`
	ApiHash        string `protobuf:"bytes,6,opt,name=api_hash,json=apiHash" json:"api_hash,omitempty"`
}

func (m *TLAuthSendCode) Reset()                    { *m = TLAuthSendCode{} }
func (m *TLAuthSendCode) String() string            { return proto.CompactTextString(m) }
func (*TLAuthSendCode) ProtoMessage()               {}
func (*TLAuthSendCode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TLAuthSendCode) GetFlags() int32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *TLAuthSendCode) GetAllowFlashcall() bool {
	if m != nil {
		return m.AllowFlashcall
	}
	return false
}

func (m *TLAuthSendCode) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *TLAuthSendCode) GetCurrentNumber() *Bool {
	if m != nil {
		return m.CurrentNumber
	}
	return nil
}

func (m *TLAuthSendCode) GetApiId() int32 {
	if m != nil {
		return m.ApiId
	}
	return 0
}

func (m *TLAuthSendCode) GetApiHash() string {
	if m != nil {
		return m.ApiHash
	}
	return ""
}

// auth.sentCode#5e002502 flags:# phone_registered:flags.0?true type:auth.SentCodeType phone_code_hash:string next_type:flags.1?auth.CodeType timeout:flags.2?int = auth.SentCode;
type TLAuthSentCode struct {
	Flags           int32              `protobuf:"varint,1,opt,name=flags" json:"flags,omitempty"`
	PhoneRegistered bool               `protobuf:"varint,2,opt,name=phone_registered,json=phoneRegistered" json:"phone_registered,omitempty"`
	Type            *Auth_SentCodeType `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	PhoneCodeHash   string             `protobuf:"bytes,4,opt,name=phone_code_hash,json=phoneCodeHash" json:"phone_code_hash,omitempty"`
	NextType        *Auth_CodeType     `protobuf:"bytes,5,opt,name=next_type,json=nextType" json:"next_type,omitempty"`
	Timeout         int32              `protobuf:"varint,6,opt,name=timeout" json:"timeout,omitempty"`
}

func (m *TLAuthSentCode) Reset()                    { *m = TLAuthSentCode{} }
func (m *TLAuthSentCode) String() string            { return proto.CompactTextString(m) }
func (*TLAuthSentCode) ProtoMessage()               {}
func (*TLAuthSentCode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TLAuthSentCode) GetFlags() int32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *TLAuthSentCode) GetPhoneRegistered() bool {
	if m != nil {
		return m.PhoneRegistered
	}
	return false
}

func (m *TLAuthSentCode) GetType() *Auth_SentCodeType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *TLAuthSentCode) GetPhoneCodeHash() string {
	if m != nil {
		return m.PhoneCodeHash
	}
	return ""
}

func (m *TLAuthSentCode) GetNextType() *Auth_CodeType {
	if m != nil {
		return m.NextType
	}
	return nil
}

func (m *TLAuthSentCode) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type Auth_SentCode struct {
	// Types that are valid to be assigned to Payload:
	//	*Auth_SentCode_AuthSentCode
	Payload isAuth_SentCode_Payload `protobuf_oneof:"payload"`
}

func (m *Auth_SentCode) Reset()                    { *m = Auth_SentCode{} }
func (m *Auth_SentCode) String() string            { return proto.CompactTextString(m) }
func (*Auth_SentCode) ProtoMessage()               {}
func (*Auth_SentCode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type isAuth_SentCode_Payload interface {
	isAuth_SentCode_Payload()
}

type Auth_SentCode_AuthSentCode struct {
	AuthSentCode *TLAuthSentCode `protobuf:"bytes,1,opt,name=auth_sentCode,json=authSentCode,oneof"`
}

func (*Auth_SentCode_AuthSentCode) isAuth_SentCode_Payload() {}

func (m *Auth_SentCode) GetPayload() isAuth_SentCode_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Auth_SentCode) GetAuthSentCode() *TLAuthSentCode {
	if x, ok := m.GetPayload().(*Auth_SentCode_AuthSentCode); ok {
		return x.AuthSentCode
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Auth_SentCode) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Auth_SentCode_OneofMarshaler, _Auth_SentCode_OneofUnmarshaler, _Auth_SentCode_OneofSizer, []interface{}{
		(*Auth_SentCode_AuthSentCode)(nil),
	}
}

func _Auth_SentCode_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Auth_SentCode)
	// payload
	switch x := m.Payload.(type) {
	case *Auth_SentCode_AuthSentCode:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AuthSentCode); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Auth_SentCode.Payload has unexpected type %T", x)
	}
	return nil
}

func _Auth_SentCode_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Auth_SentCode)
	switch tag {
	case 1: // payload.auth_sentCode
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLAuthSentCode)
		err := b.DecodeMessage(msg)
		m.Payload = &Auth_SentCode_AuthSentCode{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Auth_SentCode_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Auth_SentCode)
	// payload
	switch x := m.Payload.(type) {
	case *Auth_SentCode_AuthSentCode:
		s := proto.Size(x.AuthSentCode)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Bool struct {
	// Types that are valid to be assigned to Payload:
	//	*Bool_BoolFalse
	//	*Bool_BoolTrue
	Payload isBool_Payload `protobuf_oneof:"payload"`
}

func (m *Bool) Reset()                    { *m = Bool{} }
func (m *Bool) String() string            { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()               {}
func (*Bool) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isBool_Payload interface {
	isBool_Payload()
}

type Bool_BoolFalse struct {
	BoolFalse *TLBoolFalse `protobuf:"bytes,1,opt,name=boolFalse,oneof"`
}
type Bool_BoolTrue struct {
	BoolTrue *TLBoolTrue `protobuf:"bytes,2,opt,name=boolTrue,oneof"`
}

func (*Bool_BoolFalse) isBool_Payload() {}
func (*Bool_BoolTrue) isBool_Payload()  {}

func (m *Bool) GetPayload() isBool_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Bool) GetBoolFalse() *TLBoolFalse {
	if x, ok := m.GetPayload().(*Bool_BoolFalse); ok {
		return x.BoolFalse
	}
	return nil
}

func (m *Bool) GetBoolTrue() *TLBoolTrue {
	if x, ok := m.GetPayload().(*Bool_BoolTrue); ok {
		return x.BoolTrue
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Bool) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Bool_OneofMarshaler, _Bool_OneofUnmarshaler, _Bool_OneofSizer, []interface{}{
		(*Bool_BoolFalse)(nil),
		(*Bool_BoolTrue)(nil),
	}
}

func _Bool_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Bool)
	// payload
	switch x := m.Payload.(type) {
	case *Bool_BoolFalse:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BoolFalse); err != nil {
			return err
		}
	case *Bool_BoolTrue:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BoolTrue); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Bool.Payload has unexpected type %T", x)
	}
	return nil
}

func _Bool_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Bool)
	switch tag {
	case 1: // payload.boolFalse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLBoolFalse)
		err := b.DecodeMessage(msg)
		m.Payload = &Bool_BoolFalse{msg}
		return true, err
	case 2: // payload.boolTrue
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLBoolTrue)
		err := b.DecodeMessage(msg)
		m.Payload = &Bool_BoolTrue{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Bool_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Bool)
	// payload
	switch x := m.Payload.(type) {
	case *Bool_BoolFalse:
		s := proto.Size(x.BoolFalse)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Bool_BoolTrue:
		s := proto.Size(x.BoolTrue)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// boolFalse#bc799737 = Bool;
type TLBoolFalse struct {
}

func (m *TLBoolFalse) Reset()                    { *m = TLBoolFalse{} }
func (m *TLBoolFalse) String() string            { return proto.CompactTextString(m) }
func (*TLBoolFalse) ProtoMessage()               {}
func (*TLBoolFalse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// boolTrue#997275b5 = Bool;
type TLBoolTrue struct {
}

func (m *TLBoolTrue) Reset()                    { *m = TLBoolTrue{} }
func (m *TLBoolTrue) String() string            { return proto.CompactTextString(m) }
func (*TLBoolTrue) ProtoMessage()               {}
func (*TLBoolTrue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// true#3fedd339 = True;
type TLTrue struct {
}

func (m *TLTrue) Reset()                    { *m = TLTrue{} }
func (m *TLTrue) String() string            { return proto.CompactTextString(m) }
func (*TLTrue) ProtoMessage()               {}
func (*TLTrue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// auth.sentCodeTypeApp#3dbb5986 length:int = auth.SentCodeType;
type TLAuthSentCodeTypeApp struct {
	Length int32 `protobuf:"varint,1,opt,name=length" json:"length,omitempty"`
}

func (m *TLAuthSentCodeTypeApp) Reset()                    { *m = TLAuthSentCodeTypeApp{} }
func (m *TLAuthSentCodeTypeApp) String() string            { return proto.CompactTextString(m) }
func (*TLAuthSentCodeTypeApp) ProtoMessage()               {}
func (*TLAuthSentCodeTypeApp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *TLAuthSentCodeTypeApp) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

// auth.sentCodeTypeSms#c000bba2 length:int = auth.SentCodeType;
type TLAuthSentCodeTypeSms struct {
	Length int32 `protobuf:"varint,1,opt,name=length" json:"length,omitempty"`
}

func (m *TLAuthSentCodeTypeSms) Reset()                    { *m = TLAuthSentCodeTypeSms{} }
func (m *TLAuthSentCodeTypeSms) String() string            { return proto.CompactTextString(m) }
func (*TLAuthSentCodeTypeSms) ProtoMessage()               {}
func (*TLAuthSentCodeTypeSms) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *TLAuthSentCodeTypeSms) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

// auth.sentCodeTypeCall#5353e5a7 length:int = auth.SentCodeType;
type TLAuthSentCodeTypeCall struct {
	Length int32 `protobuf:"varint,1,opt,name=length" json:"length,omitempty"`
}

func (m *TLAuthSentCodeTypeCall) Reset()                    { *m = TLAuthSentCodeTypeCall{} }
func (m *TLAuthSentCodeTypeCall) String() string            { return proto.CompactTextString(m) }
func (*TLAuthSentCodeTypeCall) ProtoMessage()               {}
func (*TLAuthSentCodeTypeCall) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *TLAuthSentCodeTypeCall) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

// auth.sentCodeTypeFlashCall#ab03c6d9 pattern:string = auth.SentCodeType;
type TLAuthSentCodeTypeFlashCall struct {
	Pattern string `protobuf:"bytes,1,opt,name=pattern" json:"pattern,omitempty"`
}

func (m *TLAuthSentCodeTypeFlashCall) Reset()                    { *m = TLAuthSentCodeTypeFlashCall{} }
func (m *TLAuthSentCodeTypeFlashCall) String() string            { return proto.CompactTextString(m) }
func (*TLAuthSentCodeTypeFlashCall) ProtoMessage()               {}
func (*TLAuthSentCodeTypeFlashCall) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *TLAuthSentCodeTypeFlashCall) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

type Auth_SentCodeType struct {
	// Types that are valid to be assigned to Payload:
	//	*Auth_SentCodeType_AuthSentCodeTypeApp
	//	*Auth_SentCodeType_AuthSentCodeTypeSms
	//	*Auth_SentCodeType_AuthSentCodeTypeCall
	//	*Auth_SentCodeType_AuthSentCodeTypeFlashCall
	Payload isAuth_SentCodeType_Payload `protobuf_oneof:"payload"`
}

func (m *Auth_SentCodeType) Reset()                    { *m = Auth_SentCodeType{} }
func (m *Auth_SentCodeType) String() string            { return proto.CompactTextString(m) }
func (*Auth_SentCodeType) ProtoMessage()               {}
func (*Auth_SentCodeType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type isAuth_SentCodeType_Payload interface {
	isAuth_SentCodeType_Payload()
}

type Auth_SentCodeType_AuthSentCodeTypeApp struct {
	AuthSentCodeTypeApp *TLAuthSentCodeTypeApp `protobuf:"bytes,1,opt,name=auth_sentCodeTypeApp,json=authSentCodeTypeApp,oneof"`
}
type Auth_SentCodeType_AuthSentCodeTypeSms struct {
	AuthSentCodeTypeSms *TLAuthSentCodeTypeSms `protobuf:"bytes,2,opt,name=auth_sentCodeTypeSms,json=authSentCodeTypeSms,oneof"`
}
type Auth_SentCodeType_AuthSentCodeTypeCall struct {
	AuthSentCodeTypeCall *TLAuthSentCodeTypeCall `protobuf:"bytes,3,opt,name=auth_sentCodeTypeCall,json=authSentCodeTypeCall,oneof"`
}
type Auth_SentCodeType_AuthSentCodeTypeFlashCall struct {
	AuthSentCodeTypeFlashCall *TLAuthSentCodeTypeFlashCall `protobuf:"bytes,4,opt,name=auth_sentCodeTypeFlashCall,json=authSentCodeTypeFlashCall,oneof"`
}

func (*Auth_SentCodeType_AuthSentCodeTypeApp) isAuth_SentCodeType_Payload()       {}
func (*Auth_SentCodeType_AuthSentCodeTypeSms) isAuth_SentCodeType_Payload()       {}
func (*Auth_SentCodeType_AuthSentCodeTypeCall) isAuth_SentCodeType_Payload()      {}
func (*Auth_SentCodeType_AuthSentCodeTypeFlashCall) isAuth_SentCodeType_Payload() {}

func (m *Auth_SentCodeType) GetPayload() isAuth_SentCodeType_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Auth_SentCodeType) GetAuthSentCodeTypeApp() *TLAuthSentCodeTypeApp {
	if x, ok := m.GetPayload().(*Auth_SentCodeType_AuthSentCodeTypeApp); ok {
		return x.AuthSentCodeTypeApp
	}
	return nil
}

func (m *Auth_SentCodeType) GetAuthSentCodeTypeSms() *TLAuthSentCodeTypeSms {
	if x, ok := m.GetPayload().(*Auth_SentCodeType_AuthSentCodeTypeSms); ok {
		return x.AuthSentCodeTypeSms
	}
	return nil
}

func (m *Auth_SentCodeType) GetAuthSentCodeTypeCall() *TLAuthSentCodeTypeCall {
	if x, ok := m.GetPayload().(*Auth_SentCodeType_AuthSentCodeTypeCall); ok {
		return x.AuthSentCodeTypeCall
	}
	return nil
}

func (m *Auth_SentCodeType) GetAuthSentCodeTypeFlashCall() *TLAuthSentCodeTypeFlashCall {
	if x, ok := m.GetPayload().(*Auth_SentCodeType_AuthSentCodeTypeFlashCall); ok {
		return x.AuthSentCodeTypeFlashCall
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Auth_SentCodeType) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Auth_SentCodeType_OneofMarshaler, _Auth_SentCodeType_OneofUnmarshaler, _Auth_SentCodeType_OneofSizer, []interface{}{
		(*Auth_SentCodeType_AuthSentCodeTypeApp)(nil),
		(*Auth_SentCodeType_AuthSentCodeTypeSms)(nil),
		(*Auth_SentCodeType_AuthSentCodeTypeCall)(nil),
		(*Auth_SentCodeType_AuthSentCodeTypeFlashCall)(nil),
	}
}

func _Auth_SentCodeType_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Auth_SentCodeType)
	// payload
	switch x := m.Payload.(type) {
	case *Auth_SentCodeType_AuthSentCodeTypeApp:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AuthSentCodeTypeApp); err != nil {
			return err
		}
	case *Auth_SentCodeType_AuthSentCodeTypeSms:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AuthSentCodeTypeSms); err != nil {
			return err
		}
	case *Auth_SentCodeType_AuthSentCodeTypeCall:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AuthSentCodeTypeCall); err != nil {
			return err
		}
	case *Auth_SentCodeType_AuthSentCodeTypeFlashCall:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AuthSentCodeTypeFlashCall); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Auth_SentCodeType.Payload has unexpected type %T", x)
	}
	return nil
}

func _Auth_SentCodeType_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Auth_SentCodeType)
	switch tag {
	case 1: // payload.auth_sentCodeTypeApp
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLAuthSentCodeTypeApp)
		err := b.DecodeMessage(msg)
		m.Payload = &Auth_SentCodeType_AuthSentCodeTypeApp{msg}
		return true, err
	case 2: // payload.auth_sentCodeTypeSms
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLAuthSentCodeTypeSms)
		err := b.DecodeMessage(msg)
		m.Payload = &Auth_SentCodeType_AuthSentCodeTypeSms{msg}
		return true, err
	case 3: // payload.auth_sentCodeTypeCall
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLAuthSentCodeTypeCall)
		err := b.DecodeMessage(msg)
		m.Payload = &Auth_SentCodeType_AuthSentCodeTypeCall{msg}
		return true, err
	case 4: // payload.auth_sentCodeTypeFlashCall
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLAuthSentCodeTypeFlashCall)
		err := b.DecodeMessage(msg)
		m.Payload = &Auth_SentCodeType_AuthSentCodeTypeFlashCall{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Auth_SentCodeType_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Auth_SentCodeType)
	// payload
	switch x := m.Payload.(type) {
	case *Auth_SentCodeType_AuthSentCodeTypeApp:
		s := proto.Size(x.AuthSentCodeTypeApp)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Auth_SentCodeType_AuthSentCodeTypeSms:
		s := proto.Size(x.AuthSentCodeTypeSms)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Auth_SentCodeType_AuthSentCodeTypeCall:
		s := proto.Size(x.AuthSentCodeTypeCall)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Auth_SentCodeType_AuthSentCodeTypeFlashCall:
		s := proto.Size(x.AuthSentCodeTypeFlashCall)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Auth_CodeType struct {
	// Types that are valid to be assigned to Payload:
	//	*Auth_CodeType_AuthCodeTypeSms
	//	*Auth_CodeType_AuthCodeTypeCall
	//	*Auth_CodeType_AuthCodeTypeFlashCall
	Payload isAuth_CodeType_Payload `protobuf_oneof:"payload"`
}

func (m *Auth_CodeType) Reset()                    { *m = Auth_CodeType{} }
func (m *Auth_CodeType) String() string            { return proto.CompactTextString(m) }
func (*Auth_CodeType) ProtoMessage()               {}
func (*Auth_CodeType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type isAuth_CodeType_Payload interface {
	isAuth_CodeType_Payload()
}

type Auth_CodeType_AuthCodeTypeSms struct {
	AuthCodeTypeSms *TLAuthCodeTypeSms `protobuf:"bytes,1,opt,name=auth_codeTypeSms,json=authCodeTypeSms,oneof"`
}
type Auth_CodeType_AuthCodeTypeCall struct {
	AuthCodeTypeCall *TLAuthCodeTypeCall `protobuf:"bytes,2,opt,name=auth_codeTypeCall,json=authCodeTypeCall,oneof"`
}
type Auth_CodeType_AuthCodeTypeFlashCall struct {
	AuthCodeTypeFlashCall *TLAuthCodeTypeFlashCall `protobuf:"bytes,3,opt,name=auth_codeTypeFlashCall,json=authCodeTypeFlashCall,oneof"`
}

func (*Auth_CodeType_AuthCodeTypeSms) isAuth_CodeType_Payload()       {}
func (*Auth_CodeType_AuthCodeTypeCall) isAuth_CodeType_Payload()      {}
func (*Auth_CodeType_AuthCodeTypeFlashCall) isAuth_CodeType_Payload() {}

func (m *Auth_CodeType) GetPayload() isAuth_CodeType_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Auth_CodeType) GetAuthCodeTypeSms() *TLAuthCodeTypeSms {
	if x, ok := m.GetPayload().(*Auth_CodeType_AuthCodeTypeSms); ok {
		return x.AuthCodeTypeSms
	}
	return nil
}

func (m *Auth_CodeType) GetAuthCodeTypeCall() *TLAuthCodeTypeCall {
	if x, ok := m.GetPayload().(*Auth_CodeType_AuthCodeTypeCall); ok {
		return x.AuthCodeTypeCall
	}
	return nil
}

func (m *Auth_CodeType) GetAuthCodeTypeFlashCall() *TLAuthCodeTypeFlashCall {
	if x, ok := m.GetPayload().(*Auth_CodeType_AuthCodeTypeFlashCall); ok {
		return x.AuthCodeTypeFlashCall
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Auth_CodeType) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Auth_CodeType_OneofMarshaler, _Auth_CodeType_OneofUnmarshaler, _Auth_CodeType_OneofSizer, []interface{}{
		(*Auth_CodeType_AuthCodeTypeSms)(nil),
		(*Auth_CodeType_AuthCodeTypeCall)(nil),
		(*Auth_CodeType_AuthCodeTypeFlashCall)(nil),
	}
}

func _Auth_CodeType_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Auth_CodeType)
	// payload
	switch x := m.Payload.(type) {
	case *Auth_CodeType_AuthCodeTypeSms:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AuthCodeTypeSms); err != nil {
			return err
		}
	case *Auth_CodeType_AuthCodeTypeCall:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AuthCodeTypeCall); err != nil {
			return err
		}
	case *Auth_CodeType_AuthCodeTypeFlashCall:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AuthCodeTypeFlashCall); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Auth_CodeType.Payload has unexpected type %T", x)
	}
	return nil
}

func _Auth_CodeType_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Auth_CodeType)
	switch tag {
	case 1: // payload.auth_codeTypeSms
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLAuthCodeTypeSms)
		err := b.DecodeMessage(msg)
		m.Payload = &Auth_CodeType_AuthCodeTypeSms{msg}
		return true, err
	case 2: // payload.auth_codeTypeCall
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLAuthCodeTypeCall)
		err := b.DecodeMessage(msg)
		m.Payload = &Auth_CodeType_AuthCodeTypeCall{msg}
		return true, err
	case 3: // payload.auth_codeTypeFlashCall
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLAuthCodeTypeFlashCall)
		err := b.DecodeMessage(msg)
		m.Payload = &Auth_CodeType_AuthCodeTypeFlashCall{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Auth_CodeType_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Auth_CodeType)
	// payload
	switch x := m.Payload.(type) {
	case *Auth_CodeType_AuthCodeTypeSms:
		s := proto.Size(x.AuthCodeTypeSms)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Auth_CodeType_AuthCodeTypeCall:
		s := proto.Size(x.AuthCodeTypeCall)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Auth_CodeType_AuthCodeTypeFlashCall:
		s := proto.Size(x.AuthCodeTypeFlashCall)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// auth.codeTypeSms#72a3158c = auth.CodeType;
type TLAuthCodeTypeSms struct {
}

func (m *TLAuthCodeTypeSms) Reset()                    { *m = TLAuthCodeTypeSms{} }
func (m *TLAuthCodeTypeSms) String() string            { return proto.CompactTextString(m) }
func (*TLAuthCodeTypeSms) ProtoMessage()               {}
func (*TLAuthCodeTypeSms) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

// auth.codeTypeCall#741cd3e3 = auth.CodeType;
type TLAuthCodeTypeCall struct {
}

func (m *TLAuthCodeTypeCall) Reset()                    { *m = TLAuthCodeTypeCall{} }
func (m *TLAuthCodeTypeCall) String() string            { return proto.CompactTextString(m) }
func (*TLAuthCodeTypeCall) ProtoMessage()               {}
func (*TLAuthCodeTypeCall) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

// auth.codeTypeFlashCall#226ccefb = auth.CodeType;
type TLAuthCodeTypeFlashCall struct {
}

func (m *TLAuthCodeTypeFlashCall) Reset()                    { *m = TLAuthCodeTypeFlashCall{} }
func (m *TLAuthCodeTypeFlashCall) String() string            { return proto.CompactTextString(m) }
func (*TLAuthCodeTypeFlashCall) ProtoMessage()               {}
func (*TLAuthCodeTypeFlashCall) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func init() {
	proto.RegisterType((*TLAuthSendCode)(nil), "rpc.TL_auth_sendCode")
	proto.RegisterType((*TLAuthSentCode)(nil), "rpc.TL_auth_sentCode")
	proto.RegisterType((*Auth_SentCode)(nil), "rpc.auth_SentCode")
	proto.RegisterType((*Bool)(nil), "rpc.Bool")
	proto.RegisterType((*TLBoolFalse)(nil), "rpc.TL_boolFalse")
	proto.RegisterType((*TLBoolTrue)(nil), "rpc.TL_boolTrue")
	proto.RegisterType((*TLTrue)(nil), "rpc.TL_true")
	proto.RegisterType((*TLAuthSentCodeTypeApp)(nil), "rpc.TL_auth_sentCodeTypeApp")
	proto.RegisterType((*TLAuthSentCodeTypeSms)(nil), "rpc.TL_auth_sentCodeTypeSms")
	proto.RegisterType((*TLAuthSentCodeTypeCall)(nil), "rpc.TL_auth_sentCodeTypeCall")
	proto.RegisterType((*TLAuthSentCodeTypeFlashCall)(nil), "rpc.TL_auth_sentCodeTypeFlashCall")
	proto.RegisterType((*Auth_SentCodeType)(nil), "rpc.auth_SentCodeType")
	proto.RegisterType((*Auth_CodeType)(nil), "rpc.auth_CodeType")
	proto.RegisterType((*TLAuthCodeTypeSms)(nil), "rpc.TL_auth_codeTypeSms")
	proto.RegisterType((*TLAuthCodeTypeCall)(nil), "rpc.TL_auth_codeTypeCall")
	proto.RegisterType((*TLAuthCodeTypeFlashCall)(nil), "rpc.TL_auth_codeTypeFlashCall")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Auth service

type AuthClient interface {
	AuthSentCode(ctx context.Context, in *TLAuthSendCode, opts ...grpc.CallOption) (*Auth_SentCode, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) AuthSentCode(ctx context.Context, in *TLAuthSendCode, opts ...grpc.CallOption) (*Auth_SentCode, error) {
	out := new(Auth_SentCode)
	err := grpc.Invoke(ctx, "/rpc.Auth/auth_sentCode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthServer interface {
	AuthSentCode(context.Context, *TLAuthSendCode) (*Auth_SentCode, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_AuthSentCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLAuthSendCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).AuthSentCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Auth/AuthSentCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).AuthSentCode(ctx, req.(*TLAuthSendCode))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "auth_sentCode",
			Handler:    _Auth_AuthSentCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth_test.proto",
}

func init() { proto.RegisterFile("auth_test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 704 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x4d, 0xd2, 0x7c, 0x4e, 0x9a, 0x36, 0xdd, 0x26, 0xc1, 0x69, 0x29, 0x0a, 0x3e, 0x40, 0xe0,
	0x10, 0x68, 0x38, 0x21, 0x71, 0x69, 0x0a, 0x95, 0x91, 0x0a, 0x02, 0x27, 0x12, 0xdc, 0xac, 0x8d,
	0xb3, 0x8d, 0x2d, 0xf9, 0x4b, 0xf6, 0x46, 0xd0, 0x3b, 0x3f, 0x92, 0xdf, 0xc1, 0x1f, 0x00, 0xed,
	0x78, 0xed, 0x3a, 0x89, 0xcd, 0xcd, 0xfb, 0x76, 0xde, 0x9b, 0x99, 0x37, 0xbb, 0x6b, 0x38, 0xa6,
	0x1b, 0x6e, 0x19, 0x9c, 0x45, 0x7c, 0x12, 0x84, 0x3e, 0xf7, 0xc9, 0x41, 0x18, 0x98, 0xea, 0xef,
	0x32, 0x74, 0x17, 0xb7, 0x06, 0xee, 0x45, 0xcc, 0x5b, 0x5d, 0xfb, 0x2b, 0x46, 0x7a, 0x50, 0xbb,
	0x73, 0xe8, 0x3a, 0x52, 0xca, 0xa3, 0xf2, 0xb8, 0xa6, 0xc7, 0x0b, 0xf2, 0x1c, 0x8e, 0xa9, 0xe3,
	0xf8, 0x3f, 0x8c, 0x3b, 0x87, 0x46, 0x96, 0x49, 0x1d, 0x47, 0xa9, 0x8c, 0xca, 0xe3, 0xa6, 0x7e,
	0x84, 0xf0, 0x4d, 0x82, 0x92, 0xa7, 0x70, 0x18, 0x58, 0xbe, 0xc7, 0x0c, 0x6f, 0xe3, 0x2e, 0x59,
	0xa8, 0x1c, 0x8c, 0xca, 0xe3, 0x96, 0xde, 0x46, 0xec, 0x33, 0x42, 0xe4, 0x35, 0x1c, 0x99, 0x9b,
	0x30, 0x64, 0x1e, 0x4f, 0x82, 0xaa, 0xa3, 0xf2, 0xb8, 0x3d, 0x6d, 0x4d, 0xc2, 0xc0, 0x9c, 0xcc,
	0x7c, 0xdf, 0xd1, 0x3b, 0x32, 0x40, 0x32, 0xfa, 0x50, 0xa7, 0x81, 0x6d, 0xd8, 0x2b, 0xa5, 0x16,
	0x17, 0x45, 0x03, 0xfb, 0xe3, 0x8a, 0x0c, 0xa1, 0x29, 0x60, 0x8b, 0x46, 0x96, 0x52, 0xc7, 0x3c,
	0x0d, 0x1a, 0xd8, 0x1a, 0x8d, 0x2c, 0xf5, 0xcf, 0x76, 0x6b, 0xfc, 0x3f, 0xad, 0xbd, 0x80, 0x6e,
	0x5c, 0x71, 0xc8, 0xd6, 0x76, 0xc4, 0x59, 0xc8, 0x56, 0xb2, 0xb7, 0x63, 0xc4, 0xf5, 0x14, 0x26,
	0x2f, 0xa1, 0xca, 0xef, 0x03, 0x86, 0x4d, 0xb5, 0xa7, 0x03, 0xac, 0x17, 0x53, 0xcc, 0x65, 0x8a,
	0xc5, 0x7d, 0xc0, 0x74, 0x8c, 0x21, 0xcf, 0x20, 0xa6, 0x1b, 0xa6, 0xbf, 0x62, 0x71, 0x8d, 0x55,
	0xac, 0xb1, 0x83, 0xb0, 0x88, 0x16, 0x95, 0x92, 0x57, 0xd0, 0xf2, 0xd8, 0x4f, 0x6e, 0xa0, 0x70,
	0x0d, 0x85, 0xc9, 0x83, 0x70, 0x2a, 0xda, 0x14, 0x41, 0xe2, 0x8b, 0x28, 0xd0, 0xe0, 0xb6, 0xcb,
	0xfc, 0x0d, 0xc7, 0xa6, 0x6b, 0x7a, 0xb2, 0x54, 0xbf, 0x43, 0x67, 0xab, 0x1a, 0xf2, 0x4e, 0x02,
	0x89, 0x03, 0xd8, 0x78, 0x7b, 0xda, 0x47, 0xfd, 0x5d, 0x7b, 0xb4, 0x92, 0x7e, 0x28, 0x80, 0x84,
	0x3d, 0x6b, 0x41, 0x23, 0xa0, 0xf7, 0x8e, 0x4f, 0x57, 0x2a, 0x87, 0xaa, 0x98, 0x0b, 0xb9, 0x84,
	0xd6, 0xd2, 0xf7, 0x9d, 0x1b, 0xea, 0x44, 0x89, 0xd8, 0x49, 0x22, 0x96, 0x6e, 0x68, 0x25, 0xfd,
	0x21, 0x8a, 0x4c, 0xa0, 0x29, 0x16, 0x8b, 0x70, 0xc3, 0xd0, 0xd6, 0xf6, 0xb4, 0x9b, 0x65, 0x08,
	0x5c, 0x2b, 0xe9, 0x69, 0x4c, 0x36, 0xeb, 0x11, 0x1c, 0x66, 0x75, 0xd5, 0x0e, 0xb4, 0x33, 0x2c,
	0xb5, 0x05, 0x8d, 0xc5, 0xad, 0xc1, 0xc5, 0xe7, 0x25, 0x3c, 0xda, 0x6d, 0x47, 0x78, 0x75, 0x15,
	0x04, 0x64, 0x00, 0x75, 0x87, 0x79, 0x6b, 0x6e, 0xc9, 0xa9, 0xcb, 0x55, 0x11, 0x65, 0xee, 0x46,
	0x85, 0x94, 0x29, 0x28, 0x79, 0x94, 0x6b, 0x71, 0xee, 0x8b, 0x38, 0x6f, 0xe1, 0x22, 0x8f, 0x83,
	0x17, 0x06, 0x89, 0x8a, 0xe8, 0x97, 0x73, 0x16, 0x7a, 0xc8, 0x6c, 0xe9, 0xc9, 0x52, 0xfd, 0x5b,
	0x81, 0x93, 0xbd, 0xd3, 0x45, 0xbe, 0x42, 0x2f, 0xaf, 0x4f, 0x39, 0x8d, 0xc7, 0xb9, 0xa3, 0x95,
	0x31, 0x5a, 0x49, 0x3f, 0xcd, 0x4e, 0x38, 0xb1, 0x28, 0x4f, 0x72, 0xee, 0x46, 0x72, 0x5c, 0xc5,
	0x92, 0x73, 0x37, 0xca, 0x93, 0x14, 0x16, 0x2e, 0xa0, 0x9f, 0xeb, 0x93, 0xbc, 0x3a, 0x17, 0x85,
	0x9a, 0x22, 0x48, 0x2b, 0xe9, 0xbd, 0x5d, 0x51, 0xf4, 0xca, 0x84, 0xb3, 0x62, 0x27, 0xe5, 0x2b,
	0xa2, 0x16, 0x4a, 0xa7, 0x91, 0x5a, 0x49, 0x1f, 0xee, 0xea, 0xa7, 0x9b, 0xd9, 0x03, 0xf8, 0xab,
	0x22, 0x2f, 0x50, 0xea, 0xfe, 0x07, 0xe8, 0x22, 0x60, 0x66, 0x6c, 0x8a, 0x9d, 0x57, 0xb6, 0xf2,
	0x9a, 0x5b, 0x16, 0xe1, 0xf3, 0x9b, 0xb5, 0x47, 0x93, 0x93, 0x35, 0xb3, 0xd6, 0xc4, 0x76, 0x0f,
	0x73, 0x75, 0x64, 0xd9, 0xdd, 0xac, 0x10, 0x5a, 0xf2, 0x0d, 0x06, 0x5b, 0x81, 0x0f, 0x76, 0xc4,
	0x4e, 0x3f, 0xc9, 0x95, 0xcb, 0x5a, 0xd1, 0xcf, 0x6a, 0xe6, 0xda, 0xd0, 0x87, 0xd3, 0x9c, 0xbe,
	0xd4, 0x01, 0xf4, 0xf2, 0xca, 0x54, 0xcf, 0x61, 0x58, 0x98, 0x6f, 0xfa, 0x1e, 0xaa, 0x57, 0x1b,
	0x6e, 0xed, 0x3d, 0x4d, 0x64, 0xef, 0x51, 0xc2, 0xdf, 0xd1, 0x19, 0xd9, 0x7f, 0x64, 0xd5, 0xd2,
	0x6c, 0x0c, 0xe7, 0xa6, 0xef, 0x4e, 0x3c, 0xb6, 0xdc, 0x38, 0xd4, 0x76, 0x27, 0xcc, 0x5b, 0xdb,
	0x1e, 0x9b, 0xb8, 0x1c, 0xff, 0x6e, 0xb3, 0xc6, 0xa7, 0xc5, 0x17, 0xf1, 0xa1, 0x55, 0x96, 0x75,
	0x44, 0xde, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xb5, 0xe8, 0xfd, 0x02, 0x07, 0x00, 0x00,
}
