// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc_error_codes.proto

/*
Package mtproto is a generated protocol buffer package.

It is generated from these files:
	rpc_error_codes.proto
	schema.tl.core_types.proto
	schema.tl.crc32.proto
	schema.tl.handshake.proto
	schema.tl.sync.proto
	schema.tl.sync.service.proto
	schema.tl.transport.proto

It has these top-level messages:
	Bool
	True
	Error
	Null
	TLBoolFalse
	TLBoolTrue
	TLTrue
	TLError
	TLNull
	ResPQ
	P_QInnerData
	Server_DH_Params
	Server_DHInnerData
	Client_DH_Inner_Data
	SetClient_DHParamsAnswer
	DestroyAuthKeyRes
	TLResPQ
	TLPQInnerData
	TLServer_DHParamsFail
	TLServer_DHParamsOk
	TLServer_DHInnerData
	TLClient_DHInnerData
	TLDhGenOk
	TLDhGenRetry
	TLDhGenFail
	TLDestroyAuthKeyOk
	TLDestroyAuthKeyNone
	TLDestroyAuthKeyFail
	TLReqPq
	TLReq_DHParams
	TLSetClient_DHParams
	TLDestroyAuthKey
	InputPeer
	InputUser
	InputContact
	InputFile
	InputMedia
	InputChatPhoto
	InputGeoPoint
	InputPhoto
	InputFileLocation
	InputAppEvent
	Peer
	Storage_FileType
	FileLocation
	User
	UserProfilePhoto
	UserStatus
	Chat
	ChatFull
	ChatParticipant
	ChatParticipants
	ChatPhoto
	Message
	MessageMedia
	MessageAction
	Dialog
	Photo
	PhotoSize
	GeoPoint
	Auth_CheckedPhone
	Auth_SentCode
	Auth_Authorization
	Auth_ExportedAuthorization
	InputNotifyPeer
	InputPeerNotifyEvents
	InputPeerNotifySettings
	PeerNotifyEvents
	PeerNotifySettings
	PeerSettings
	WallPaper
	ReportReason
	UserFull
	Contact
	ImportedContact
	ContactBlocked
	ContactStatus
	Contacts_Link
	Contacts_Contacts
	Contacts_ImportedContacts
	Contacts_Blocked
	Messages_Dialogs
	Messages_Messages
	Messages_Chats
	Messages_ChatFull
	Messages_AffectedHistory
	MessagesFilter
	Update
	Updates_State
	Updates_Difference
	Updates
	Photos_Photos
	Photos_Photo
	Upload_File
	DcOption
	Config
	NearestDc
	Help_AppUpdate
	Help_InviteText
	EncryptedChat
	InputEncryptedChat
	EncryptedFile
	InputEncryptedFile
	EncryptedMessage
	Messages_DhConfig
	Messages_SentEncryptedMessage
	InputDocument
	Document
	Help_Support
	NotifyPeer
	SendMessageAction
	Contacts_Found
	InputPrivacyKey
	PrivacyKey
	InputPrivacyRule
	PrivacyRule
	Account_PrivacyRules
	AccountDaysTTL
	DocumentAttribute
	Messages_Stickers
	StickerPack
	Messages_AllStickers
	DisabledFeature
	Messages_AffectedMessages
	ContactLink
	WebPage
	Authorization
	Account_Authorizations
	Account_Password
	Account_PasswordSettings
	Account_PasswordInputSettings
	Auth_PasswordRecovery
	ReceivedNotifyMessage
	ExportedChatInvite
	ChatInvite
	InputStickerSet
	StickerSet
	Messages_StickerSet
	BotCommand
	BotInfo
	KeyboardButton
	KeyboardButtonRow
	ReplyMarkup
	MessageEntity
	InputChannel
	Contacts_ResolvedPeer
	MessageRange
	Updates_ChannelDifference
	ChannelMessagesFilter
	ChannelParticipant
	ChannelParticipantsFilter
	Channels_ChannelParticipants
	Channels_ChannelParticipant
	Help_TermsOfService
	FoundGif
	Messages_FoundGifs
	Messages_SavedGifs
	InputBotInlineMessage
	InputBotInlineResult
	BotInlineMessage
	BotInlineResult
	Messages_BotResults
	ExportedMessageLink
	MessageFwdHeader
	Auth_CodeType
	Auth_SentCodeType
	Messages_BotCallbackAnswer
	Messages_MessageEditData
	InputBotInlineMessageID
	InlineBotSwitchPM
	Messages_PeerDialogs
	TopPeer
	TopPeerCategory
	TopPeerCategoryPeers
	Contacts_TopPeers
	DraftMessage
	Messages_FeaturedStickers
	Messages_RecentStickers
	Messages_ArchivedStickers
	Messages_StickerSetInstallResult
	StickerSetCovered
	MaskCoords
	InputStickeredMedia
	Game
	InputGame
	HighScore
	Messages_HighScores
	RichText
	PageBlock
	Page
	PhoneCallDiscardReason
	DataJSON
	LabeledPrice
	Invoice
	PaymentCharge
	PostAddress
	PaymentRequestedInfo
	PaymentSavedCredentials
	WebDocument
	InputWebDocument
	InputWebFileLocation
	Upload_WebFile
	Payments_PaymentForm
	Payments_ValidatedRequestedInfo
	Payments_PaymentResult
	Payments_PaymentReceipt
	Payments_SavedInfo
	InputPaymentCredentials
	Account_TmpPassword
	ShippingOption
	InputStickerSetItem
	InputPhoneCall
	PhoneCall
	PhoneConnection
	PhoneCallProtocol
	Phone_PhoneCall
	Upload_CdnFile
	CdnPublicKey
	CdnConfig
	LangPackString
	LangPackDifference
	LangPackLanguage
	ChannelAdminRights
	ChannelBannedRights
	ChannelAdminLogEventAction
	ChannelAdminLogEvent
	Channels_AdminLogResults
	ChannelAdminLogEventsFilter
	PopularContact
	CdnFileHash
	Messages_FavedStickers
	TLInputPeerEmpty
	TLInputPeerSelf
	TLInputPeerChat
	TLInputPeerUser
	TLInputPeerChannel
	TLInputUserEmpty
	TLInputUserSelf
	TLInputUser
	TLInputPhoneContact
	TLInputFile
	TLInputFileBig
	TLInputMediaEmpty
	TLInputMediaUploadedPhoto
	TLInputMediaPhoto
	TLInputMediaGeoPoint
	TLInputMediaContact
	TLInputMediaUploadedDocument
	TLInputMediaDocument
	TLInputMediaVenue
	TLInputMediaGifExternal
	TLInputMediaPhotoExternal
	TLInputMediaDocumentExternal
	TLInputMediaGame
	TLInputMediaInvoice
	TLInputChatPhotoEmpty
	TLInputChatUploadedPhoto
	TLInputChatPhoto
	TLInputGeoPointEmpty
	TLInputGeoPoint
	TLInputPhotoEmpty
	TLInputPhoto
	TLInputFileLocation
	TLInputEncryptedFileLocation
	TLInputDocumentFileLocation
	TLInputAppEvent
	TLPeerUser
	TLPeerChat
	TLPeerChannel
	TLStorageFileUnknown
	TLStorageFilePartial
	TLStorageFileJpeg
	TLStorageFileGif
	TLStorageFilePng
	TLStorageFilePdf
	TLStorageFileMp3
	TLStorageFileMov
	TLStorageFileMp4
	TLStorageFileWebp
	TLFileLocationUnavailable
	TLFileLocation
	TLUserEmpty
	TLUser
	TLUserProfilePhotoEmpty
	TLUserProfilePhoto
	TLUserStatusEmpty
	TLUserStatusOnline
	TLUserStatusOffline
	TLUserStatusRecently
	TLUserStatusLastWeek
	TLUserStatusLastMonth
	TLChatEmpty
	TLChat
	TLChatForbidden
	TLChannel
	TLChannelForbidden
	TLChatFull
	TLChannelFull
	TLChatParticipant
	TLChatParticipantCreator
	TLChatParticipantAdmin
	TLChatParticipantsForbidden
	TLChatParticipants
	TLChatPhotoEmpty
	TLChatPhoto
	TLMessageEmpty
	TLMessage
	TLMessageService
	TLMessageMediaEmpty
	TLMessageMediaPhoto
	TLMessageMediaGeo
	TLMessageMediaContact
	TLMessageMediaUnsupported
	TLMessageMediaDocument
	TLMessageMediaWebPage
	TLMessageMediaVenue
	TLMessageMediaGame
	TLMessageMediaInvoice
	TLMessageActionEmpty
	TLMessageActionChatCreate
	TLMessageActionChatEditTitle
	TLMessageActionChatEditPhoto
	TLMessageActionChatDeletePhoto
	TLMessageActionChatAddUser
	TLMessageActionChatDeleteUser
	TLMessageActionChatJoinedByLink
	TLMessageActionChannelCreate
	TLMessageActionChatMigrateTo
	TLMessageActionChannelMigrateFrom
	TLMessageActionPinMessage
	TLMessageActionHistoryClear
	TLMessageActionGameScore
	TLMessageActionPaymentSentMe
	TLMessageActionPaymentSent
	TLMessageActionPhoneCall
	TLMessageActionScreenshotTaken
	TLDialog
	TLPhotoEmpty
	TLPhoto
	TLPhotoSizeEmpty
	TLPhotoSize
	TLPhotoCachedSize
	TLGeoPointEmpty
	TLGeoPoint
	TLAuthCheckedPhone
	TLAuthSentCode
	TLAuthAuthorization
	TLAuthExportedAuthorization
	TLInputNotifyPeer
	TLInputNotifyUsers
	TLInputNotifyChats
	TLInputNotifyAll
	TLInputPeerNotifyEventsEmpty
	TLInputPeerNotifyEventsAll
	TLInputPeerNotifySettings
	TLPeerNotifyEventsEmpty
	TLPeerNotifyEventsAll
	TLPeerNotifySettingsEmpty
	TLPeerNotifySettings
	TLPeerSettings
	TLWallPaper
	TLWallPaperSolid
	TLInputReportReasonSpam
	TLInputReportReasonViolence
	TLInputReportReasonPornography
	TLInputReportReasonOther
	TLUserFull
	TLContact
	TLImportedContact
	TLContactBlocked
	TLContactStatus
	TLContactsLink
	TLContactsContactsNotModified
	TLContactsContacts
	TLContactsImportedContacts
	TLContactsBlocked
	TLContactsBlockedSlice
	TLMessagesDialogs
	TLMessagesDialogsSlice
	TLMessagesMessages
	TLMessagesMessagesSlice
	TLMessagesChannelMessages
	TLMessagesChats
	TLMessagesChatsSlice
	TLMessagesChatFull
	TLMessagesAffectedHistory
	TLInputMessagesFilterEmpty
	TLInputMessagesFilterPhotos
	TLInputMessagesFilterVideo
	TLInputMessagesFilterPhotoVideo
	TLInputMessagesFilterPhotoVideoDocuments
	TLInputMessagesFilterDocument
	TLInputMessagesFilterUrl
	TLInputMessagesFilterGif
	TLInputMessagesFilterVoice
	TLInputMessagesFilterMusic
	TLInputMessagesFilterChatPhotos
	TLInputMessagesFilterPhoneCalls
	TLInputMessagesFilterRoundVoice
	TLInputMessagesFilterRoundVideo
	TLInputMessagesFilterMyMentions
	TLUpdateNewMessage
	TLUpdateMessageID
	TLUpdateDeleteMessages
	TLUpdateUserTyping
	TLUpdateChatUserTyping
	TLUpdateChatParticipants
	TLUpdateUserStatus
	TLUpdateUserName
	TLUpdateUserPhoto
	TLUpdateContactRegistered
	TLUpdateContactLink
	TLUpdateNewEncryptedMessage
	TLUpdateEncryptedChatTyping
	TLUpdateEncryption
	TLUpdateEncryptedMessagesRead
	TLUpdateChatParticipantAdd
	TLUpdateChatParticipantDelete
	TLUpdateDcOptions
	TLUpdateUserBlocked
	TLUpdateNotifySettings
	TLUpdateServiceNotification
	TLUpdatePrivacy
	TLUpdateUserPhone
	TLUpdateReadHistoryInbox
	TLUpdateReadHistoryOutbox
	TLUpdateWebPage
	TLUpdateReadMessagesContents
	TLUpdateChannelTooLong
	TLUpdateChannel
	TLUpdateNewChannelMessage
	TLUpdateReadChannelInbox
	TLUpdateDeleteChannelMessages
	TLUpdateChannelMessageViews
	TLUpdateChatAdmins
	TLUpdateChatParticipantAdmin
	TLUpdateNewStickerSet
	TLUpdateStickerSetsOrder
	TLUpdateStickerSets
	TLUpdateSavedGifs
	TLUpdateBotInlineQuery
	TLUpdateBotInlineSend
	TLUpdateEditChannelMessage
	TLUpdateChannelPinnedMessage
	TLUpdateBotCallbackQuery
	TLUpdateEditMessage
	TLUpdateInlineBotCallbackQuery
	TLUpdateReadChannelOutbox
	TLUpdateDraftMessage
	TLUpdateReadFeaturedStickers
	TLUpdateRecentStickers
	TLUpdateConfig
	TLUpdatePtsChanged
	TLUpdateChannelWebPage
	TLUpdateDialogPinned
	TLUpdatePinnedDialogs
	TLUpdateBotWebhookJSON
	TLUpdateBotWebhookJSONQuery
	TLUpdateBotShippingQuery
	TLUpdateBotPrecheckoutQuery
	TLUpdatePhoneCall
	TLUpdateLangPackTooLong
	TLUpdateLangPack
	TLUpdateFavedStickers
	TLUpdateChannelReadMessagesContents
	TLUpdateContactsReset
	TLUpdatesState
	TLUpdatesDifferenceEmpty
	TLUpdatesDifference
	TLUpdatesDifferenceSlice
	TLUpdatesDifferenceTooLong
	TLUpdatesTooLong
	TLUpdateShortMessage
	TLUpdateShortChatMessage
	TLUpdateShort
	TLUpdatesCombined
	TLUpdates
	TLUpdateShortSentMessage
	TLPhotosPhotos
	TLPhotosPhotosSlice
	TLPhotosPhoto
	TLUploadFile
	TLUploadFileCdnRedirect
	TLDcOption
	TLConfig
	TLNearestDc
	TLHelpAppUpdate
	TLHelpNoAppUpdate
	TLHelpInviteText
	TLEncryptedChatEmpty
	TLEncryptedChatWaiting
	TLEncryptedChatRequested
	TLEncryptedChat
	TLEncryptedChatDiscarded
	TLInputEncryptedChat
	TLEncryptedFileEmpty
	TLEncryptedFile
	TLInputEncryptedFileEmpty
	TLInputEncryptedFileUploaded
	TLInputEncryptedFile
	TLInputEncryptedFileBigUploaded
	TLEncryptedMessage
	TLEncryptedMessageService
	TLMessagesDhConfigNotModified
	TLMessagesDhConfig
	TLMessagesSentEncryptedMessage
	TLMessagesSentEncryptedFile
	TLInputDocumentEmpty
	TLInputDocument
	TLDocumentEmpty
	TLDocument
	TLHelpSupport
	TLNotifyPeer
	TLNotifyUsers
	TLNotifyChats
	TLNotifyAll
	TLSendMessageTypingAction
	TLSendMessageCancelAction
	TLSendMessageRecordVideoAction
	TLSendMessageUploadVideoAction
	TLSendMessageRecordAudioAction
	TLSendMessageUploadAudioAction
	TLSendMessageUploadPhotoAction
	TLSendMessageUploadDocumentAction
	TLSendMessageGeoLocationAction
	TLSendMessageChooseContactAction
	TLSendMessageGamePlayAction
	TLSendMessageRecordRoundAction
	TLSendMessageUploadRoundAction
	TLContactsFound
	TLInputPrivacyKeyStatusTimestamp
	TLInputPrivacyKeyChatInvite
	TLInputPrivacyKeyPhoneCall
	TLPrivacyKeyStatusTimestamp
	TLPrivacyKeyChatInvite
	TLPrivacyKeyPhoneCall
	TLInputPrivacyValueAllowContacts
	TLInputPrivacyValueAllowAll
	TLInputPrivacyValueAllowUsers
	TLInputPrivacyValueDisallowContacts
	TLInputPrivacyValueDisallowAll
	TLInputPrivacyValueDisallowUsers
	TLPrivacyValueAllowContacts
	TLPrivacyValueAllowAll
	TLPrivacyValueAllowUsers
	TLPrivacyValueDisallowContacts
	TLPrivacyValueDisallowAll
	TLPrivacyValueDisallowUsers
	TLAccountPrivacyRules
	TLAccountDaysTTL
	TLDocumentAttributeImageSize
	TLDocumentAttributeAnimated
	TLDocumentAttributeSticker
	TLDocumentAttributeVideo
	TLDocumentAttributeAudio
	TLDocumentAttributeFilename
	TLDocumentAttributeHasStickers
	TLMessagesStickersNotModified
	TLMessagesStickers
	TLStickerPack
	TLMessagesAllStickersNotModified
	TLMessagesAllStickers
	TLDisabledFeature
	TLMessagesAffectedMessages
	TLContactLinkUnknown
	TLContactLinkNone
	TLContactLinkHasPhone
	TLContactLinkContact
	TLWebPageEmpty
	TLWebPagePending
	TLWebPage
	TLWebPageNotModified
	TLAuthorization
	TLAccountAuthorizations
	TLAccountNoPassword
	TLAccountPassword
	TLAccountPasswordSettings
	TLAccountPasswordInputSettings
	TLAuthPasswordRecovery
	TLReceivedNotifyMessage
	TLChatInviteEmpty
	TLChatInviteExported
	TLChatInviteAlready
	TLChatInvite
	TLInputStickerSetEmpty
	TLInputStickerSetID
	TLInputStickerSetShortName
	TLStickerSet
	TLMessagesStickerSet
	TLBotCommand
	TLBotInfo
	TLKeyboardButton
	TLKeyboardButtonUrl
	TLKeyboardButtonCallback
	TLKeyboardButtonRequestPhone
	TLKeyboardButtonRequestGeoLocation
	TLKeyboardButtonSwitchInline
	TLKeyboardButtonGame
	TLKeyboardButtonBuy
	TLKeyboardButtonRow
	TLReplyKeyboardHide
	TLReplyKeyboardForceReply
	TLReplyKeyboardMarkup
	TLReplyInlineMarkup
	TLMessageEntityUnknown
	TLMessageEntityMention
	TLMessageEntityHashtag
	TLMessageEntityBotCommand
	TLMessageEntityUrl
	TLMessageEntityEmail
	TLMessageEntityBold
	TLMessageEntityItalic
	TLMessageEntityCode
	TLMessageEntityPre
	TLMessageEntityTextUrl
	TLMessageEntityMentionName
	TLInputMessageEntityMentionName
	TLInputChannelEmpty
	TLInputChannel
	TLContactsResolvedPeer
	TLMessageRange
	TLUpdatesChannelDifferenceEmpty
	TLUpdatesChannelDifferenceTooLong
	TLUpdatesChannelDifference
	TLChannelMessagesFilterEmpty
	TLChannelMessagesFilter
	TLChannelParticipant
	TLChannelParticipantSelf
	TLChannelParticipantCreator
	TLChannelParticipantAdmin
	TLChannelParticipantBanned
	TLChannelParticipantsRecent
	TLChannelParticipantsAdmins
	TLChannelParticipantsKicked
	TLChannelParticipantsBots
	TLChannelParticipantsBanned
	TLChannelParticipantsSearch
	TLChannelsChannelParticipants
	TLChannelsChannelParticipant
	TLHelpTermsOfService
	TLFoundGif
	TLFoundGifCached
	TLMessagesFoundGifs
	TLMessagesSavedGifsNotModified
	TLMessagesSavedGifs
	TLInputBotInlineMessageMediaAuto
	TLInputBotInlineMessageText
	TLInputBotInlineMessageMediaGeo
	TLInputBotInlineMessageMediaVenue
	TLInputBotInlineMessageMediaContact
	TLInputBotInlineMessageGame
	TLInputBotInlineResult
	TLInputBotInlineResultPhoto
	TLInputBotInlineResultDocument
	TLInputBotInlineResultGame
	TLBotInlineMessageMediaAuto
	TLBotInlineMessageText
	TLBotInlineMessageMediaGeo
	TLBotInlineMessageMediaVenue
	TLBotInlineMessageMediaContact
	TLBotInlineResult
	TLBotInlineMediaResult
	TLMessagesBotResults
	TLExportedMessageLink
	TLMessageFwdHeader
	TLAuthCodeTypeSms
	TLAuthCodeTypeCall
	TLAuthCodeTypeFlashCall
	TLAuthSentCodeTypeApp
	TLAuthSentCodeTypeSms
	TLAuthSentCodeTypeCall
	TLAuthSentCodeTypeFlashCall
	TLMessagesBotCallbackAnswer
	TLMessagesMessageEditData
	TLInputBotInlineMessageID
	TLInlineBotSwitchPM
	TLMessagesPeerDialogs
	TLTopPeer
	TLTopPeerCategoryBotsPM
	TLTopPeerCategoryBotsInline
	TLTopPeerCategoryCorrespondents
	TLTopPeerCategoryGroups
	TLTopPeerCategoryChannels
	TLTopPeerCategoryPhoneCalls
	TLTopPeerCategoryPeers
	TLContactsTopPeersNotModified
	TLContactsTopPeers
	TLDraftMessageEmpty
	TLDraftMessage
	TLMessagesFeaturedStickersNotModified
	TLMessagesFeaturedStickers
	TLMessagesRecentStickersNotModified
	TLMessagesRecentStickers
	TLMessagesArchivedStickers
	TLMessagesStickerSetInstallResultSuccess
	TLMessagesStickerSetInstallResultArchive
	TLStickerSetCovered
	TLStickerSetMultiCovered
	TLMaskCoords
	TLInputStickeredMediaPhoto
	TLInputStickeredMediaDocument
	TLGame
	TLInputGameID
	TLInputGameShortName
	TLHighScore
	TLMessagesHighScores
	TLTextEmpty
	TLTextPlain
	TLTextBold
	TLTextItalic
	TLTextUnderline
	TLTextStrike
	TLTextFixed
	TLTextUrl
	TLTextEmail
	TLTextConcat
	TLPageBlockUnsupported
	TLPageBlockTitle
	TLPageBlockSubtitle
	TLPageBlockAuthorDate
	TLPageBlockHeader
	TLPageBlockSubheader
	TLPageBlockParagraph
	TLPageBlockPreformatted
	TLPageBlockFooter
	TLPageBlockDivider
	TLPageBlockAnchor
	TLPageBlockList
	TLPageBlockBlockquote
	TLPageBlockPullquote
	TLPageBlockPhoto
	TLPageBlockVideo
	TLPageBlockCover
	TLPageBlockEmbed
	TLPageBlockEmbedPost
	TLPageBlockCollage
	TLPageBlockSlideshow
	TLPageBlockChannel
	TLPageBlockAudio
	TLPagePart
	TLPageFull
	TLPhoneCallDiscardReasonMissed
	TLPhoneCallDiscardReasonDisconnect
	TLPhoneCallDiscardReasonHangup
	TLPhoneCallDiscardReasonBusy
	TLDataJSON
	TLLabeledPrice
	TLInvoice
	TLPaymentCharge
	TLPostAddress
	TLPaymentRequestedInfo
	TLPaymentSavedCredentialsCard
	TLWebDocument
	TLInputWebDocument
	TLInputWebFileLocation
	TLUploadWebFile
	TLPaymentsPaymentForm
	TLPaymentsValidatedRequestedInfo
	TLPaymentsPaymentResult
	TLPaymentsPaymentVerficationNeeded
	TLPaymentsPaymentReceipt
	TLPaymentsSavedInfo
	TLInputPaymentCredentialsSaved
	TLInputPaymentCredentials
	TLAccountTmpPassword
	TLShippingOption
	TLInputStickerSetItem
	TLInputPhoneCall
	TLPhoneCallEmpty
	TLPhoneCallWaiting
	TLPhoneCallRequested
	TLPhoneCallAccepted
	TLPhoneCall
	TLPhoneCallDiscarded
	TLPhoneConnection
	TLPhoneCallProtocol
	TLPhonePhoneCall
	TLUploadCdnFileReuploadNeeded
	TLUploadCdnFile
	TLCdnPublicKey
	TLCdnConfig
	TLLangPackString
	TLLangPackStringPluralized
	TLLangPackStringDeleted
	TLLangPackDifference
	TLLangPackLanguage
	TLChannelAdminRights
	TLChannelBannedRights
	TLChannelAdminLogEventActionChangeTitle
	TLChannelAdminLogEventActionChangeAbout
	TLChannelAdminLogEventActionChangeUsername
	TLChannelAdminLogEventActionChangePhoto
	TLChannelAdminLogEventActionToggleInvites
	TLChannelAdminLogEventActionToggleSignatures
	TLChannelAdminLogEventActionUpdatePinned
	TLChannelAdminLogEventActionEditMessage
	TLChannelAdminLogEventActionDeleteMessage
	TLChannelAdminLogEventActionParticipantJoin
	TLChannelAdminLogEventActionParticipantLeave
	TLChannelAdminLogEventActionParticipantInvite
	TLChannelAdminLogEventActionParticipantToggleBan
	TLChannelAdminLogEventActionParticipantToggleAdmin
	TLChannelAdminLogEventActionChangeStickerSet
	TLChannelAdminLogEvent
	TLChannelsAdminLogResults
	TLChannelAdminLogEventsFilter
	TLPopularContact
	TLCdnFileHash
	TLMessagesFavedStickersNotModified
	TLMessagesFavedStickers
	TLInvokeAfterMsg
	TLInvokeAfterMsgs
	TLInitConnection
	TLInvokeWithLayer
	TLInvokeWithoutUpdates
	TLAuthCheckPhone
	TLAuthSendCode
	TLAuthResendCode
	TLAccountSendChangePhoneCode
	TLAccountSendConfirmPhoneCode
	TLAuthSignUp
	TLAuthSignIn
	TLAuthImportAuthorization
	TLAuthImportBotAuthorization
	TLAuthCheckPassword
	TLAuthRecoverPassword
	TLAuthLogOut
	TLAuthResetAuthorizations
	TLAuthSendInvites
	TLAuthBindTempAuthKey
	TLAuthCancelCode
	TLAuthDropTempAuthKeys
	TLAccountRegisterDevice
	TLAccountUnregisterDevice
	TLAccountUpdateNotifySettings
	TLAccountResetNotifySettings
	TLAccountUpdateStatus
	TLAccountReportPeer
	TLAccountCheckUsername
	TLAccountDeleteAccount
	TLAccountSetAccountTTL
	TLAccountUpdateDeviceLocked
	TLAccountResetAuthorization
	TLAccountUpdatePasswordSettings
	TLAccountConfirmPhone
	TLContactsDeleteContacts
	TLContactsBlock
	TLContactsUnblock
	TLContactsResetTopPeerRating
	TLContactsResetSaved
	TLMessagesSetTyping
	TLMessagesReportSpam
	TLMessagesHideReportSpam
	TLMessagesDiscardEncryption
	TLMessagesSetEncryptedTyping
	TLMessagesReadEncryptedHistory
	TLMessagesReportEncryptedSpam
	TLMessagesUninstallStickerSet
	TLMessagesEditChatAdmin
	TLMessagesReorderStickerSets
	TLMessagesSaveGif
	TLMessagesSetInlineBotResults
	TLMessagesEditInlineBotMessage
	TLMessagesSetBotCallbackAnswer
	TLMessagesSaveDraft
	TLMessagesReadFeaturedStickers
	TLMessagesSaveRecentSticker
	TLMessagesClearRecentStickers
	TLMessagesSetInlineGameScore
	TLMessagesToggleDialogPin
	TLMessagesReorderPinnedDialogs
	TLMessagesSetBotShippingResults
	TLMessagesSetBotPrecheckoutResults
	TLMessagesFaveSticker
	TLUploadSaveFilePart
	TLUploadSaveBigFilePart
	TLHelpSaveAppLog
	TLHelpSetBotUpdatesStatus
	TLChannelsReadHistory
	TLChannelsReportSpam
	TLChannelsEditAbout
	TLChannelsCheckUsername
	TLChannelsUpdateUsername
	TLChannelsSetStickers
	TLChannelsReadMessageContents
	TLBotsAnswerWebhookJSONQuery
	TLPaymentsClearSavedInfo
	TLPhoneReceivedCall
	TLPhoneSaveCallDebug
	TLAuthExportAuthorization
	TLAuthRequestPasswordRecovery
	TLAccountGetNotifySettings
	TLAccountUpdateProfile
	TLAccountUpdateUsername
	TLAccountChangePhone
	TLContactsImportCard
	TLAccountGetWallPapers
	TLAccountGetPrivacy
	TLAccountSetPrivacy
	TLAccountGetAccountTTL
	TLAccountGetAuthorizations
	TLAccountGetPassword
	TLAccountGetPasswordSettings
	TLAccountGetTmpPassword
	TLUsersGetUsers
	TLUsersGetFullUser
	TLContactsGetStatuses
	TLContactsGetContacts
	TLContactsImportContacts
	TLContactsDeleteContact
	TLContactsGetBlocked
	TLContactsExportCard
	TLMessagesGetMessagesViews
	TLContactsSearch
	TLContactsResolveUsername
	TLContactsGetTopPeers
	TLMessagesGetMessages
	TLMessagesGetHistory
	TLMessagesSearch
	TLMessagesSearchGlobal
	TLMessagesGetUnreadMentions
	TLChannelsGetMessages
	TLMessagesGetDialogs
	TLMessagesReadHistory
	TLMessagesDeleteMessages
	TLMessagesReadMessageContents
	TLChannelsDeleteMessages
	TLMessagesDeleteHistory
	TLChannelsDeleteUserHistory
	TLMessagesReceivedMessages
	TLMessagesSendMessage
	TLMessagesSendMedia
	TLMessagesForwardMessages
	TLMessagesEditChatTitle
	TLMessagesEditChatPhoto
	TLMessagesAddChatUser
	TLMessagesDeleteChatUser
	TLMessagesCreateChat
	TLMessagesForwardMessage
	TLMessagesImportChatInvite
	TLMessagesStartBot
	TLMessagesToggleChatAdmins
	TLMessagesMigrateChat
	TLMessagesSendInlineBotResult
	TLMessagesEditMessage
	TLMessagesGetAllDrafts
	TLMessagesSetGameScore
	TLMessagesSendScreenshotNotification
	TLHelpGetAppChangelog
	TLChannelsCreateChannel
	TLChannelsEditAdmin
	TLChannelsEditTitle
	TLChannelsEditPhoto
	TLChannelsJoinChannel
	TLChannelsLeaveChannel
	TLChannelsInviteToChannel
	TLChannelsDeleteChannel
	TLChannelsToggleInvites
	TLChannelsToggleSignatures
	TLChannelsUpdatePinnedMessage
	TLChannelsEditBanned
	TLPhoneDiscardCall
	TLPhoneSetCallRating
	TLMessagesGetPeerSettings
	TLMessagesGetChats
	TLMessagesGetCommonChats
	TLMessagesGetAllChats
	TLChannelsGetChannels
	TLChannelsGetAdminedPublicChannels
	TLMessagesGetFullChat
	TLChannelsGetFullChannel
	TLMessagesGetDhConfig
	TLMessagesRequestEncryption
	TLMessagesAcceptEncryption
	TLMessagesSendEncrypted
	TLMessagesSendEncryptedFile
	TLMessagesSendEncryptedService
	TLMessagesReceivedQueue
	TLPhotosDeletePhotos
	TLMessagesGetAllStickers
	TLMessagesGetMaskStickers
	TLMessagesGetWebPagePreview
	TLMessagesUploadMedia
	TLMessagesExportChatInvite
	TLChannelsExportInvite
	TLMessagesCheckChatInvite
	TLMessagesGetStickerSet
	TLStickersCreateStickerSet
	TLStickersRemoveStickerFromSet
	TLStickersChangeStickerPosition
	TLStickersAddStickerToSet
	TLMessagesInstallStickerSet
	TLMessagesGetDocumentByHash
	TLMessagesSearchGifs
	TLMessagesGetSavedGifs
	TLMessagesGetInlineBotResults
	TLMessagesGetMessageEditData
	TLMessagesGetBotCallbackAnswer
	TLMessagesGetPeerDialogs
	TLMessagesGetPinnedDialogs
	TLMessagesGetFeaturedStickers
	TLMessagesGetRecentStickers
	TLMessagesGetArchivedStickers
	TLMessagesGetAttachedStickers
	TLMessagesGetGameHighScores
	TLMessagesGetInlineGameHighScores
	TLMessagesGetWebPage
	TLMessagesGetFavedStickers
	TLUpdatesGetState
	TLUpdatesGetDifference
	TLUpdatesGetChannelDifference
	TLPhotosUpdateProfilePhoto
	TLPhotosUploadProfilePhoto
	TLPhotosGetUserPhotos
	TLUploadGetFile
	TLUploadGetWebFile
	TLUploadGetCdnFile
	TLUploadReuploadCdnFile
	TLUploadGetCdnFileHashes
	TLHelpGetConfig
	TLHelpGetNearestDc
	TLHelpGetAppUpdate
	TLHelpGetInviteText
	TLHelpGetSupport
	TLHelpGetTermsOfService
	TLHelpGetCdnConfig
	TLChannelsGetParticipants
	TLChannelsGetParticipant
	TLChannelsExportMessageLink
	TLChannelsGetAdminLog
	TLBotsSendCustomRequest
	TLPhoneGetCallConfig
	TLPaymentsGetPaymentForm
	TLPaymentsGetPaymentReceipt
	TLPaymentsValidateRequestedInfo
	TLPaymentsSendPaymentForm
	TLPaymentsGetSavedInfo
	TLPhoneRequestCall
	TLPhoneAcceptCall
	TLPhoneConfirmCall
	TLLangpackGetLangPack
	TLLangpackGetDifference
	TLLangpackGetStrings
	TLLangpackGetLanguages
	MsgsAck
	BadMsgNotification
	MsgsStateReq
	MsgsStateInfo
	MsgsAllInfo
	MsgDetailedInfo
	MsgResendReq
	RpcError
	RpcDropAnswer
	FutureSalt
	FutureSalts
	Pong
	DestroySessionRes
	NewSession
	HttpWait
	IpPort
	Help_ConfigSimple
	TLMsgsAck
	TLBadMsgNotification
	TLBadServerSalt
	TLMsgsStateReq
	TLMsgsStateInfo
	TLMsgsAllInfo
	TLMsgDetailedInfo
	TLMsgNewDetailedInfo
	TLMsgResendReq
	TLRpcError
	TLRpcAnswerUnknown
	TLRpcAnswerDroppedRunning
	TLRpcAnswerDropped
	TLFutureSalt
	TLFutureSalts
	TLPong
	TLDestroySessionOk
	TLDestroySessionNone
	TLNewSessionCreated
	TLHttpWait
	TLIpPort
	TLHelpConfigSimple
	TLRpcDropAnswer
	TLGetFutureSalts
	TLPing
	TLPingDelayDisconnect
	TLDestroySession
	TLContestSaveDeveloperInfo
*/
package mtproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TLRpcErrorCodes int32

const (
	// 	Error handling
	//
	// 	There will be errors when working with the API, and they must be correctly handled on the client.
	//
	// 	An error is characterized by several parameters:
	//
	// 	Error Code
	// 	Similar to HTTP status. Contains information on the type of error that occurred: for example,
	// 	a data input error, privacy error, or server error. This is a required parameter.
	//
	// 	Error Type
	// 	A string literal in the form of /[A-Z_0-9]+/, which summarizes the problem. For example, AUTH_KEY_UNREGISTERED.
	// 	This is an optional parameter.
	//
	// 	Error Description
	// 	May contain more detailed information on the error and how to resolve it,
	// 	for example: authorization required, use auth.* methods. Please note that the description text is subject to change,
	// 	one should avoid tying application logic to these messages. This is an optional parameter.
	//
	// 	Error Constructors
	// 	There should be a way to handle errors that are returned in rpc_error constructors.
	//
	// 	If an error constructor does not differentiate between type and description
	// 	but instead contains a single field called error_message (as in the example above),
	// 	it must be split into 2 components, for example, using the following regular expression: /^([A-Z_0-9]+)(: (.+))?/.
	//
	// Protobuf3 enum first is 0
	TLRpcErrorCodes_ERROR_CODE_OK TLRpcErrorCodes = 0
	// The request must be repeated, but directed to a different data center.
	//
	// FILE_MIGRATE_X: the file to be accessed is currently stored in a different data center.
	// PHONE_MIGRATE_X: the phone number a user is trying to use for authorization is associated with a different data center.
	// NETWORK_MIGRATE_X: the source IP address is associated with a different data center (for registration)
	// USER_MIGRATE_X: the user whose identity is being used to execute
	// 				   queries is associated with a different data center (for registration)
	//
	// In all these cases, the error description’s string literal
	// 		contains the number of the data center (instead of the X) to which the repeated query must be sent.
	// More information about redirects between data centers »
	//
	TLRpcErrorCodes_FILE_MIGRATE_X    TLRpcErrorCodes = 303000
	TLRpcErrorCodes_PHONE_MIGRATE_X   TLRpcErrorCodes = 303001
	TLRpcErrorCodes_NETWORK_MIGRATE_X TLRpcErrorCodes = 303002
	TLRpcErrorCodes_USER_MIGRATE_X    TLRpcErrorCodes = 303003
	TLRpcErrorCodes_ERROR_SEE_OTHER   TLRpcErrorCodes = 303
	// The query contains errors. In the event that a request was created using a form
	// and contains user generated data,
	// the user should be notified that the data must be corrected before the query is repeated.
	//
	//
	// Examples of Errors:
	// 	FIRSTNAME_INVALID: The first name is invalid
	// 	LASTNAME_INVALID: The last name is invalid
	// 	PHONE_NUMBER_INVALID: The phone number is invalid
	// 	PHONE_CODE_HASH_EMPTY: phone_code_hash is missing
	// 	PHONE_CODE_EMPTY: phone_code is missing
	// 	PHONE_CODE_EXPIRED: The confirmation code has expired
	// 	API_ID_INVALID: The api_id/api_hash combination is invalid
	// 	PHONE_NUMBER_OCCUPIED: The phone number is already in use
	// 	PHONE_NUMBER_UNOCCUPIED: The phone number is not yet being used
	// 	USERS_TOO_FEW: Not enough users (to create a chat, for example)
	// 	USERS_TOO_MUCH: The maximum number of users has been exceeded (to create a chat, for example)
	// 	TYPE_CONSTRUCTOR_INVALID: The type constructor is invalid
	// 	FILE_PART_INVALID: The file part number is invalid
	// 	FILE_PARTS_INVALID: The number of file parts is invalid
	// 	FILE_PART_Х_MISSING: Part X (where X is a number) of the file is missing from storage
	// 	MD5_CHECKSUM_INVALID: The MD5 checksums do not match
	// 	PHOTO_INVALID_DIMENSIONS: The photo dimensions are invalid
	// 	FIELD_NAME_INVALID: The field with the name FIELD_NAME is invalid
	// 	FIELD_NAME_EMPTY: The field with the name FIELD_NAME is missing
	// 	MSG_WAIT_FAILED: A waiting call returned an error
	//
	TLRpcErrorCodes_FIRSTNAME_INVALID        TLRpcErrorCodes = 400000
	TLRpcErrorCodes_LASTNAME_INVALID         TLRpcErrorCodes = 400001
	TLRpcErrorCodes_PHONE_NUMBER_INVALID     TLRpcErrorCodes = 400002
	TLRpcErrorCodes_PHONE_CODE_HASH_EMPTY    TLRpcErrorCodes = 400003
	TLRpcErrorCodes_PHONE_CODE_EMPTY         TLRpcErrorCodes = 400004
	TLRpcErrorCodes_PHONE_CODE_EXPIRED       TLRpcErrorCodes = 400005
	TLRpcErrorCodes_API_ID_INVALID           TLRpcErrorCodes = 400006
	TLRpcErrorCodes_PHONE_NUMBER_OCCUPIED    TLRpcErrorCodes = 400007
	TLRpcErrorCodes_PHONE_NUMBER_UNOCCUPIED  TLRpcErrorCodes = 400008
	TLRpcErrorCodes_USERS_TOO_FEW            TLRpcErrorCodes = 400009
	TLRpcErrorCodes_USERS_TOO_MUCH           TLRpcErrorCodes = 400010
	TLRpcErrorCodes_TYPE_CONSTRUCTOR_INVALID TLRpcErrorCodes = 400011
	TLRpcErrorCodes_FILE_PART_INVALID        TLRpcErrorCodes = 400012
	TLRpcErrorCodes_FILE_PART_X_MISSING      TLRpcErrorCodes = 400013
	TLRpcErrorCodes_MD5_CHECKSUM_INVALID     TLRpcErrorCodes = 400014
	TLRpcErrorCodes_PHOTO_INVALID_DIMENSIONS TLRpcErrorCodes = 400015
	TLRpcErrorCodes_FIELD_NAME_INVALID       TLRpcErrorCodes = 400016
	TLRpcErrorCodes_FIELD_NAME_EMPTY         TLRpcErrorCodes = 400017
	TLRpcErrorCodes_MSG_WAIT_FAILED          TLRpcErrorCodes = 400018
	// android client code:
	//    if (error.code == 400 && "PARTICIPANT_VERSION_OUTDATED".equals(error.text)) {
	//        callFailed(VoIPController.ERROR_PEER_OUTDATED);
	TLRpcErrorCodes_PARTICIPANT_VERSION_OUTDATED TLRpcErrorCodes = 400019
	//
	TLRpcErrorCodes_PHONE_CODE_INVALID TLRpcErrorCodes = 400020
	TLRpcErrorCodes_BAD_REQUEST        TLRpcErrorCodes = 400
	// There was an unauthorized attempt to use functionality available only to authorized users.
	//
	// Examples of Errors:
	// 	AUTH_KEY_UNREGISTERED: The key is not registered in the system
	// 	AUTH_KEY_INVALID: The key is invalid
	// 	USER_DEACTIVATED: The user has been deleted/deactivated
	// 	SESSION_REVOKED: The authorization has been invalidated, because of the user terminating all sessions
	// 	SESSION_EXPIRED: The authorization has expired
	// 	ACTIVE_USER_REQUIRED: The method is only available to already activated users
	// 	AUTH_KEY_PERM_EMPTY: The method is unavailble for temporary authorization key, not bound to permanent
	//
	TLRpcErrorCodes_AUTH_KEY_UNREGISTERED TLRpcErrorCodes = 401000
	TLRpcErrorCodes_AUTH_KEY_INVALID      TLRpcErrorCodes = 401001
	TLRpcErrorCodes_USER_DEACTIVATED      TLRpcErrorCodes = 401002
	TLRpcErrorCodes_SESSION_REVOKED       TLRpcErrorCodes = 401003
	TLRpcErrorCodes_SESSION_EXPIRED       TLRpcErrorCodes = 401004
	TLRpcErrorCodes_ACTIVE_USER_REQUIRED  TLRpcErrorCodes = 401005
	TLRpcErrorCodes_AUTH_KEY_PERM_EMPTY   TLRpcErrorCodes = 401006
	// Only a small portion of the API methods are available to unauthorized users:
	//
	// auth.sendCode
	// auth.sendCall
	// auth.checkPhone
	// auth.signUp
	// auth.signIn
	// auth.importAuthorization
	// help.getConfig
	// help.getNearestDc
	//
	// Other methods will result in an error: 401 UNAUTHORIZED.
	TLRpcErrorCodes_UNAUTHORIZED TLRpcErrorCodes = 401
	// Privacy violation. For example, an attempt to write a message to someone who has blacklisted the current user.
	//
	//
	// android client code:
	//    } else if(error.code==403 && "USER_PRIVACY_RESTRICTED".equals(error.text)){
	//        callFailed(VoIPController.ERROR_PRIVACY);
	TLRpcErrorCodes_USER_PRIVACY_RESTRICTED TLRpcErrorCodes = 403000
	TLRpcErrorCodes_FORBIDDEN               TLRpcErrorCodes = 403
	// 406
	// android client code:
	// }else if(error.code==406){
	//     callFailed(VoIPController.ERROR_LOCALIZED);
	TLRpcErrorCodes_ERROR_LOCALIZED TLRpcErrorCodes = 406000
	TLRpcErrorCodes_LOCALIZED       TLRpcErrorCodes = 406
	// The maximum allowed number of attempts to invoke the given method with the given input parameters has been exceeded.
	// For example, in an attempt to request a large number of text messages (SMS) for the same phone number.
	//
	// Error Example:
	// FLOOD_WAIT_X: A wait of X seconds is required (where X is a number)
	//
	TLRpcErrorCodes_FLOOD_WAIT_X TLRpcErrorCodes = 420000
	// PEER_FLOOD
	// FLOOD_WAIT
	TLRpcErrorCodes_FLOOD TLRpcErrorCodes = 420
	// An internal server error occurred while a request was being processed;
	// for example, there was a disruption while accessing a database or file storage.
	//
	// If a client receives a 500 error, or you believe this error should not have occurred,
	// please collect as much information as possible about the query and error and send it to the developers.
	TLRpcErrorCodes_INTERNAL              TLRpcErrorCodes = 500
	TLRpcErrorCodes_INTERNAL_SERVER_ERROR TLRpcErrorCodes = 500000
	// If a server returns an error with a code other than the ones listed above,
	// it may be considered the same as a 500 error and treated as an internal server error.
	//
	TLRpcErrorCodes_OTHER TLRpcErrorCodes = 501
	//    // OFFSET_INVALID
	//    // RETRY_LIMIT
	//    // FILE_TOKEN_INVALID
	//    // REQUEST_TOKEN_INVALID
	//
	//    // CHANNEL_PRIVATE
	//    // CHANNEL_PUBLIC_GROUP_NA
	//    // USER_BANNED_IN_CHANNEL
	//
	//
	//    // MESSAGE_NOT_MODIFIED
	//
	//    // USERS_TOO_MUCH
	//
	//    // -1000
	//
	//    /////////////////////////////////////////////////////////////
	//     // android client code:
	//       } else if (request instanceof TLRPC.TL_auth_resendCode) {
	//        if (error.text.contains("PHONE_NUMBER_INVALID")) {
	//            showSimpleAlert(fragment, LocaleController.getString("InvalidPhoneNumber", R.string.InvalidPhoneNumber));
	//        } else if (error.text.contains("PHONE_CODE_EMPTY") || error.text.contains("PHONE_CODE_INVALID")) {
	//            showSimpleAlert(fragment, LocaleController.getString("InvalidCode", R.string.InvalidCode));
	//        } else if (error.text.contains("PHONE_CODE_EXPIRED")) {
	//            showSimpleAlert(fragment, LocaleController.getString("CodeExpired", R.string.CodeExpired));
	//        } else if (error.text.startsWith("FLOOD_WAIT")) {
	//            showSimpleAlert(fragment, LocaleController.getString("FloodWait", R.string.FloodWait));
	//        } else if (error.code != -1000) {
	//            showSimpleAlert(fragment, LocaleController.getString("ErrorOccurred", R.string.ErrorOccurred) + "\n" + error.text);
	//        }
	//
	//     /////////////////////////////////////////////////////////////
	//        } else if (request instanceof TLRPC.TL_updateUserName) {
	//            switch (error.text) {
	//                case "USERNAME_INVALID":
	//                    showSimpleAlert(fragment, LocaleController.getString("UsernameInvalid", R.string.UsernameInvalid));
	//                    break;
	//                case "USERNAME_OCCUPIED":
	//                    showSimpleAlert(fragment, LocaleController.getString("UsernameInUse", R.string.UsernameInUse));
	//                    break;
	//                case "USERNAMES_UNAVAILABLE":
	//                    showSimpleAlert(fragment, LocaleController.getString("FeatureUnavailable", R.string.FeatureUnavailable));
	//                    break;
	//                default:
	//                    showSimpleAlert(fragment, LocaleController.getString("ErrorOccurred", R.string.ErrorOccurred));
	//                    break;
	//            }
	//
	//     /////////////////////////////////////////////////////////////
	//            } else if (request instanceof TLRPC.TL_payments_sendPaymentForm) {
	//            switch (error.text) {
	//                case "BOT_PRECHECKOUT_FAILED":
	//                    showSimpleToast(fragment, LocaleController.getString("PaymentPrecheckoutFailed", R.string.PaymentPrecheckoutFailed));
	//                    break;
	//                case "PAYMENT_FAILED":
	//                    showSimpleToast(fragment, LocaleController.getString("PaymentFailed", R.string.PaymentFailed));
	//                    break;
	//                default:
	//                    showSimpleToast(fragment, error.text);
	//                    break;
	//            }
	//        } else if (request instanceof TLRPC.TL_payments_validateRequestedInfo) {
	//            switch (error.text) {
	//                case "SHIPPING_NOT_AVAILABLE":
	//                    showSimpleToast(fragment, LocaleController.getString("PaymentNoShippingMethod", R.string.PaymentNoShippingMethod));
	//                    break;
	//                default:
	//                    showSimpleToast(fragment, error.text);
	//                    break;
	//            }
	//        }
	//
	//     /////////////////////////////////////////////////////////////
	//
	//        } else {
	//            if (error.text.equals("2FA_RECENT_CONFIRM")) {
	//                needShowAlert(LocaleController.getString("AppName", R.string.AppName), LocaleController.getString("ResetAccountCancelledAlert", R.string.ResetAccountCancelledAlert));
	//            } else if (error.text.startsWith("2FA_CONFIRM_WAIT_")) {
	//                Bundle params = new Bundle();
	//                params.putString("phoneFormated", requestPhone);
	//                params.putString("phoneHash", phoneHash);
	//                params.putString("code", phoneCode);
	//                params.putInt("startTime", ConnectionsManager.getInstance().getCurrentTime());
	//                params.putInt("waitTime", Utilities.parseInt(error.text.replace("2FA_CONFIRM_WAIT_", "")));
	//                setPage(8, true, params, false);
	//            } else {
	TLRpcErrorCodes_OTHER2 TLRpcErrorCodes = 502
)

var TLRpcErrorCodes_name = map[int32]string{
	0:      "ERROR_CODE_OK",
	303000: "FILE_MIGRATE_X",
	303001: "PHONE_MIGRATE_X",
	303002: "NETWORK_MIGRATE_X",
	303003: "USER_MIGRATE_X",
	303:    "ERROR_SEE_OTHER",
	400000: "FIRSTNAME_INVALID",
	400001: "LASTNAME_INVALID",
	400002: "PHONE_NUMBER_INVALID",
	400003: "PHONE_CODE_HASH_EMPTY",
	400004: "PHONE_CODE_EMPTY",
	400005: "PHONE_CODE_EXPIRED",
	400006: "API_ID_INVALID",
	400007: "PHONE_NUMBER_OCCUPIED",
	400008: "PHONE_NUMBER_UNOCCUPIED",
	400009: "USERS_TOO_FEW",
	400010: "USERS_TOO_MUCH",
	400011: "TYPE_CONSTRUCTOR_INVALID",
	400012: "FILE_PART_INVALID",
	400013: "FILE_PART_X_MISSING",
	400014: "MD5_CHECKSUM_INVALID",
	400015: "PHOTO_INVALID_DIMENSIONS",
	400016: "FIELD_NAME_INVALID",
	400017: "FIELD_NAME_EMPTY",
	400018: "MSG_WAIT_FAILED",
	400019: "PARTICIPANT_VERSION_OUTDATED",
	400020: "PHONE_CODE_INVALID",
	400:    "BAD_REQUEST",
	401000: "AUTH_KEY_UNREGISTERED",
	401001: "AUTH_KEY_INVALID",
	401002: "USER_DEACTIVATED",
	401003: "SESSION_REVOKED",
	401004: "SESSION_EXPIRED",
	401005: "ACTIVE_USER_REQUIRED",
	401006: "AUTH_KEY_PERM_EMPTY",
	401:    "UNAUTHORIZED",
	403000: "USER_PRIVACY_RESTRICTED",
	403:    "FORBIDDEN",
	406000: "ERROR_LOCALIZED",
	406:    "LOCALIZED",
	420000: "FLOOD_WAIT_X",
	420:    "FLOOD",
	500:    "INTERNAL",
	500000: "INTERNAL_SERVER_ERROR",
	501:    "OTHER",
	502:    "OTHER2",
}
var TLRpcErrorCodes_value = map[string]int32{
	"ERROR_CODE_OK":                0,
	"FILE_MIGRATE_X":               303000,
	"PHONE_MIGRATE_X":              303001,
	"NETWORK_MIGRATE_X":            303002,
	"USER_MIGRATE_X":               303003,
	"ERROR_SEE_OTHER":              303,
	"FIRSTNAME_INVALID":            400000,
	"LASTNAME_INVALID":             400001,
	"PHONE_NUMBER_INVALID":         400002,
	"PHONE_CODE_HASH_EMPTY":        400003,
	"PHONE_CODE_EMPTY":             400004,
	"PHONE_CODE_EXPIRED":           400005,
	"API_ID_INVALID":               400006,
	"PHONE_NUMBER_OCCUPIED":        400007,
	"PHONE_NUMBER_UNOCCUPIED":      400008,
	"USERS_TOO_FEW":                400009,
	"USERS_TOO_MUCH":               400010,
	"TYPE_CONSTRUCTOR_INVALID":     400011,
	"FILE_PART_INVALID":            400012,
	"FILE_PART_X_MISSING":          400013,
	"MD5_CHECKSUM_INVALID":         400014,
	"PHOTO_INVALID_DIMENSIONS":     400015,
	"FIELD_NAME_INVALID":           400016,
	"FIELD_NAME_EMPTY":             400017,
	"MSG_WAIT_FAILED":              400018,
	"PARTICIPANT_VERSION_OUTDATED": 400019,
	"PHONE_CODE_INVALID":           400020,
	"BAD_REQUEST":                  400,
	"AUTH_KEY_UNREGISTERED":        401000,
	"AUTH_KEY_INVALID":             401001,
	"USER_DEACTIVATED":             401002,
	"SESSION_REVOKED":              401003,
	"SESSION_EXPIRED":              401004,
	"ACTIVE_USER_REQUIRED":         401005,
	"AUTH_KEY_PERM_EMPTY":          401006,
	"UNAUTHORIZED":                 401,
	"USER_PRIVACY_RESTRICTED":      403000,
	"FORBIDDEN":                    403,
	"ERROR_LOCALIZED":              406000,
	"LOCALIZED":                    406,
	"FLOOD_WAIT_X":                 420000,
	"FLOOD":                        420,
	"INTERNAL":                     500,
	"INTERNAL_SERVER_ERROR":        500000,
	"OTHER":                        501,
	"OTHER2":                       502,
}

func (x TLRpcErrorCodes) String() string {
	return proto.EnumName(TLRpcErrorCodes_name, int32(x))
}
func (TLRpcErrorCodes) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterEnum("mtproto.TLRpcErrorCodes", TLRpcErrorCodes_name, TLRpcErrorCodes_value)
}

func init() { proto.RegisterFile("rpc_error_codes.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 731 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x54, 0xb9, 0x6f, 0x3c, 0x35,
	0x18, 0x45, 0x59, 0x91, 0x04, 0xe7, 0x72, 0x9c, 0x84, 0x38, 0x04, 0x52, 0x50, 0x21, 0x8a, 0x2d,
	0x40, 0xfc, 0x01, 0xde, 0xf1, 0xb7, 0x3b, 0xd6, 0xce, 0xd8, 0x83, 0xed, 0xd9, 0xec, 0xd2, 0x58,
	0x64, 0x59, 0xa1, 0x48, 0x24, 0x1b, 0x2d, 0xa1, 0xe7, 0xbe, 0x8f, 0x84, 0x20, 0xc4, 0xd1, 0xa4,
	0xa0, 0xa7, 0x1a, 0x89, 0x62, 0xa5, 0x48, 0xd4, 0x34, 0x74, 0xf4, 0x34, 0xdc, 0xa2, 0x00, 0x6a,
	0x64, 0x3b, 0x7b, 0xe4, 0xf7, 0xeb, 0x3c, 0xef, 0xd9, 0xdf, 0x7b, 0x7e, 0xdf, 0xe7, 0x41, 0x3b,
	0xa3, 0xb3, 0xbe, 0x1b, 0x8c, 0x46, 0xc3, 0x91, 0xeb, 0x0f, 0x5f, 0x18, 0xbc, 0x5c, 0x3f, 0x1b,
	0x0d, 0xcf, 0x87, 0x64, 0xe9, 0xe4, 0x3c, 0x2c, 0x9e, 0xfc, 0x69, 0x19, 0x6d, 0xd8, 0x4c, 0x9f,
	0xf5, 0xc1, 0xef, 0x49, 0xfc, 0x16, 0xb2, 0x89, 0xd6, 0x40, 0x6b, 0xa5, 0x5d, 0xa2, 0x38, 0x38,
	0xd5, 0xc6, 0x0f, 0x90, 0x6d, 0xb4, 0xde, 0x14, 0x19, 0xb8, 0x5c, 0xb4, 0x34, 0xb3, 0xe0, 0xba,
	0xf8, 0x8b, 0x1b, 0x42, 0x76, 0xd0, 0x46, 0x91, 0x2a, 0x39, 0x0f, 0x7f, 0x79, 0x43, 0xc8, 0x2e,
	0xda, 0x94, 0x60, 0x0f, 0x95, 0x6e, 0xcf, 0x11, 0x5f, 0xdd, 0x10, 0x5f, 0xa5, 0x34, 0xa0, 0xe7,
	0xd0, 0xaf, 0x03, 0xba, 0x11, 0xe5, 0x0c, 0x80, 0x53, 0x36, 0x05, 0x8d, 0xbf, 0x5d, 0xf0, 0x45,
	0x9a, 0x42, 0x1b, 0x2b, 0x59, 0x0e, 0x4e, 0xc8, 0x0e, 0xcb, 0x04, 0xc7, 0xaf, 0x56, 0x94, 0x3c,
	0x8c, 0x70, 0xc6, 0xee, 0xc1, 0x5f, 0xab, 0x28, 0x79, 0x04, 0x6d, 0x47, 0x33, 0xb2, 0xcc, 0x1b,
	0xa0, 0xa7, 0xdc, 0xeb, 0x15, 0x25, 0xfb, 0x68, 0x27, 0x72, 0xe1, 0x46, 0x29, 0x33, 0xa9, 0x83,
	0xbc, 0xb0, 0x3d, 0xfc, 0x46, 0x2c, 0x38, 0x47, 0x46, 0xfc, 0xcd, 0x8a, 0x12, 0x8a, 0xc8, 0x3c,
	0xde, 0x2d, 0x84, 0x06, 0x8e, 0xdf, 0xaa, 0xa8, 0xbf, 0x07, 0x2b, 0x84, 0x13, 0x7c, 0x2a, 0xf2,
	0xf6, 0xbc, 0xc8, 0xad, 0x01, 0x95, 0x24, 0x65, 0x21, 0x80, 0xe3, 0x77, 0x2a, 0x4a, 0x1e, 0x43,
	0xbb, 0x77, 0xc8, 0x52, 0x4e, 0xe9, 0x77, 0x2b, 0x4a, 0xb6, 0xd0, 0x9a, 0x4f, 0xc6, 0x38, 0xab,
	0x94, 0x6b, 0xc2, 0x21, 0x7e, 0x2f, 0xca, 0xcc, 0xc0, 0xbc, 0x4c, 0x52, 0xfc, 0x7e, 0x45, 0xc9,
	0x01, 0xa2, 0xb6, 0x57, 0x78, 0x57, 0xd2, 0x58, 0x5d, 0x26, 0x56, 0xcd, 0xee, 0xfa, 0x41, 0x45,
	0x63, 0x70, 0x19, 0xb8, 0x82, 0x69, 0x3b, 0x25, 0x3e, 0xac, 0x28, 0xd9, 0x43, 0x5b, 0x33, 0xa2,
	0xeb, 0x72, 0x61, 0x8c, 0x90, 0x2d, 0xfc, 0x51, 0xcc, 0x2e, 0xe7, 0xcf, 0xb8, 0x24, 0x85, 0xa4,
	0x6d, 0xca, 0x7c, 0x7a, 0xec, 0xe3, 0xa8, 0x57, 0xa4, 0xca, 0xaa, 0x09, 0xe8, 0xb8, 0xc8, 0x41,
	0x1a, 0xa1, 0xa4, 0xc1, 0x9f, 0xc4, 0x98, 0x9a, 0x02, 0x32, 0xee, 0xee, 0x74, 0xe4, 0x22, 0x06,
	0x3b, 0xc7, 0xc4, 0x60, 0x2f, 0x2b, 0xea, 0xc7, 0x26, 0x37, 0x2d, 0x77, 0xc8, 0x84, 0x75, 0x4d,
	0x26, 0x32, 0xe0, 0xf8, 0xd3, 0x8a, 0x92, 0xc7, 0xd1, 0xa3, 0xde, 0x9a, 0x48, 0x44, 0xc1, 0xa4,
	0x75, 0x1d, 0xd0, 0x5e, 0xc4, 0xa9, 0xd2, 0x72, 0x66, 0x81, 0xe3, 0xab, 0xfb, 0x7a, 0x32, 0x11,
	0xfb, 0xac, 0xa2, 0x04, 0xa3, 0x95, 0x06, 0xe3, 0x4e, 0xc3, 0xb3, 0x25, 0x18, 0x8b, 0x2f, 0x6a,
	0xbe, 0x1f, 0xac, 0xb4, 0xa9, 0x6b, 0x43, 0xcf, 0x95, 0x52, 0x43, 0x4b, 0x18, 0x0b, 0xbe, 0x85,
	0xbf, 0x8c, 0x83, 0xb7, 0x29, 0x39, 0x29, 0xf3, 0x6b, 0xc4, 0xc3, 0x88, 0x72, 0x60, 0x89, 0x15,
	0x9d, 0x20, 0xfc, 0xdb, 0x38, 0x78, 0x36, 0x60, 0x82, 0x21, 0x0d, 0x1d, 0xd5, 0x06, 0x8e, 0x7f,
	0xbf, 0x0b, 0x4f, 0x06, 0xe4, 0x8f, 0x71, 0xc8, 0x33, 0x1c, 0x07, 0x17, 0x8a, 0x79, 0x53, 0x81,
	0xfb, 0x73, 0x1c, 0xda, 0x30, 0x55, 0x2e, 0x40, 0xe7, 0xb7, 0xc1, 0xfc, 0x35, 0xa6, 0x64, 0x13,
	0xad, 0x96, 0xd2, 0x93, 0x4a, 0x8b, 0xe7, 0x80, 0xe3, 0xcb, 0x9a, 0x9f, 0x9b, 0x50, 0xa2, 0xd0,
	0xa2, 0xc3, 0x92, 0x9e, 0xd3, 0x60, 0xac, 0x16, 0x89, 0xb7, 0xf5, 0xdd, 0x0f, 0x94, 0xac, 0xa3,
	0x87, 0x9a, 0x4a, 0x37, 0x04, 0xe7, 0x20, 0xf1, 0x55, 0xcd, 0xfb, 0x89, 0x6f, 0x29, 0x53, 0x09,
	0xcb, 0x42, 0x91, 0xbf, 0x7f, 0x0e, 0xdb, 0x66, 0xc0, 0xe7, 0x35, 0x42, 0xd0, 0x6a, 0x33, 0x53,
	0x8a, 0xc7, 0x1e, 0x74, 0xf1, 0xf5, 0x8f, 0x7b, 0x04, 0xa1, 0x07, 0x03, 0x86, 0xbf, 0xa9, 0x91,
	0x35, 0xb4, 0x2c, 0xa4, 0x05, 0x2d, 0x59, 0x86, 0xff, 0x09, 0x49, 0x4e, 0x3e, 0x9d, 0x01, 0xdd,
	0x01, 0xed, 0x82, 0x0a, 0xbe, 0xfe, 0xfe, 0xc0, 0x9f, 0x8b, 0x8f, 0xf6, 0xdf, 0x1a, 0x59, 0x41,
	0x8b, 0x61, 0xfd, 0x14, 0xfe, 0xaf, 0xd6, 0x78, 0x02, 0xed, 0xf7, 0x87, 0x27, 0xf5, 0xd3, 0xc1,
	0xd1, 0x2b, 0x2f, 0x3d, 0x7f, 0x7c, 0x52, 0x1f, 0x9c, 0xbe, 0x78, 0x7c, 0x3a, 0xa8, 0xdf, 0xfe,
	0x79, 0x1a, 0x4b, 0xb9, 0x2d, 0xfc, 0x22, 0x5d, 0x38, 0x5a, 0x0c, 0xc8, 0xd3, 0xff, 0x07, 0x00,
	0x00, 0xff, 0xff, 0x50, 0xbe, 0x24, 0x41, 0xad, 0x04, 0x00, 0x00,
}
