// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.tl.transport.proto

package mtproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Type forward declarations
type MsgsAck struct {
	// Types that are valid to be assigned to Payload:
	//	*MsgsAck_MsgsAck
	Payload isMsgsAck_Payload `protobuf_oneof:"payload"`
}

func (m *MsgsAck) Reset()                    { *m = MsgsAck{} }
func (m *MsgsAck) String() string            { return proto.CompactTextString(m) }
func (*MsgsAck) ProtoMessage()               {}
func (*MsgsAck) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

type isMsgsAck_Payload interface {
	isMsgsAck_Payload()
}

type MsgsAck_MsgsAck struct {
	MsgsAck *TLMsgsAck `protobuf:"bytes,1,opt,name=msgs_ack,json=msgsAck,oneof"`
}

func (*MsgsAck_MsgsAck) isMsgsAck_Payload() {}

func (m *MsgsAck) GetPayload() isMsgsAck_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *MsgsAck) GetMsgsAck() *TLMsgsAck {
	if x, ok := m.GetPayload().(*MsgsAck_MsgsAck); ok {
		return x.MsgsAck
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MsgsAck) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MsgsAck_OneofMarshaler, _MsgsAck_OneofUnmarshaler, _MsgsAck_OneofSizer, []interface{}{
		(*MsgsAck_MsgsAck)(nil),
	}
}

func _MsgsAck_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MsgsAck)
	// payload
	switch x := m.Payload.(type) {
	case *MsgsAck_MsgsAck:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MsgsAck); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("MsgsAck.Payload has unexpected type %T", x)
	}
	return nil
}

func _MsgsAck_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MsgsAck)
	switch tag {
	case 1: // payload.msgs_ack
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLMsgsAck)
		err := b.DecodeMessage(msg)
		m.Payload = &MsgsAck_MsgsAck{msg}
		return true, err
	default:
		return false, nil
	}
}

func _MsgsAck_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MsgsAck)
	// payload
	switch x := m.Payload.(type) {
	case *MsgsAck_MsgsAck:
		s := proto.Size(x.MsgsAck)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type BadMsgNotification struct {
	// Types that are valid to be assigned to Payload:
	//	*BadMsgNotification_BadMsgNotification
	//	*BadMsgNotification_BadServerSalt
	Payload isBadMsgNotification_Payload `protobuf_oneof:"payload"`
}

func (m *BadMsgNotification) Reset()                    { *m = BadMsgNotification{} }
func (m *BadMsgNotification) String() string            { return proto.CompactTextString(m) }
func (*BadMsgNotification) ProtoMessage()               {}
func (*BadMsgNotification) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

type isBadMsgNotification_Payload interface {
	isBadMsgNotification_Payload()
}

type BadMsgNotification_BadMsgNotification struct {
	BadMsgNotification *TLBadMsgNotification `protobuf:"bytes,1,opt,name=bad_msg_notification,json=badMsgNotification,oneof"`
}
type BadMsgNotification_BadServerSalt struct {
	BadServerSalt *TLBadServerSalt `protobuf:"bytes,2,opt,name=bad_server_salt,json=badServerSalt,oneof"`
}

func (*BadMsgNotification_BadMsgNotification) isBadMsgNotification_Payload() {}
func (*BadMsgNotification_BadServerSalt) isBadMsgNotification_Payload()      {}

func (m *BadMsgNotification) GetPayload() isBadMsgNotification_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *BadMsgNotification) GetBadMsgNotification() *TLBadMsgNotification {
	if x, ok := m.GetPayload().(*BadMsgNotification_BadMsgNotification); ok {
		return x.BadMsgNotification
	}
	return nil
}

func (m *BadMsgNotification) GetBadServerSalt() *TLBadServerSalt {
	if x, ok := m.GetPayload().(*BadMsgNotification_BadServerSalt); ok {
		return x.BadServerSalt
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*BadMsgNotification) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _BadMsgNotification_OneofMarshaler, _BadMsgNotification_OneofUnmarshaler, _BadMsgNotification_OneofSizer, []interface{}{
		(*BadMsgNotification_BadMsgNotification)(nil),
		(*BadMsgNotification_BadServerSalt)(nil),
	}
}

func _BadMsgNotification_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*BadMsgNotification)
	// payload
	switch x := m.Payload.(type) {
	case *BadMsgNotification_BadMsgNotification:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BadMsgNotification); err != nil {
			return err
		}
	case *BadMsgNotification_BadServerSalt:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BadServerSalt); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("BadMsgNotification.Payload has unexpected type %T", x)
	}
	return nil
}

func _BadMsgNotification_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*BadMsgNotification)
	switch tag {
	case 1: // payload.bad_msg_notification
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLBadMsgNotification)
		err := b.DecodeMessage(msg)
		m.Payload = &BadMsgNotification_BadMsgNotification{msg}
		return true, err
	case 2: // payload.bad_server_salt
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLBadServerSalt)
		err := b.DecodeMessage(msg)
		m.Payload = &BadMsgNotification_BadServerSalt{msg}
		return true, err
	default:
		return false, nil
	}
}

func _BadMsgNotification_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*BadMsgNotification)
	// payload
	switch x := m.Payload.(type) {
	case *BadMsgNotification_BadMsgNotification:
		s := proto.Size(x.BadMsgNotification)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *BadMsgNotification_BadServerSalt:
		s := proto.Size(x.BadServerSalt)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type MsgsStateReq struct {
	// Types that are valid to be assigned to Payload:
	//	*MsgsStateReq_MsgsStateReq
	Payload isMsgsStateReq_Payload `protobuf_oneof:"payload"`
}

func (m *MsgsStateReq) Reset()                    { *m = MsgsStateReq{} }
func (m *MsgsStateReq) String() string            { return proto.CompactTextString(m) }
func (*MsgsStateReq) ProtoMessage()               {}
func (*MsgsStateReq) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

type isMsgsStateReq_Payload interface {
	isMsgsStateReq_Payload()
}

type MsgsStateReq_MsgsStateReq struct {
	MsgsStateReq *TLMsgsStateReq `protobuf:"bytes,1,opt,name=msgs_state_req,json=msgsStateReq,oneof"`
}

func (*MsgsStateReq_MsgsStateReq) isMsgsStateReq_Payload() {}

func (m *MsgsStateReq) GetPayload() isMsgsStateReq_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *MsgsStateReq) GetMsgsStateReq() *TLMsgsStateReq {
	if x, ok := m.GetPayload().(*MsgsStateReq_MsgsStateReq); ok {
		return x.MsgsStateReq
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MsgsStateReq) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MsgsStateReq_OneofMarshaler, _MsgsStateReq_OneofUnmarshaler, _MsgsStateReq_OneofSizer, []interface{}{
		(*MsgsStateReq_MsgsStateReq)(nil),
	}
}

func _MsgsStateReq_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MsgsStateReq)
	// payload
	switch x := m.Payload.(type) {
	case *MsgsStateReq_MsgsStateReq:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MsgsStateReq); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("MsgsStateReq.Payload has unexpected type %T", x)
	}
	return nil
}

func _MsgsStateReq_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MsgsStateReq)
	switch tag {
	case 1: // payload.msgs_state_req
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLMsgsStateReq)
		err := b.DecodeMessage(msg)
		m.Payload = &MsgsStateReq_MsgsStateReq{msg}
		return true, err
	default:
		return false, nil
	}
}

func _MsgsStateReq_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MsgsStateReq)
	// payload
	switch x := m.Payload.(type) {
	case *MsgsStateReq_MsgsStateReq:
		s := proto.Size(x.MsgsStateReq)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type MsgsStateInfo struct {
	// Types that are valid to be assigned to Payload:
	//	*MsgsStateInfo_MsgsStateInfo
	Payload isMsgsStateInfo_Payload `protobuf_oneof:"payload"`
}

func (m *MsgsStateInfo) Reset()                    { *m = MsgsStateInfo{} }
func (m *MsgsStateInfo) String() string            { return proto.CompactTextString(m) }
func (*MsgsStateInfo) ProtoMessage()               {}
func (*MsgsStateInfo) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{3} }

type isMsgsStateInfo_Payload interface {
	isMsgsStateInfo_Payload()
}

type MsgsStateInfo_MsgsStateInfo struct {
	MsgsStateInfo *TLMsgsStateInfo `protobuf:"bytes,1,opt,name=msgs_state_info,json=msgsStateInfo,oneof"`
}

func (*MsgsStateInfo_MsgsStateInfo) isMsgsStateInfo_Payload() {}

func (m *MsgsStateInfo) GetPayload() isMsgsStateInfo_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *MsgsStateInfo) GetMsgsStateInfo() *TLMsgsStateInfo {
	if x, ok := m.GetPayload().(*MsgsStateInfo_MsgsStateInfo); ok {
		return x.MsgsStateInfo
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MsgsStateInfo) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MsgsStateInfo_OneofMarshaler, _MsgsStateInfo_OneofUnmarshaler, _MsgsStateInfo_OneofSizer, []interface{}{
		(*MsgsStateInfo_MsgsStateInfo)(nil),
	}
}

func _MsgsStateInfo_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MsgsStateInfo)
	// payload
	switch x := m.Payload.(type) {
	case *MsgsStateInfo_MsgsStateInfo:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MsgsStateInfo); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("MsgsStateInfo.Payload has unexpected type %T", x)
	}
	return nil
}

func _MsgsStateInfo_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MsgsStateInfo)
	switch tag {
	case 1: // payload.msgs_state_info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLMsgsStateInfo)
		err := b.DecodeMessage(msg)
		m.Payload = &MsgsStateInfo_MsgsStateInfo{msg}
		return true, err
	default:
		return false, nil
	}
}

func _MsgsStateInfo_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MsgsStateInfo)
	// payload
	switch x := m.Payload.(type) {
	case *MsgsStateInfo_MsgsStateInfo:
		s := proto.Size(x.MsgsStateInfo)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type MsgsAllInfo struct {
	// Types that are valid to be assigned to Payload:
	//	*MsgsAllInfo_MsgsAllInfo
	Payload isMsgsAllInfo_Payload `protobuf_oneof:"payload"`
}

func (m *MsgsAllInfo) Reset()                    { *m = MsgsAllInfo{} }
func (m *MsgsAllInfo) String() string            { return proto.CompactTextString(m) }
func (*MsgsAllInfo) ProtoMessage()               {}
func (*MsgsAllInfo) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{4} }

type isMsgsAllInfo_Payload interface {
	isMsgsAllInfo_Payload()
}

type MsgsAllInfo_MsgsAllInfo struct {
	MsgsAllInfo *TLMsgsAllInfo `protobuf:"bytes,1,opt,name=msgs_all_info,json=msgsAllInfo,oneof"`
}

func (*MsgsAllInfo_MsgsAllInfo) isMsgsAllInfo_Payload() {}

func (m *MsgsAllInfo) GetPayload() isMsgsAllInfo_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *MsgsAllInfo) GetMsgsAllInfo() *TLMsgsAllInfo {
	if x, ok := m.GetPayload().(*MsgsAllInfo_MsgsAllInfo); ok {
		return x.MsgsAllInfo
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MsgsAllInfo) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MsgsAllInfo_OneofMarshaler, _MsgsAllInfo_OneofUnmarshaler, _MsgsAllInfo_OneofSizer, []interface{}{
		(*MsgsAllInfo_MsgsAllInfo)(nil),
	}
}

func _MsgsAllInfo_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MsgsAllInfo)
	// payload
	switch x := m.Payload.(type) {
	case *MsgsAllInfo_MsgsAllInfo:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MsgsAllInfo); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("MsgsAllInfo.Payload has unexpected type %T", x)
	}
	return nil
}

func _MsgsAllInfo_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MsgsAllInfo)
	switch tag {
	case 1: // payload.msgs_all_info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLMsgsAllInfo)
		err := b.DecodeMessage(msg)
		m.Payload = &MsgsAllInfo_MsgsAllInfo{msg}
		return true, err
	default:
		return false, nil
	}
}

func _MsgsAllInfo_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MsgsAllInfo)
	// payload
	switch x := m.Payload.(type) {
	case *MsgsAllInfo_MsgsAllInfo:
		s := proto.Size(x.MsgsAllInfo)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type MsgDetailedInfo struct {
	// Types that are valid to be assigned to Payload:
	//	*MsgDetailedInfo_MsgDetailedInfo
	//	*MsgDetailedInfo_MsgNewDetailedInfo
	Payload isMsgDetailedInfo_Payload `protobuf_oneof:"payload"`
}

func (m *MsgDetailedInfo) Reset()                    { *m = MsgDetailedInfo{} }
func (m *MsgDetailedInfo) String() string            { return proto.CompactTextString(m) }
func (*MsgDetailedInfo) ProtoMessage()               {}
func (*MsgDetailedInfo) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{5} }

type isMsgDetailedInfo_Payload interface {
	isMsgDetailedInfo_Payload()
}

type MsgDetailedInfo_MsgDetailedInfo struct {
	MsgDetailedInfo *TLMsgDetailedInfo `protobuf:"bytes,1,opt,name=msg_detailed_info,json=msgDetailedInfo,oneof"`
}
type MsgDetailedInfo_MsgNewDetailedInfo struct {
	MsgNewDetailedInfo *TLMsgNewDetailedInfo `protobuf:"bytes,2,opt,name=msg_new_detailed_info,json=msgNewDetailedInfo,oneof"`
}

func (*MsgDetailedInfo_MsgDetailedInfo) isMsgDetailedInfo_Payload()    {}
func (*MsgDetailedInfo_MsgNewDetailedInfo) isMsgDetailedInfo_Payload() {}

func (m *MsgDetailedInfo) GetPayload() isMsgDetailedInfo_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *MsgDetailedInfo) GetMsgDetailedInfo() *TLMsgDetailedInfo {
	if x, ok := m.GetPayload().(*MsgDetailedInfo_MsgDetailedInfo); ok {
		return x.MsgDetailedInfo
	}
	return nil
}

func (m *MsgDetailedInfo) GetMsgNewDetailedInfo() *TLMsgNewDetailedInfo {
	if x, ok := m.GetPayload().(*MsgDetailedInfo_MsgNewDetailedInfo); ok {
		return x.MsgNewDetailedInfo
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MsgDetailedInfo) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MsgDetailedInfo_OneofMarshaler, _MsgDetailedInfo_OneofUnmarshaler, _MsgDetailedInfo_OneofSizer, []interface{}{
		(*MsgDetailedInfo_MsgDetailedInfo)(nil),
		(*MsgDetailedInfo_MsgNewDetailedInfo)(nil),
	}
}

func _MsgDetailedInfo_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MsgDetailedInfo)
	// payload
	switch x := m.Payload.(type) {
	case *MsgDetailedInfo_MsgDetailedInfo:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MsgDetailedInfo); err != nil {
			return err
		}
	case *MsgDetailedInfo_MsgNewDetailedInfo:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MsgNewDetailedInfo); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("MsgDetailedInfo.Payload has unexpected type %T", x)
	}
	return nil
}

func _MsgDetailedInfo_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MsgDetailedInfo)
	switch tag {
	case 1: // payload.msg_detailed_info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLMsgDetailedInfo)
		err := b.DecodeMessage(msg)
		m.Payload = &MsgDetailedInfo_MsgDetailedInfo{msg}
		return true, err
	case 2: // payload.msg_new_detailed_info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLMsgNewDetailedInfo)
		err := b.DecodeMessage(msg)
		m.Payload = &MsgDetailedInfo_MsgNewDetailedInfo{msg}
		return true, err
	default:
		return false, nil
	}
}

func _MsgDetailedInfo_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MsgDetailedInfo)
	// payload
	switch x := m.Payload.(type) {
	case *MsgDetailedInfo_MsgDetailedInfo:
		s := proto.Size(x.MsgDetailedInfo)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MsgDetailedInfo_MsgNewDetailedInfo:
		s := proto.Size(x.MsgNewDetailedInfo)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type MsgResendReq struct {
	// Types that are valid to be assigned to Payload:
	//	*MsgResendReq_MsgResendReq
	Payload isMsgResendReq_Payload `protobuf_oneof:"payload"`
}

func (m *MsgResendReq) Reset()                    { *m = MsgResendReq{} }
func (m *MsgResendReq) String() string            { return proto.CompactTextString(m) }
func (*MsgResendReq) ProtoMessage()               {}
func (*MsgResendReq) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{6} }

type isMsgResendReq_Payload interface {
	isMsgResendReq_Payload()
}

type MsgResendReq_MsgResendReq struct {
	MsgResendReq *TLMsgResendReq `protobuf:"bytes,1,opt,name=msg_resend_req,json=msgResendReq,oneof"`
}

func (*MsgResendReq_MsgResendReq) isMsgResendReq_Payload() {}

func (m *MsgResendReq) GetPayload() isMsgResendReq_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *MsgResendReq) GetMsgResendReq() *TLMsgResendReq {
	if x, ok := m.GetPayload().(*MsgResendReq_MsgResendReq); ok {
		return x.MsgResendReq
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MsgResendReq) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MsgResendReq_OneofMarshaler, _MsgResendReq_OneofUnmarshaler, _MsgResendReq_OneofSizer, []interface{}{
		(*MsgResendReq_MsgResendReq)(nil),
	}
}

func _MsgResendReq_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MsgResendReq)
	// payload
	switch x := m.Payload.(type) {
	case *MsgResendReq_MsgResendReq:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MsgResendReq); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("MsgResendReq.Payload has unexpected type %T", x)
	}
	return nil
}

func _MsgResendReq_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MsgResendReq)
	switch tag {
	case 1: // payload.msg_resend_req
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLMsgResendReq)
		err := b.DecodeMessage(msg)
		m.Payload = &MsgResendReq_MsgResendReq{msg}
		return true, err
	default:
		return false, nil
	}
}

func _MsgResendReq_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MsgResendReq)
	// payload
	switch x := m.Payload.(type) {
	case *MsgResendReq_MsgResendReq:
		s := proto.Size(x.MsgResendReq)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type RpcError struct {
	// Types that are valid to be assigned to Payload:
	//	*RpcError_RpcError
	Payload isRpcError_Payload `protobuf_oneof:"payload"`
}

func (m *RpcError) Reset()                    { *m = RpcError{} }
func (m *RpcError) String() string            { return proto.CompactTextString(m) }
func (*RpcError) ProtoMessage()               {}
func (*RpcError) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{7} }

type isRpcError_Payload interface {
	isRpcError_Payload()
}

type RpcError_RpcError struct {
	RpcError *TLRpcError `protobuf:"bytes,1,opt,name=rpc_error,json=rpcError,oneof"`
}

func (*RpcError_RpcError) isRpcError_Payload() {}

func (m *RpcError) GetPayload() isRpcError_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *RpcError) GetRpcError() *TLRpcError {
	if x, ok := m.GetPayload().(*RpcError_RpcError); ok {
		return x.RpcError
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RpcError) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RpcError_OneofMarshaler, _RpcError_OneofUnmarshaler, _RpcError_OneofSizer, []interface{}{
		(*RpcError_RpcError)(nil),
	}
}

func _RpcError_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RpcError)
	// payload
	switch x := m.Payload.(type) {
	case *RpcError_RpcError:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RpcError); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("RpcError.Payload has unexpected type %T", x)
	}
	return nil
}

func _RpcError_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RpcError)
	switch tag {
	case 1: // payload.rpc_error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLRpcError)
		err := b.DecodeMessage(msg)
		m.Payload = &RpcError_RpcError{msg}
		return true, err
	default:
		return false, nil
	}
}

func _RpcError_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RpcError)
	// payload
	switch x := m.Payload.(type) {
	case *RpcError_RpcError:
		s := proto.Size(x.RpcError)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type RpcDropAnswer struct {
	// Types that are valid to be assigned to Payload:
	//	*RpcDropAnswer_RpcAnswerUnknown
	//	*RpcDropAnswer_RpcAnswerDroppedRunning
	//	*RpcDropAnswer_RpcAnswerDropped
	Payload isRpcDropAnswer_Payload `protobuf_oneof:"payload"`
}

func (m *RpcDropAnswer) Reset()                    { *m = RpcDropAnswer{} }
func (m *RpcDropAnswer) String() string            { return proto.CompactTextString(m) }
func (*RpcDropAnswer) ProtoMessage()               {}
func (*RpcDropAnswer) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{8} }

type isRpcDropAnswer_Payload interface {
	isRpcDropAnswer_Payload()
}

type RpcDropAnswer_RpcAnswerUnknown struct {
	RpcAnswerUnknown *TLRpcAnswerUnknown `protobuf:"bytes,1,opt,name=rpc_answer_unknown,json=rpcAnswerUnknown,oneof"`
}
type RpcDropAnswer_RpcAnswerDroppedRunning struct {
	RpcAnswerDroppedRunning *TLRpcAnswerDroppedRunning `protobuf:"bytes,2,opt,name=rpc_answer_dropped_running,json=rpcAnswerDroppedRunning,oneof"`
}
type RpcDropAnswer_RpcAnswerDropped struct {
	RpcAnswerDropped *TLRpcAnswerDropped `protobuf:"bytes,3,opt,name=rpc_answer_dropped,json=rpcAnswerDropped,oneof"`
}

func (*RpcDropAnswer_RpcAnswerUnknown) isRpcDropAnswer_Payload()        {}
func (*RpcDropAnswer_RpcAnswerDroppedRunning) isRpcDropAnswer_Payload() {}
func (*RpcDropAnswer_RpcAnswerDropped) isRpcDropAnswer_Payload()        {}

func (m *RpcDropAnswer) GetPayload() isRpcDropAnswer_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *RpcDropAnswer) GetRpcAnswerUnknown() *TLRpcAnswerUnknown {
	if x, ok := m.GetPayload().(*RpcDropAnswer_RpcAnswerUnknown); ok {
		return x.RpcAnswerUnknown
	}
	return nil
}

func (m *RpcDropAnswer) GetRpcAnswerDroppedRunning() *TLRpcAnswerDroppedRunning {
	if x, ok := m.GetPayload().(*RpcDropAnswer_RpcAnswerDroppedRunning); ok {
		return x.RpcAnswerDroppedRunning
	}
	return nil
}

func (m *RpcDropAnswer) GetRpcAnswerDropped() *TLRpcAnswerDropped {
	if x, ok := m.GetPayload().(*RpcDropAnswer_RpcAnswerDropped); ok {
		return x.RpcAnswerDropped
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RpcDropAnswer) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RpcDropAnswer_OneofMarshaler, _RpcDropAnswer_OneofUnmarshaler, _RpcDropAnswer_OneofSizer, []interface{}{
		(*RpcDropAnswer_RpcAnswerUnknown)(nil),
		(*RpcDropAnswer_RpcAnswerDroppedRunning)(nil),
		(*RpcDropAnswer_RpcAnswerDropped)(nil),
	}
}

func _RpcDropAnswer_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RpcDropAnswer)
	// payload
	switch x := m.Payload.(type) {
	case *RpcDropAnswer_RpcAnswerUnknown:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RpcAnswerUnknown); err != nil {
			return err
		}
	case *RpcDropAnswer_RpcAnswerDroppedRunning:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RpcAnswerDroppedRunning); err != nil {
			return err
		}
	case *RpcDropAnswer_RpcAnswerDropped:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RpcAnswerDropped); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("RpcDropAnswer.Payload has unexpected type %T", x)
	}
	return nil
}

func _RpcDropAnswer_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RpcDropAnswer)
	switch tag {
	case 1: // payload.rpc_answer_unknown
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLRpcAnswerUnknown)
		err := b.DecodeMessage(msg)
		m.Payload = &RpcDropAnswer_RpcAnswerUnknown{msg}
		return true, err
	case 2: // payload.rpc_answer_dropped_running
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLRpcAnswerDroppedRunning)
		err := b.DecodeMessage(msg)
		m.Payload = &RpcDropAnswer_RpcAnswerDroppedRunning{msg}
		return true, err
	case 3: // payload.rpc_answer_dropped
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLRpcAnswerDropped)
		err := b.DecodeMessage(msg)
		m.Payload = &RpcDropAnswer_RpcAnswerDropped{msg}
		return true, err
	default:
		return false, nil
	}
}

func _RpcDropAnswer_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RpcDropAnswer)
	// payload
	switch x := m.Payload.(type) {
	case *RpcDropAnswer_RpcAnswerUnknown:
		s := proto.Size(x.RpcAnswerUnknown)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RpcDropAnswer_RpcAnswerDroppedRunning:
		s := proto.Size(x.RpcAnswerDroppedRunning)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RpcDropAnswer_RpcAnswerDropped:
		s := proto.Size(x.RpcAnswerDropped)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type FutureSalt struct {
	// Types that are valid to be assigned to Payload:
	//	*FutureSalt_FutureSalt
	Payload isFutureSalt_Payload `protobuf_oneof:"payload"`
}

func (m *FutureSalt) Reset()                    { *m = FutureSalt{} }
func (m *FutureSalt) String() string            { return proto.CompactTextString(m) }
func (*FutureSalt) ProtoMessage()               {}
func (*FutureSalt) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{9} }

type isFutureSalt_Payload interface {
	isFutureSalt_Payload()
}

type FutureSalt_FutureSalt struct {
	FutureSalt *TLFutureSalt `protobuf:"bytes,1,opt,name=future_salt,json=futureSalt,oneof"`
}

func (*FutureSalt_FutureSalt) isFutureSalt_Payload() {}

func (m *FutureSalt) GetPayload() isFutureSalt_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *FutureSalt) GetFutureSalt() *TLFutureSalt {
	if x, ok := m.GetPayload().(*FutureSalt_FutureSalt); ok {
		return x.FutureSalt
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*FutureSalt) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _FutureSalt_OneofMarshaler, _FutureSalt_OneofUnmarshaler, _FutureSalt_OneofSizer, []interface{}{
		(*FutureSalt_FutureSalt)(nil),
	}
}

func _FutureSalt_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*FutureSalt)
	// payload
	switch x := m.Payload.(type) {
	case *FutureSalt_FutureSalt:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FutureSalt); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("FutureSalt.Payload has unexpected type %T", x)
	}
	return nil
}

func _FutureSalt_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*FutureSalt)
	switch tag {
	case 1: // payload.future_salt
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLFutureSalt)
		err := b.DecodeMessage(msg)
		m.Payload = &FutureSalt_FutureSalt{msg}
		return true, err
	default:
		return false, nil
	}
}

func _FutureSalt_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*FutureSalt)
	// payload
	switch x := m.Payload.(type) {
	case *FutureSalt_FutureSalt:
		s := proto.Size(x.FutureSalt)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type FutureSalts struct {
	// Types that are valid to be assigned to Payload:
	//	*FutureSalts_FutureSalts
	Payload isFutureSalts_Payload `protobuf_oneof:"payload"`
}

func (m *FutureSalts) Reset()                    { *m = FutureSalts{} }
func (m *FutureSalts) String() string            { return proto.CompactTextString(m) }
func (*FutureSalts) ProtoMessage()               {}
func (*FutureSalts) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{10} }

type isFutureSalts_Payload interface {
	isFutureSalts_Payload()
}

type FutureSalts_FutureSalts struct {
	FutureSalts *TLFutureSalts `protobuf:"bytes,1,opt,name=future_salts,json=futureSalts,oneof"`
}

func (*FutureSalts_FutureSalts) isFutureSalts_Payload() {}

func (m *FutureSalts) GetPayload() isFutureSalts_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *FutureSalts) GetFutureSalts() *TLFutureSalts {
	if x, ok := m.GetPayload().(*FutureSalts_FutureSalts); ok {
		return x.FutureSalts
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*FutureSalts) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _FutureSalts_OneofMarshaler, _FutureSalts_OneofUnmarshaler, _FutureSalts_OneofSizer, []interface{}{
		(*FutureSalts_FutureSalts)(nil),
	}
}

func _FutureSalts_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*FutureSalts)
	// payload
	switch x := m.Payload.(type) {
	case *FutureSalts_FutureSalts:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FutureSalts); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("FutureSalts.Payload has unexpected type %T", x)
	}
	return nil
}

func _FutureSalts_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*FutureSalts)
	switch tag {
	case 1: // payload.future_salts
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLFutureSalts)
		err := b.DecodeMessage(msg)
		m.Payload = &FutureSalts_FutureSalts{msg}
		return true, err
	default:
		return false, nil
	}
}

func _FutureSalts_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*FutureSalts)
	// payload
	switch x := m.Payload.(type) {
	case *FutureSalts_FutureSalts:
		s := proto.Size(x.FutureSalts)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Pong struct {
	// Types that are valid to be assigned to Payload:
	//	*Pong_Pong
	Payload isPong_Payload `protobuf_oneof:"payload"`
}

func (m *Pong) Reset()                    { *m = Pong{} }
func (m *Pong) String() string            { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()               {}
func (*Pong) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{11} }

type isPong_Payload interface {
	isPong_Payload()
}

type Pong_Pong struct {
	Pong *TLPong `protobuf:"bytes,1,opt,name=pong,oneof"`
}

func (*Pong_Pong) isPong_Payload() {}

func (m *Pong) GetPayload() isPong_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Pong) GetPong() *TLPong {
	if x, ok := m.GetPayload().(*Pong_Pong); ok {
		return x.Pong
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Pong) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Pong_OneofMarshaler, _Pong_OneofUnmarshaler, _Pong_OneofSizer, []interface{}{
		(*Pong_Pong)(nil),
	}
}

func _Pong_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Pong)
	// payload
	switch x := m.Payload.(type) {
	case *Pong_Pong:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Pong); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Pong.Payload has unexpected type %T", x)
	}
	return nil
}

func _Pong_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Pong)
	switch tag {
	case 1: // payload.pong
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLPong)
		err := b.DecodeMessage(msg)
		m.Payload = &Pong_Pong{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Pong_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Pong)
	// payload
	switch x := m.Payload.(type) {
	case *Pong_Pong:
		s := proto.Size(x.Pong)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type DestroySessionRes struct {
	// Types that are valid to be assigned to Payload:
	//	*DestroySessionRes_DestroySessionOk
	//	*DestroySessionRes_DestroySessionNone
	Payload isDestroySessionRes_Payload `protobuf_oneof:"payload"`
}

func (m *DestroySessionRes) Reset()                    { *m = DestroySessionRes{} }
func (m *DestroySessionRes) String() string            { return proto.CompactTextString(m) }
func (*DestroySessionRes) ProtoMessage()               {}
func (*DestroySessionRes) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{12} }

type isDestroySessionRes_Payload interface {
	isDestroySessionRes_Payload()
}

type DestroySessionRes_DestroySessionOk struct {
	DestroySessionOk *TLDestroySessionOk `protobuf:"bytes,1,opt,name=destroy_session_ok,json=destroySessionOk,oneof"`
}
type DestroySessionRes_DestroySessionNone struct {
	DestroySessionNone *TLDestroySessionNone `protobuf:"bytes,2,opt,name=destroy_session_none,json=destroySessionNone,oneof"`
}

func (*DestroySessionRes_DestroySessionOk) isDestroySessionRes_Payload()   {}
func (*DestroySessionRes_DestroySessionNone) isDestroySessionRes_Payload() {}

func (m *DestroySessionRes) GetPayload() isDestroySessionRes_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *DestroySessionRes) GetDestroySessionOk() *TLDestroySessionOk {
	if x, ok := m.GetPayload().(*DestroySessionRes_DestroySessionOk); ok {
		return x.DestroySessionOk
	}
	return nil
}

func (m *DestroySessionRes) GetDestroySessionNone() *TLDestroySessionNone {
	if x, ok := m.GetPayload().(*DestroySessionRes_DestroySessionNone); ok {
		return x.DestroySessionNone
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*DestroySessionRes) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _DestroySessionRes_OneofMarshaler, _DestroySessionRes_OneofUnmarshaler, _DestroySessionRes_OneofSizer, []interface{}{
		(*DestroySessionRes_DestroySessionOk)(nil),
		(*DestroySessionRes_DestroySessionNone)(nil),
	}
}

func _DestroySessionRes_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*DestroySessionRes)
	// payload
	switch x := m.Payload.(type) {
	case *DestroySessionRes_DestroySessionOk:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DestroySessionOk); err != nil {
			return err
		}
	case *DestroySessionRes_DestroySessionNone:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DestroySessionNone); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("DestroySessionRes.Payload has unexpected type %T", x)
	}
	return nil
}

func _DestroySessionRes_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*DestroySessionRes)
	switch tag {
	case 1: // payload.destroy_session_ok
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLDestroySessionOk)
		err := b.DecodeMessage(msg)
		m.Payload = &DestroySessionRes_DestroySessionOk{msg}
		return true, err
	case 2: // payload.destroy_session_none
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLDestroySessionNone)
		err := b.DecodeMessage(msg)
		m.Payload = &DestroySessionRes_DestroySessionNone{msg}
		return true, err
	default:
		return false, nil
	}
}

func _DestroySessionRes_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*DestroySessionRes)
	// payload
	switch x := m.Payload.(type) {
	case *DestroySessionRes_DestroySessionOk:
		s := proto.Size(x.DestroySessionOk)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *DestroySessionRes_DestroySessionNone:
		s := proto.Size(x.DestroySessionNone)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type NewSession struct {
	// Types that are valid to be assigned to Payload:
	//	*NewSession_NewSessionCreated
	Payload isNewSession_Payload `protobuf_oneof:"payload"`
}

func (m *NewSession) Reset()                    { *m = NewSession{} }
func (m *NewSession) String() string            { return proto.CompactTextString(m) }
func (*NewSession) ProtoMessage()               {}
func (*NewSession) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{13} }

type isNewSession_Payload interface {
	isNewSession_Payload()
}

type NewSession_NewSessionCreated struct {
	NewSessionCreated *TLNewSessionCreated `protobuf:"bytes,1,opt,name=new_session_created,json=newSessionCreated,oneof"`
}

func (*NewSession_NewSessionCreated) isNewSession_Payload() {}

func (m *NewSession) GetPayload() isNewSession_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *NewSession) GetNewSessionCreated() *TLNewSessionCreated {
	if x, ok := m.GetPayload().(*NewSession_NewSessionCreated); ok {
		return x.NewSessionCreated
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*NewSession) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _NewSession_OneofMarshaler, _NewSession_OneofUnmarshaler, _NewSession_OneofSizer, []interface{}{
		(*NewSession_NewSessionCreated)(nil),
	}
}

func _NewSession_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*NewSession)
	// payload
	switch x := m.Payload.(type) {
	case *NewSession_NewSessionCreated:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NewSessionCreated); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("NewSession.Payload has unexpected type %T", x)
	}
	return nil
}

func _NewSession_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*NewSession)
	switch tag {
	case 1: // payload.new_session_created
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLNewSessionCreated)
		err := b.DecodeMessage(msg)
		m.Payload = &NewSession_NewSessionCreated{msg}
		return true, err
	default:
		return false, nil
	}
}

func _NewSession_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*NewSession)
	// payload
	switch x := m.Payload.(type) {
	case *NewSession_NewSessionCreated:
		s := proto.Size(x.NewSessionCreated)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type HttpWait struct {
	// Types that are valid to be assigned to Payload:
	//	*HttpWait_HttpWait
	Payload isHttpWait_Payload `protobuf_oneof:"payload"`
}

func (m *HttpWait) Reset()                    { *m = HttpWait{} }
func (m *HttpWait) String() string            { return proto.CompactTextString(m) }
func (*HttpWait) ProtoMessage()               {}
func (*HttpWait) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{14} }

type isHttpWait_Payload interface {
	isHttpWait_Payload()
}

type HttpWait_HttpWait struct {
	HttpWait *TLHttpWait `protobuf:"bytes,1,opt,name=http_wait,json=httpWait,oneof"`
}

func (*HttpWait_HttpWait) isHttpWait_Payload() {}

func (m *HttpWait) GetPayload() isHttpWait_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *HttpWait) GetHttpWait() *TLHttpWait {
	if x, ok := m.GetPayload().(*HttpWait_HttpWait); ok {
		return x.HttpWait
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*HttpWait) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _HttpWait_OneofMarshaler, _HttpWait_OneofUnmarshaler, _HttpWait_OneofSizer, []interface{}{
		(*HttpWait_HttpWait)(nil),
	}
}

func _HttpWait_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*HttpWait)
	// payload
	switch x := m.Payload.(type) {
	case *HttpWait_HttpWait:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HttpWait); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("HttpWait.Payload has unexpected type %T", x)
	}
	return nil
}

func _HttpWait_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*HttpWait)
	switch tag {
	case 1: // payload.http_wait
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLHttpWait)
		err := b.DecodeMessage(msg)
		m.Payload = &HttpWait_HttpWait{msg}
		return true, err
	default:
		return false, nil
	}
}

func _HttpWait_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*HttpWait)
	// payload
	switch x := m.Payload.(type) {
	case *HttpWait_HttpWait:
		s := proto.Size(x.HttpWait)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type IpPort struct {
	// Types that are valid to be assigned to Payload:
	//	*IpPort_IpPort
	Payload isIpPort_Payload `protobuf_oneof:"payload"`
}

func (m *IpPort) Reset()                    { *m = IpPort{} }
func (m *IpPort) String() string            { return proto.CompactTextString(m) }
func (*IpPort) ProtoMessage()               {}
func (*IpPort) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{15} }

type isIpPort_Payload interface {
	isIpPort_Payload()
}

type IpPort_IpPort struct {
	IpPort *TLIpPort `protobuf:"bytes,1,opt,name=ipPort,oneof"`
}

func (*IpPort_IpPort) isIpPort_Payload() {}

func (m *IpPort) GetPayload() isIpPort_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *IpPort) GetIpPort() *TLIpPort {
	if x, ok := m.GetPayload().(*IpPort_IpPort); ok {
		return x.IpPort
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*IpPort) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _IpPort_OneofMarshaler, _IpPort_OneofUnmarshaler, _IpPort_OneofSizer, []interface{}{
		(*IpPort_IpPort)(nil),
	}
}

func _IpPort_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*IpPort)
	// payload
	switch x := m.Payload.(type) {
	case *IpPort_IpPort:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.IpPort); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("IpPort.Payload has unexpected type %T", x)
	}
	return nil
}

func _IpPort_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*IpPort)
	switch tag {
	case 1: // payload.ipPort
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLIpPort)
		err := b.DecodeMessage(msg)
		m.Payload = &IpPort_IpPort{msg}
		return true, err
	default:
		return false, nil
	}
}

func _IpPort_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*IpPort)
	// payload
	switch x := m.Payload.(type) {
	case *IpPort_IpPort:
		s := proto.Size(x.IpPort)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Help_ConfigSimple struct {
	// Types that are valid to be assigned to Payload:
	//	*Help_ConfigSimple_HelpConfigSimple
	Payload isHelp_ConfigSimple_Payload `protobuf_oneof:"payload"`
}

func (m *Help_ConfigSimple) Reset()                    { *m = Help_ConfigSimple{} }
func (m *Help_ConfigSimple) String() string            { return proto.CompactTextString(m) }
func (*Help_ConfigSimple) ProtoMessage()               {}
func (*Help_ConfigSimple) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{16} }

type isHelp_ConfigSimple_Payload interface {
	isHelp_ConfigSimple_Payload()
}

type Help_ConfigSimple_HelpConfigSimple struct {
	HelpConfigSimple *TLHelpConfigSimple `protobuf:"bytes,1,opt,name=help_configSimple,json=helpConfigSimple,oneof"`
}

func (*Help_ConfigSimple_HelpConfigSimple) isHelp_ConfigSimple_Payload() {}

func (m *Help_ConfigSimple) GetPayload() isHelp_ConfigSimple_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Help_ConfigSimple) GetHelpConfigSimple() *TLHelpConfigSimple {
	if x, ok := m.GetPayload().(*Help_ConfigSimple_HelpConfigSimple); ok {
		return x.HelpConfigSimple
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Help_ConfigSimple) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Help_ConfigSimple_OneofMarshaler, _Help_ConfigSimple_OneofUnmarshaler, _Help_ConfigSimple_OneofSizer, []interface{}{
		(*Help_ConfigSimple_HelpConfigSimple)(nil),
	}
}

func _Help_ConfigSimple_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Help_ConfigSimple)
	// payload
	switch x := m.Payload.(type) {
	case *Help_ConfigSimple_HelpConfigSimple:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HelpConfigSimple); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Help_ConfigSimple.Payload has unexpected type %T", x)
	}
	return nil
}

func _Help_ConfigSimple_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Help_ConfigSimple)
	switch tag {
	case 1: // payload.help_configSimple
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TLHelpConfigSimple)
		err := b.DecodeMessage(msg)
		m.Payload = &Help_ConfigSimple_HelpConfigSimple{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Help_ConfigSimple_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Help_ConfigSimple)
	// payload
	switch x := m.Payload.(type) {
	case *Help_ConfigSimple_HelpConfigSimple:
		s := proto.Size(x.HelpConfigSimple)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// msgs_ack#62d6b459 msg_ids:Vector<long> = MsgsAck;
type TLMsgsAck struct {
	MsgIds []int64 `protobuf:"varint,1,rep,packed,name=msg_ids,json=msgIds" json:"msg_ids,omitempty"`
}

func (m *TLMsgsAck) Reset()                    { *m = TLMsgsAck{} }
func (m *TLMsgsAck) String() string            { return proto.CompactTextString(m) }
func (*TLMsgsAck) ProtoMessage()               {}
func (*TLMsgsAck) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{17} }

func (m *TLMsgsAck) GetMsgIds() []int64 {
	if m != nil {
		return m.MsgIds
	}
	return nil
}

// bad_msg_notification#a7eff811 bad_msg_id:long bad_msg_seqno:int error_code:int = BadMsgNotification;
type TLBadMsgNotification struct {
	BadMsgId    int64 `protobuf:"varint,1,opt,name=bad_msg_id,json=badMsgId" json:"bad_msg_id,omitempty"`
	BadMsgSeqno int32 `protobuf:"varint,2,opt,name=bad_msg_seqno,json=badMsgSeqno" json:"bad_msg_seqno,omitempty"`
	ErrorCode   int32 `protobuf:"varint,3,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *TLBadMsgNotification) Reset()                    { *m = TLBadMsgNotification{} }
func (m *TLBadMsgNotification) String() string            { return proto.CompactTextString(m) }
func (*TLBadMsgNotification) ProtoMessage()               {}
func (*TLBadMsgNotification) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{18} }

func (m *TLBadMsgNotification) GetBadMsgId() int64 {
	if m != nil {
		return m.BadMsgId
	}
	return 0
}

func (m *TLBadMsgNotification) GetBadMsgSeqno() int32 {
	if m != nil {
		return m.BadMsgSeqno
	}
	return 0
}

func (m *TLBadMsgNotification) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// bad_server_salt#edab447b bad_msg_id:long bad_msg_seqno:int error_code:int new_server_salt:long = BadMsgNotification;
type TLBadServerSalt struct {
	BadMsgId      int64 `protobuf:"varint,1,opt,name=bad_msg_id,json=badMsgId" json:"bad_msg_id,omitempty"`
	BadMsgSeqno   int32 `protobuf:"varint,2,opt,name=bad_msg_seqno,json=badMsgSeqno" json:"bad_msg_seqno,omitempty"`
	ErrorCode     int32 `protobuf:"varint,3,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	NewServerSalt int64 `protobuf:"varint,4,opt,name=new_server_salt,json=newServerSalt" json:"new_server_salt,omitempty"`
}

func (m *TLBadServerSalt) Reset()                    { *m = TLBadServerSalt{} }
func (m *TLBadServerSalt) String() string            { return proto.CompactTextString(m) }
func (*TLBadServerSalt) ProtoMessage()               {}
func (*TLBadServerSalt) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{19} }

func (m *TLBadServerSalt) GetBadMsgId() int64 {
	if m != nil {
		return m.BadMsgId
	}
	return 0
}

func (m *TLBadServerSalt) GetBadMsgSeqno() int32 {
	if m != nil {
		return m.BadMsgSeqno
	}
	return 0
}

func (m *TLBadServerSalt) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *TLBadServerSalt) GetNewServerSalt() int64 {
	if m != nil {
		return m.NewServerSalt
	}
	return 0
}

// msgs_state_req#da69fb52 msg_ids:Vector<long> = MsgsStateReq;
type TLMsgsStateReq struct {
	MsgIds []int64 `protobuf:"varint,1,rep,packed,name=msg_ids,json=msgIds" json:"msg_ids,omitempty"`
}

func (m *TLMsgsStateReq) Reset()                    { *m = TLMsgsStateReq{} }
func (m *TLMsgsStateReq) String() string            { return proto.CompactTextString(m) }
func (*TLMsgsStateReq) ProtoMessage()               {}
func (*TLMsgsStateReq) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{20} }

func (m *TLMsgsStateReq) GetMsgIds() []int64 {
	if m != nil {
		return m.MsgIds
	}
	return nil
}

// msgs_state_info#04deb57d req_msg_id:long info:string = MsgsStateInfo;
type TLMsgsStateInfo struct {
	ReqMsgId int64  `protobuf:"varint,1,opt,name=req_msg_id,json=reqMsgId" json:"req_msg_id,omitempty"`
	Info     string `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *TLMsgsStateInfo) Reset()                    { *m = TLMsgsStateInfo{} }
func (m *TLMsgsStateInfo) String() string            { return proto.CompactTextString(m) }
func (*TLMsgsStateInfo) ProtoMessage()               {}
func (*TLMsgsStateInfo) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{21} }

func (m *TLMsgsStateInfo) GetReqMsgId() int64 {
	if m != nil {
		return m.ReqMsgId
	}
	return 0
}

func (m *TLMsgsStateInfo) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

// msgs_all_info#8cc0d131 msg_ids:Vector<long> info:string = MsgsAllInfo;
type TLMsgsAllInfo struct {
	MsgIds []int64 `protobuf:"varint,1,rep,packed,name=msg_ids,json=msgIds" json:"msg_ids,omitempty"`
	Info   string  `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *TLMsgsAllInfo) Reset()                    { *m = TLMsgsAllInfo{} }
func (m *TLMsgsAllInfo) String() string            { return proto.CompactTextString(m) }
func (*TLMsgsAllInfo) ProtoMessage()               {}
func (*TLMsgsAllInfo) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{22} }

func (m *TLMsgsAllInfo) GetMsgIds() []int64 {
	if m != nil {
		return m.MsgIds
	}
	return nil
}

func (m *TLMsgsAllInfo) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

// msg_detailed_info#276d3ec6 msg_id:long answer_msg_id:long bytes:int status:int = MsgDetailedInfo;
type TLMsgDetailedInfo struct {
	MsgId       int64 `protobuf:"varint,1,opt,name=msg_id,json=msgId" json:"msg_id,omitempty"`
	AnswerMsgId int64 `protobuf:"varint,2,opt,name=answer_msg_id,json=answerMsgId" json:"answer_msg_id,omitempty"`
	Bytes       int32 `protobuf:"varint,3,opt,name=bytes" json:"bytes,omitempty"`
	Status      int32 `protobuf:"varint,4,opt,name=status" json:"status,omitempty"`
}

func (m *TLMsgDetailedInfo) Reset()                    { *m = TLMsgDetailedInfo{} }
func (m *TLMsgDetailedInfo) String() string            { return proto.CompactTextString(m) }
func (*TLMsgDetailedInfo) ProtoMessage()               {}
func (*TLMsgDetailedInfo) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{23} }

func (m *TLMsgDetailedInfo) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *TLMsgDetailedInfo) GetAnswerMsgId() int64 {
	if m != nil {
		return m.AnswerMsgId
	}
	return 0
}

func (m *TLMsgDetailedInfo) GetBytes() int32 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

func (m *TLMsgDetailedInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// msg_new_detailed_info#809db6df answer_msg_id:long bytes:int status:int = MsgDetailedInfo;
type TLMsgNewDetailedInfo struct {
	AnswerMsgId int64 `protobuf:"varint,1,opt,name=answer_msg_id,json=answerMsgId" json:"answer_msg_id,omitempty"`
	Bytes       int32 `protobuf:"varint,2,opt,name=bytes" json:"bytes,omitempty"`
	Status      int32 `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
}

func (m *TLMsgNewDetailedInfo) Reset()                    { *m = TLMsgNewDetailedInfo{} }
func (m *TLMsgNewDetailedInfo) String() string            { return proto.CompactTextString(m) }
func (*TLMsgNewDetailedInfo) ProtoMessage()               {}
func (*TLMsgNewDetailedInfo) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{24} }

func (m *TLMsgNewDetailedInfo) GetAnswerMsgId() int64 {
	if m != nil {
		return m.AnswerMsgId
	}
	return 0
}

func (m *TLMsgNewDetailedInfo) GetBytes() int32 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

func (m *TLMsgNewDetailedInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// msg_resend_req#7d861a08 msg_ids:Vector<long> = MsgResendReq;
type TLMsgResendReq struct {
	MsgIds []int64 `protobuf:"varint,1,rep,packed,name=msg_ids,json=msgIds" json:"msg_ids,omitempty"`
}

func (m *TLMsgResendReq) Reset()                    { *m = TLMsgResendReq{} }
func (m *TLMsgResendReq) String() string            { return proto.CompactTextString(m) }
func (*TLMsgResendReq) ProtoMessage()               {}
func (*TLMsgResendReq) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{25} }

func (m *TLMsgResendReq) GetMsgIds() []int64 {
	if m != nil {
		return m.MsgIds
	}
	return nil
}

// rpc_error#2144ca19 error_code:int error_message:string = RpcError;
type TLRpcError struct {
	ErrorCode    int32  `protobuf:"varint,1,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
}

func (m *TLRpcError) Reset()                    { *m = TLRpcError{} }
func (m *TLRpcError) String() string            { return proto.CompactTextString(m) }
func (*TLRpcError) ProtoMessage()               {}
func (*TLRpcError) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{26} }

func (m *TLRpcError) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *TLRpcError) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

// rpc_answer_unknown#5e2ad36e = RpcDropAnswer;
type TLRpcAnswerUnknown struct {
}

func (m *TLRpcAnswerUnknown) Reset()                    { *m = TLRpcAnswerUnknown{} }
func (m *TLRpcAnswerUnknown) String() string            { return proto.CompactTextString(m) }
func (*TLRpcAnswerUnknown) ProtoMessage()               {}
func (*TLRpcAnswerUnknown) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{27} }

// rpc_answer_dropped_running#cd78e586 = RpcDropAnswer;
type TLRpcAnswerDroppedRunning struct {
}

func (m *TLRpcAnswerDroppedRunning) Reset()                    { *m = TLRpcAnswerDroppedRunning{} }
func (m *TLRpcAnswerDroppedRunning) String() string            { return proto.CompactTextString(m) }
func (*TLRpcAnswerDroppedRunning) ProtoMessage()               {}
func (*TLRpcAnswerDroppedRunning) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{28} }

// rpc_answer_dropped#a43ad8b7 msg_id:long seq_no:int bytes:int = RpcDropAnswer;
type TLRpcAnswerDropped struct {
	MsgId int64 `protobuf:"varint,1,opt,name=msg_id,json=msgId" json:"msg_id,omitempty"`
	SeqNo int32 `protobuf:"varint,2,opt,name=seq_no,json=seqNo" json:"seq_no,omitempty"`
	Bytes int32 `protobuf:"varint,3,opt,name=bytes" json:"bytes,omitempty"`
}

func (m *TLRpcAnswerDropped) Reset()                    { *m = TLRpcAnswerDropped{} }
func (m *TLRpcAnswerDropped) String() string            { return proto.CompactTextString(m) }
func (*TLRpcAnswerDropped) ProtoMessage()               {}
func (*TLRpcAnswerDropped) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{29} }

func (m *TLRpcAnswerDropped) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *TLRpcAnswerDropped) GetSeqNo() int32 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

func (m *TLRpcAnswerDropped) GetBytes() int32 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

// future_salt#0949d9dc valid_since:int valid_until:int salt:long = FutureSalt;
type TLFutureSalt struct {
	ValidSince int32 `protobuf:"varint,1,opt,name=valid_since,json=validSince" json:"valid_since,omitempty"`
	ValidUntil int32 `protobuf:"varint,2,opt,name=valid_until,json=validUntil" json:"valid_until,omitempty"`
	Salt       int64 `protobuf:"varint,3,opt,name=salt" json:"salt,omitempty"`
}

func (m *TLFutureSalt) Reset()                    { *m = TLFutureSalt{} }
func (m *TLFutureSalt) String() string            { return proto.CompactTextString(m) }
func (*TLFutureSalt) ProtoMessage()               {}
func (*TLFutureSalt) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{30} }

func (m *TLFutureSalt) GetValidSince() int32 {
	if m != nil {
		return m.ValidSince
	}
	return 0
}

func (m *TLFutureSalt) GetValidUntil() int32 {
	if m != nil {
		return m.ValidUntil
	}
	return 0
}

func (m *TLFutureSalt) GetSalt() int64 {
	if m != nil {
		return m.Salt
	}
	return 0
}

// future_salts#ae500895 req_msg_id:long now:int salts:vector<future_salt> = FutureSalts;
type TLFutureSalts struct {
	ReqMsgId int64           `protobuf:"varint,1,opt,name=req_msg_id,json=reqMsgId" json:"req_msg_id,omitempty"`
	Now      int32           `protobuf:"varint,2,opt,name=now" json:"now,omitempty"`
	Salts    []*TLFutureSalt `protobuf:"bytes,3,rep,name=salts" json:"salts,omitempty"`
}

func (m *TLFutureSalts) Reset()                    { *m = TLFutureSalts{} }
func (m *TLFutureSalts) String() string            { return proto.CompactTextString(m) }
func (*TLFutureSalts) ProtoMessage()               {}
func (*TLFutureSalts) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{31} }

func (m *TLFutureSalts) GetReqMsgId() int64 {
	if m != nil {
		return m.ReqMsgId
	}
	return 0
}

func (m *TLFutureSalts) GetNow() int32 {
	if m != nil {
		return m.Now
	}
	return 0
}

func (m *TLFutureSalts) GetSalts() []*TLFutureSalt {
	if m != nil {
		return m.Salts
	}
	return nil
}

// pong#347773c5 msg_id:long ping_id:long = Pong;
type TLPong struct {
	MsgId  int64 `protobuf:"varint,1,opt,name=msg_id,json=msgId" json:"msg_id,omitempty"`
	PingId int64 `protobuf:"varint,2,opt,name=ping_id,json=pingId" json:"ping_id,omitempty"`
}

func (m *TLPong) Reset()                    { *m = TLPong{} }
func (m *TLPong) String() string            { return proto.CompactTextString(m) }
func (*TLPong) ProtoMessage()               {}
func (*TLPong) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{32} }

func (m *TLPong) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *TLPong) GetPingId() int64 {
	if m != nil {
		return m.PingId
	}
	return 0
}

// destroy_session_ok#e22045fc session_id:long = DestroySessionRes;
type TLDestroySessionOk struct {
	SessionId int64 `protobuf:"varint,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
}

func (m *TLDestroySessionOk) Reset()                    { *m = TLDestroySessionOk{} }
func (m *TLDestroySessionOk) String() string            { return proto.CompactTextString(m) }
func (*TLDestroySessionOk) ProtoMessage()               {}
func (*TLDestroySessionOk) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{33} }

func (m *TLDestroySessionOk) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

// destroy_session_none#62d350c9 session_id:long = DestroySessionRes;
type TLDestroySessionNone struct {
	SessionId int64 `protobuf:"varint,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
}

func (m *TLDestroySessionNone) Reset()                    { *m = TLDestroySessionNone{} }
func (m *TLDestroySessionNone) String() string            { return proto.CompactTextString(m) }
func (*TLDestroySessionNone) ProtoMessage()               {}
func (*TLDestroySessionNone) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{34} }

func (m *TLDestroySessionNone) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

// new_session_created#9ec20908 first_msg_id:long unique_id:long server_salt:long = NewSession;
type TLNewSessionCreated struct {
	FirstMsgId int64 `protobuf:"varint,1,opt,name=first_msg_id,json=firstMsgId" json:"first_msg_id,omitempty"`
	UniqueId   int64 `protobuf:"varint,2,opt,name=unique_id,json=uniqueId" json:"unique_id,omitempty"`
	ServerSalt int64 `protobuf:"varint,3,opt,name=server_salt,json=serverSalt" json:"server_salt,omitempty"`
}

func (m *TLNewSessionCreated) Reset()                    { *m = TLNewSessionCreated{} }
func (m *TLNewSessionCreated) String() string            { return proto.CompactTextString(m) }
func (*TLNewSessionCreated) ProtoMessage()               {}
func (*TLNewSessionCreated) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{35} }

func (m *TLNewSessionCreated) GetFirstMsgId() int64 {
	if m != nil {
		return m.FirstMsgId
	}
	return 0
}

func (m *TLNewSessionCreated) GetUniqueId() int64 {
	if m != nil {
		return m.UniqueId
	}
	return 0
}

func (m *TLNewSessionCreated) GetServerSalt() int64 {
	if m != nil {
		return m.ServerSalt
	}
	return 0
}

// http_wait#9299359f max_delay:int wait_after:int max_wait:int = HttpWait;
type TLHttpWait struct {
	MaxDelay  int32 `protobuf:"varint,1,opt,name=max_delay,json=maxDelay" json:"max_delay,omitempty"`
	WaitAfter int32 `protobuf:"varint,2,opt,name=wait_after,json=waitAfter" json:"wait_after,omitempty"`
	MaxWait   int32 `protobuf:"varint,3,opt,name=max_wait,json=maxWait" json:"max_wait,omitempty"`
}

func (m *TLHttpWait) Reset()                    { *m = TLHttpWait{} }
func (m *TLHttpWait) String() string            { return proto.CompactTextString(m) }
func (*TLHttpWait) ProtoMessage()               {}
func (*TLHttpWait) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{36} }

func (m *TLHttpWait) GetMaxDelay() int32 {
	if m != nil {
		return m.MaxDelay
	}
	return 0
}

func (m *TLHttpWait) GetWaitAfter() int32 {
	if m != nil {
		return m.WaitAfter
	}
	return 0
}

func (m *TLHttpWait) GetMaxWait() int32 {
	if m != nil {
		return m.MaxWait
	}
	return 0
}

// ipPort#d433ad73 ipv4:int port:int = IpPort;
type TLIpPort struct {
	Ipv4 int32 `protobuf:"varint,1,opt,name=ipv4" json:"ipv4,omitempty"`
	Port int32 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *TLIpPort) Reset()                    { *m = TLIpPort{} }
func (m *TLIpPort) String() string            { return proto.CompactTextString(m) }
func (*TLIpPort) ProtoMessage()               {}
func (*TLIpPort) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{37} }

func (m *TLIpPort) GetIpv4() int32 {
	if m != nil {
		return m.Ipv4
	}
	return 0
}

func (m *TLIpPort) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

// help.configSimple#d997c3c5 date:int expires:int dc_id:int ip_port_list:Vector<ipPort> = help.ConfigSimple;
type TLHelpConfigSimple struct {
	Date       int32       `protobuf:"varint,1,opt,name=date" json:"date,omitempty"`
	Expires    int32       `protobuf:"varint,2,opt,name=expires" json:"expires,omitempty"`
	DcId       int32       `protobuf:"varint,3,opt,name=dc_id,json=dcId" json:"dc_id,omitempty"`
	IpPortList []*TLIpPort `protobuf:"bytes,4,rep,name=ip_port_list,json=ipPortList" json:"ip_port_list,omitempty"`
}

func (m *TLHelpConfigSimple) Reset()                    { *m = TLHelpConfigSimple{} }
func (m *TLHelpConfigSimple) String() string            { return proto.CompactTextString(m) }
func (*TLHelpConfigSimple) ProtoMessage()               {}
func (*TLHelpConfigSimple) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{38} }

func (m *TLHelpConfigSimple) GetDate() int32 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *TLHelpConfigSimple) GetExpires() int32 {
	if m != nil {
		return m.Expires
	}
	return 0
}

func (m *TLHelpConfigSimple) GetDcId() int32 {
	if m != nil {
		return m.DcId
	}
	return 0
}

func (m *TLHelpConfigSimple) GetIpPortList() []*TLIpPort {
	if m != nil {
		return m.IpPortList
	}
	return nil
}

// RPC
// rpc_drop_answer#58e4a740 req_msg_id:long = RpcDropAnswer;
type TLRpcDropAnswer struct {
	ReqMsgId int64 `protobuf:"varint,1,opt,name=req_msg_id,json=reqMsgId" json:"req_msg_id,omitempty"`
}

func (m *TLRpcDropAnswer) Reset()                    { *m = TLRpcDropAnswer{} }
func (m *TLRpcDropAnswer) String() string            { return proto.CompactTextString(m) }
func (*TLRpcDropAnswer) ProtoMessage()               {}
func (*TLRpcDropAnswer) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{39} }

func (m *TLRpcDropAnswer) GetReqMsgId() int64 {
	if m != nil {
		return m.ReqMsgId
	}
	return 0
}

// get_future_salts#b921bd04 num:int = FutureSalts;
type TLGetFutureSalts struct {
	Num int32 `protobuf:"varint,1,opt,name=num" json:"num,omitempty"`
}

func (m *TLGetFutureSalts) Reset()                    { *m = TLGetFutureSalts{} }
func (m *TLGetFutureSalts) String() string            { return proto.CompactTextString(m) }
func (*TLGetFutureSalts) ProtoMessage()               {}
func (*TLGetFutureSalts) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{40} }

func (m *TLGetFutureSalts) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

// ping#7abe77ec ping_id:long = Pong;
type TLPing struct {
	PingId int64 `protobuf:"varint,1,opt,name=ping_id,json=pingId" json:"ping_id,omitempty"`
}

func (m *TLPing) Reset()                    { *m = TLPing{} }
func (m *TLPing) String() string            { return proto.CompactTextString(m) }
func (*TLPing) ProtoMessage()               {}
func (*TLPing) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{41} }

func (m *TLPing) GetPingId() int64 {
	if m != nil {
		return m.PingId
	}
	return 0
}

// ping_delay_disconnect#f3427b8c ping_id:long disconnect_delay:int = Pong;
type TLPingDelayDisconnect struct {
	PingId          int64 `protobuf:"varint,1,opt,name=ping_id,json=pingId" json:"ping_id,omitempty"`
	DisconnectDelay int32 `protobuf:"varint,2,opt,name=disconnect_delay,json=disconnectDelay" json:"disconnect_delay,omitempty"`
}

func (m *TLPingDelayDisconnect) Reset()                    { *m = TLPingDelayDisconnect{} }
func (m *TLPingDelayDisconnect) String() string            { return proto.CompactTextString(m) }
func (*TLPingDelayDisconnect) ProtoMessage()               {}
func (*TLPingDelayDisconnect) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{42} }

func (m *TLPingDelayDisconnect) GetPingId() int64 {
	if m != nil {
		return m.PingId
	}
	return 0
}

func (m *TLPingDelayDisconnect) GetDisconnectDelay() int32 {
	if m != nil {
		return m.DisconnectDelay
	}
	return 0
}

// destroy_session#e7512126 session_id:long = DestroySessionRes;
type TLDestroySession struct {
	SessionId int64 `protobuf:"varint,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
}

func (m *TLDestroySession) Reset()                    { *m = TLDestroySession{} }
func (m *TLDestroySession) String() string            { return proto.CompactTextString(m) }
func (*TLDestroySession) ProtoMessage()               {}
func (*TLDestroySession) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{43} }

func (m *TLDestroySession) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

// contest.saveDeveloperInfo#9a5f6e95 vk_id:int name:string phone_number:string age:int city:string = Bool;
type TLContestSaveDeveloperInfo struct {
	VkId        int32  `protobuf:"varint,1,opt,name=vk_id,json=vkId" json:"vk_id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	PhoneNumber string `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
	Age         int32  `protobuf:"varint,4,opt,name=age" json:"age,omitempty"`
	City        string `protobuf:"bytes,5,opt,name=city" json:"city,omitempty"`
}

func (m *TLContestSaveDeveloperInfo) Reset()                    { *m = TLContestSaveDeveloperInfo{} }
func (m *TLContestSaveDeveloperInfo) String() string            { return proto.CompactTextString(m) }
func (*TLContestSaveDeveloperInfo) ProtoMessage()               {}
func (*TLContestSaveDeveloperInfo) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{44} }

func (m *TLContestSaveDeveloperInfo) GetVkId() int32 {
	if m != nil {
		return m.VkId
	}
	return 0
}

func (m *TLContestSaveDeveloperInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TLContestSaveDeveloperInfo) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *TLContestSaveDeveloperInfo) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *TLContestSaveDeveloperInfo) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgsAck)(nil), "mtproto.MsgsAck")
	proto.RegisterType((*BadMsgNotification)(nil), "mtproto.BadMsgNotification")
	proto.RegisterType((*MsgsStateReq)(nil), "mtproto.MsgsStateReq")
	proto.RegisterType((*MsgsStateInfo)(nil), "mtproto.MsgsStateInfo")
	proto.RegisterType((*MsgsAllInfo)(nil), "mtproto.MsgsAllInfo")
	proto.RegisterType((*MsgDetailedInfo)(nil), "mtproto.MsgDetailedInfo")
	proto.RegisterType((*MsgResendReq)(nil), "mtproto.MsgResendReq")
	proto.RegisterType((*RpcError)(nil), "mtproto.RpcError")
	proto.RegisterType((*RpcDropAnswer)(nil), "mtproto.RpcDropAnswer")
	proto.RegisterType((*FutureSalt)(nil), "mtproto.FutureSalt")
	proto.RegisterType((*FutureSalts)(nil), "mtproto.FutureSalts")
	proto.RegisterType((*Pong)(nil), "mtproto.Pong")
	proto.RegisterType((*DestroySessionRes)(nil), "mtproto.DestroySessionRes")
	proto.RegisterType((*NewSession)(nil), "mtproto.NewSession")
	proto.RegisterType((*HttpWait)(nil), "mtproto.HttpWait")
	proto.RegisterType((*IpPort)(nil), "mtproto.IpPort")
	proto.RegisterType((*Help_ConfigSimple)(nil), "mtproto.help_ConfigSimple")
	proto.RegisterType((*TLMsgsAck)(nil), "mtproto.TL_msgs_ack")
	proto.RegisterType((*TLBadMsgNotification)(nil), "mtproto.TL_bad_msg_notification")
	proto.RegisterType((*TLBadServerSalt)(nil), "mtproto.TL_bad_server_salt")
	proto.RegisterType((*TLMsgsStateReq)(nil), "mtproto.TL_msgs_state_req")
	proto.RegisterType((*TLMsgsStateInfo)(nil), "mtproto.TL_msgs_state_info")
	proto.RegisterType((*TLMsgsAllInfo)(nil), "mtproto.TL_msgs_all_info")
	proto.RegisterType((*TLMsgDetailedInfo)(nil), "mtproto.TL_msg_detailed_info")
	proto.RegisterType((*TLMsgNewDetailedInfo)(nil), "mtproto.TL_msg_new_detailed_info")
	proto.RegisterType((*TLMsgResendReq)(nil), "mtproto.TL_msg_resend_req")
	proto.RegisterType((*TLRpcError)(nil), "mtproto.TL_rpc_error")
	proto.RegisterType((*TLRpcAnswerUnknown)(nil), "mtproto.TL_rpc_answer_unknown")
	proto.RegisterType((*TLRpcAnswerDroppedRunning)(nil), "mtproto.TL_rpc_answer_dropped_running")
	proto.RegisterType((*TLRpcAnswerDropped)(nil), "mtproto.TL_rpc_answer_dropped")
	proto.RegisterType((*TLFutureSalt)(nil), "mtproto.TL_future_salt")
	proto.RegisterType((*TLFutureSalts)(nil), "mtproto.TL_future_salts")
	proto.RegisterType((*TLPong)(nil), "mtproto.TL_pong")
	proto.RegisterType((*TLDestroySessionOk)(nil), "mtproto.TL_destroy_session_ok")
	proto.RegisterType((*TLDestroySessionNone)(nil), "mtproto.TL_destroy_session_none")
	proto.RegisterType((*TLNewSessionCreated)(nil), "mtproto.TL_new_session_created")
	proto.RegisterType((*TLHttpWait)(nil), "mtproto.TL_http_wait")
	proto.RegisterType((*TLIpPort)(nil), "mtproto.TL_ipPort")
	proto.RegisterType((*TLHelpConfigSimple)(nil), "mtproto.TL_help_configSimple")
	proto.RegisterType((*TLRpcDropAnswer)(nil), "mtproto.TL_rpc_drop_answer")
	proto.RegisterType((*TLGetFutureSalts)(nil), "mtproto.TL_get_future_salts")
	proto.RegisterType((*TLPing)(nil), "mtproto.TL_ping")
	proto.RegisterType((*TLPingDelayDisconnect)(nil), "mtproto.TL_ping_delay_disconnect")
	proto.RegisterType((*TLDestroySession)(nil), "mtproto.TL_destroy_session")
	proto.RegisterType((*TLContestSaveDeveloperInfo)(nil), "mtproto.TL_contest_saveDeveloperInfo")
}

func init() { proto.RegisterFile("schema.tl.transport.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 1562 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xb6, 0xe3, 0xd8, 0x8e, 0x8f, 0x9d, 0x26, 0x99, 0x24, 0x4d, 0xda, 0xb4, 0x34, 0x5d, 0xa4,
	0x50, 0xa4, 0x12, 0x89, 0xb6, 0x42, 0x14, 0x09, 0x55, 0x49, 0xd3, 0x62, 0xab, 0x49, 0x28, 0xe3,
	0x94, 0x0a, 0x21, 0x58, 0x6d, 0x76, 0xc7, 0xce, 0x92, 0xdd, 0xd9, 0xf5, 0xce, 0x38, 0x3f, 0xdc,
	0xf0, 0x08, 0xf0, 0x02, 0x5c, 0xf0, 0x1e, 0xdc, 0x20, 0xf1, 0x60, 0xe8, 0xcc, 0x8c, 0xed, 0xf1,
	0xda, 0x4e, 0xaf, 0xb8, 0xca, 0xec, 0x37, 0x67, 0xbe, 0x33, 0xe7, 0x67, 0xce, 0xe7, 0xc0, 0x1d,
	0xe1, 0x9f, 0xb1, 0xd8, 0xdb, 0x95, 0xd1, 0xae, 0xcc, 0x3c, 0x2e, 0xd2, 0x24, 0x93, 0xbb, 0x69,
	0x96, 0xc8, 0x84, 0x54, 0x63, 0xa9, 0x16, 0xce, 0x37, 0x50, 0x3d, 0x12, 0x5d, 0xb1, 0xe7, 0x9f,
	0x93, 0xcf, 0x61, 0x21, 0x16, 0x5d, 0xe1, 0x7a, 0xfe, 0xf9, 0x66, 0x71, 0xbb, 0xf8, 0xa8, 0xfe,
	0x64, 0x6d, 0xd7, 0x98, 0xed, 0x9e, 0x1c, 0xba, 0x83, 0xbd, 0x66, 0x81, 0x56, 0x63, 0x7d, 0x64,
	0xbf, 0x06, 0xd5, 0xd4, 0xbb, 0x8e, 0x12, 0x2f, 0x70, 0xfe, 0x2e, 0x02, 0xd9, 0xf7, 0x82, 0x23,
	0xd1, 0x3d, 0x4e, 0x64, 0xd8, 0x09, 0x7d, 0x4f, 0x86, 0x09, 0x27, 0x27, 0xb0, 0x76, 0xea, 0x05,
	0x78, 0xd8, 0xe5, 0x16, 0x6e, 0x1c, 0x6c, 0xdb, 0x0e, 0xa6, 0xd9, 0x35, 0x0b, 0x94, 0x9c, 0x4e,
	0xb2, 0xbe, 0x82, 0x25, 0xb4, 0x16, 0x2c, 0xbb, 0x60, 0x99, 0x2b, 0xbc, 0x48, 0x6e, 0xce, 0x29,
	0xc2, 0xad, 0x3c, 0xa1, 0x65, 0xd2, 0x2c, 0xd0, 0xc5, 0x53, 0x2f, 0x68, 0x2b, 0xa4, 0xed, 0x45,
	0xd2, 0xbe, 0xfe, 0x4f, 0xd0, 0xc0, 0x3c, 0xb4, 0xa5, 0x27, 0x19, 0x65, 0x3d, 0xb2, 0x0f, 0xb7,
	0x54, 0xc0, 0x02, 0x01, 0x37, 0x63, 0x3d, 0x73, 0xe3, 0xbb, 0x13, 0x29, 0x19, 0x5a, 0x34, 0x0b,
	0xb4, 0x11, 0x5b, 0x1c, 0x36, 0xbd, 0x07, 0x8b, 0x43, 0xfa, 0x16, 0xef, 0x24, 0x18, 0x81, 0x75,
	0x3a, 0xe4, 0x9d, 0xc4, 0x38, 0xd8, 0x9a, 0xe1, 0x00, 0x4d, 0x30, 0x82, 0xd8, 0xa6, 0xb1, 0x5d,
	0xfc, 0x00, 0x75, 0x55, 0xc9, 0x28, 0x52, 0x0e, 0x5e, 0xc0, 0xa2, 0xae, 0x58, 0x14, 0xd9, 0xf4,
	0x77, 0x26, 0x4b, 0x6a, 0x0c, 0x9a, 0x05, 0x5a, 0x8f, 0x47, 0x04, 0x36, 0xf5, 0x3f, 0x45, 0x58,
	0x3a, 0x12, 0xdd, 0x03, 0x26, 0xbd, 0x30, 0x62, 0x81, 0xe2, 0x7f, 0x03, 0x2b, 0x58, 0xac, 0xc0,
	0x60, 0xb6, 0x8f, 0xfb, 0x39, 0x1f, 0xe3, 0x46, 0xcd, 0x02, 0xc5, 0xd0, 0xc7, 0xc8, 0xbe, 0x87,
	0x75, 0x55, 0x79, 0x76, 0x99, 0x23, 0xd4, 0x55, 0x7d, 0x98, 0x27, 0x9c, 0x30, 0xc4, 0x3e, 0x89,
	0x45, 0xf7, 0x98, 0x5d, 0xda, 0xbc, 0x93, 0x05, 0xa6, 0x4c, 0x30, 0x1e, 0x8c, 0x0a, 0xec, 0x66,
	0x0a, 0xb8, 0xa1, 0xc0, 0x96, 0x85, 0x29, 0xf0, 0x90, 0xc3, 0xa6, 0x7f, 0x03, 0x0b, 0x34, 0xf5,
	0x5f, 0x65, 0x59, 0x92, 0x91, 0x67, 0x50, 0xcb, 0x52, 0xdf, 0x65, 0xf8, 0x61, 0x58, 0xd7, 0x6d,
	0xd6, 0xe1, 0x66, 0xb3, 0x40, 0x17, 0x32, 0x73, 0xca, 0x26, 0xfb, 0x6b, 0x0e, 0x16, 0x69, 0xea,
	0x1f, 0x64, 0x49, 0xba, 0xc7, 0xc5, 0x25, 0xcb, 0xc8, 0x31, 0x10, 0x3c, 0xe5, 0xa9, 0x2f, 0xb7,
	0xcf, 0xcf, 0x79, 0x72, 0x39, 0x78, 0x44, 0x1f, 0xe5, 0xb9, 0xc7, 0xad, 0x9a, 0x05, 0xba, 0x9c,
	0xa5, 0xbe, 0x26, 0x7a, 0xa7, 0x31, 0xc2, 0xe0, 0xae, 0x65, 0x19, 0x64, 0x49, 0x9a, 0xb2, 0xc0,
	0xcd, 0xfa, 0x9c, 0x87, 0xbc, 0x6b, 0xb2, 0xbe, 0x33, 0x83, 0x37, 0x67, 0xdd, 0x2c, 0xd0, 0x8d,
	0x21, 0xff, 0x81, 0xde, 0xa3, 0x7a, 0x2b, 0x77, 0x6d, 0x73, 0x70, 0xb3, 0x74, 0xe3, 0xb5, 0x8d,
	0xd5, 0xd8, 0xb5, 0x0d, 0xad, 0x9d, 0xa3, 0x36, 0xc0, 0xeb, 0xbe, 0xec, 0x67, 0x0c, 0x5f, 0x32,
	0xf9, 0x0a, 0xea, 0x1d, 0xf5, 0xa5, 0x87, 0x81, 0x4e, 0xcc, 0x86, 0xed, 0xc1, 0xda, 0x6e, 0x16,
	0x28, 0x74, 0x86, 0x67, 0x6d, 0xd2, 0xf7, 0x50, 0x1f, 0x91, 0x0a, 0xf2, 0x35, 0x34, 0xac, 0x63,
	0xc2, 0xd0, 0x6e, 0xce, 0xa0, 0x15, 0xf8, 0x82, 0x46, 0xbc, 0xc2, 0x26, 0x7e, 0x0e, 0xf3, 0x6f,
	0x13, 0xde, 0x25, 0x3b, 0x30, 0x9f, 0x26, 0xbc, 0x6b, 0x98, 0x96, 0x6d, 0x26, 0xc4, 0x9b, 0x05,
	0xaa, 0xf6, 0xed, 0xa3, 0xff, 0x16, 0x61, 0xe5, 0x80, 0x09, 0x99, 0x25, 0xd7, 0x6d, 0x26, 0x44,
	0x98, 0x70, 0xca, 0x04, 0x66, 0x36, 0xd0, 0xa0, 0x2b, 0x34, 0xea, 0x26, 0xe7, 0xd3, 0x1a, 0x62,
	0xd2, 0x0a, 0x33, 0x1b, 0x8c, 0x11, 0x7e, 0x7b, 0x8e, 0x73, 0x3a, 0x6f, 0xc9, 0x13, 0xce, 0x4c,
	0x2b, 0x6c, 0xdf, 0xc4, 0x88, 0x76, 0xf8, 0xfe, 0xc6, 0x39, 0x8f, 0x13, 0xce, 0xec, 0x30, 0x7e,
	0x01, 0x38, 0x66, 0x97, 0x66, 0x93, 0x7c, 0x07, 0xab, 0xf8, 0x86, 0x07, 0x14, 0x7e, 0xc6, 0x3c,
	0xc9, 0x02, 0x73, 0xff, 0x07, 0xb6, 0xb7, 0x29, 0x66, 0xcd, 0x02, 0x5d, 0xe1, 0x43, 0xae, 0x97,
	0x1a, 0xcc, 0x3d, 0xc6, 0xa6, 0x94, 0xe9, 0x7b, 0x2f, 0x94, 0xf8, 0x18, 0xcf, 0xa4, 0x4c, 0xdd,
	0x4b, 0x2f, 0x94, 0xd3, 0x1e, 0xe3, 0x70, 0x13, 0x1f, 0xe3, 0x99, 0x39, 0x65, 0x93, 0xed, 0x41,
	0xa5, 0x95, 0xbe, 0x4d, 0x32, 0x49, 0x1e, 0x43, 0x25, 0x54, 0x2b, 0xc3, 0x43, 0x6c, 0x1e, 0xbd,
	0xd3, 0x2c, 0x50, 0x63, 0x63, 0x53, 0x44, 0xb0, 0x72, 0xc6, 0xa2, 0xd4, 0x7d, 0x99, 0xf0, 0x4e,
	0xd8, 0x6d, 0x87, 0x71, 0x1a, 0x31, 0x72, 0x68, 0x40, 0xdf, 0x02, 0xa7, 0x0d, 0xd0, 0x09, 0x23,
	0xac, 0x1f, 0x82, 0x36, 0x9b, 0xed, 0x6d, 0x07, 0xea, 0x96, 0x5c, 0x93, 0x0d, 0x40, 0xb9, 0x76,
	0xc3, 0x00, 0xfb, 0xb7, 0xf4, 0xa8, 0x44, 0x2b, 0xb1, 0xe8, 0xb6, 0x02, 0xe1, 0xfc, 0x0a, 0x1b,
	0x33, 0x54, 0x97, 0xdc, 0x03, 0x18, 0xe0, 0xa1, 0xae, 0x4a, 0x89, 0x2e, 0x68, 0x1d, 0x6e, 0x05,
	0xc4, 0x81, 0xc5, 0xc1, 0xae, 0x60, 0x3d, 0xae, 0xa7, 0x74, 0x99, 0xd6, 0xb5, 0x41, 0x1b, 0x21,
	0x72, 0x1f, 0x40, 0x8d, 0x38, 0xd7, 0x4f, 0x02, 0xa6, 0x5e, 0x7c, 0x99, 0xd6, 0x14, 0xf2, 0x32,
	0x09, 0x98, 0xf3, 0x67, 0x11, 0xc8, 0xa4, 0x42, 0xff, 0xef, 0x7e, 0xc9, 0x0e, 0x2c, 0xe9, 0x86,
	0x1a, 0xfd, 0x70, 0x98, 0x57, 0x5e, 0x16, 0x55, 0x43, 0x0d, 0x7e, 0x19, 0x38, 0x8f, 0x61, 0x65,
	0x42, 0xdf, 0x67, 0x67, 0xf2, 0xb5, 0x0a, 0x26, 0x27, 0xd6, 0x18, 0x4c, 0xc6, 0x7a, 0xb9, 0x60,
	0x32, 0xd6, 0xd3, 0xc1, 0x10, 0x98, 0x1f, 0x2a, 0x5c, 0x8d, 0xaa, 0xb5, 0xf3, 0x02, 0x96, 0xf3,
	0xaa, 0x3c, 0xd3, 0xe9, 0x54, 0x82, 0xdf, 0x60, 0x6d, 0x9a, 0xe4, 0x92, 0x75, 0xa8, 0x8c, 0x5d,
	0xa3, 0x1c, 0x0f, 0x12, 0x6a, 0x86, 0xae, 0xd9, 0x9d, 0x53, 0xbb, 0x75, 0x0d, 0xea, 0x7b, 0xae,
	0x41, 0xf9, 0xf4, 0x5a, 0x32, 0x61, 0x72, 0xa9, 0x3f, 0xc8, 0x6d, 0xa8, 0x60, 0xa4, 0x7d, 0xa1,
	0xd2, 0x57, 0xa6, 0xe6, 0xcb, 0x89, 0x60, 0x73, 0x96, 0x44, 0x4f, 0x7a, 0x2b, 0xde, 0xe0, 0x6d,
	0x6e, 0xba, 0xb7, 0xd2, 0x98, 0xb7, 0x61, 0x95, 0x2c, 0x91, 0x9e, 0x5d, 0x25, 0x0a, 0x0d, 0x5b,
	0x7c, 0x73, 0xad, 0x52, 0xcc, 0xb7, 0xca, 0xc7, 0xb0, 0xa8, 0xb7, 0x63, 0x26, 0x84, 0xd7, 0x65,
	0x26, 0xd1, 0x0d, 0x05, 0x1e, 0x69, 0xcc, 0xd9, 0x80, 0xf5, 0xa9, 0xa2, 0xeb, 0x3c, 0x80, 0xfb,
	0x37, 0xaa, 0xa6, 0xf3, 0x63, 0xfe, 0xa4, 0x31, 0x98, 0x55, 0xab, 0x75, 0xa8, 0x08, 0xd6, 0x73,
	0x87, 0x5d, 0x5f, 0x16, 0xac, 0x77, 0x9c, 0x4c, 0x2f, 0x8f, 0xd3, 0x81, 0x5b, 0xe3, 0xda, 0x44,
	0x1e, 0x40, 0xfd, 0xc2, 0x8b, 0xc2, 0xc0, 0x15, 0x21, 0xf7, 0x07, 0xd1, 0x82, 0x82, 0xda, 0x88,
	0x8c, 0x0c, 0xfa, 0x5c, 0x86, 0x91, 0x71, 0xa2, 0x0d, 0xde, 0x21, 0x82, 0xfd, 0xa6, 0xde, 0x4b,
	0x49, 0xdd, 0x4a, 0xad, 0x9d, 0x14, 0x96, 0x72, 0x1a, 0xf8, 0x81, 0xae, 0x5f, 0x86, 0x12, 0x4f,
	0x2e, 0x0d, 0x3b, 0x2e, 0xc9, 0x67, 0x50, 0xd6, 0xe2, 0x5a, 0xda, 0x2e, 0xdd, 0xa0, 0xd9, 0x54,
	0x5b, 0x39, 0xcf, 0xa1, 0x6a, 0xb4, 0x72, 0x56, 0xa2, 0x36, 0xa0, 0x9a, 0x86, 0xdc, 0x6a, 0xe7,
	0x0a, 0x7e, 0xb6, 0x02, 0xe7, 0x0b, 0x95, 0xf1, 0x49, 0x3d, 0xc4, 0x46, 0x18, 0x7c, 0x0d, 0xc9,
	0x6a, 0x06, 0x69, 0x05, 0xce, 0x97, 0x6a, 0x4e, 0x4e, 0x53, 0xbd, 0x0f, 0x9d, 0xbc, 0x82, 0xdb,
	0xd3, 0x15, 0x8c, 0x6c, 0x43, 0xa3, 0x13, 0x66, 0x42, 0x8e, 0xe7, 0x09, 0x14, 0xa6, 0x33, 0xb5,
	0x05, 0xb5, 0x3e, 0x0f, 0x7b, 0x7d, 0x36, 0x0a, 0x64, 0x41, 0x03, 0xad, 0x00, 0x8b, 0x65, 0x8f,
	0x30, 0x5d, 0x12, 0x10, 0xa3, 0xf9, 0xc5, 0x54, 0xaf, 0x0f, 0xb5, 0x0d, 0xd9, 0x62, 0xef, 0xca,
	0x0d, 0x58, 0xe4, 0x5d, 0x9b, 0xe2, 0x2f, 0xc4, 0xde, 0xd5, 0x01, 0x7e, 0x63, 0x14, 0x68, 0xe4,
	0x7a, 0x1d, 0xc9, 0x32, 0x53, 0x9b, 0x1a, 0x22, 0x7b, 0x08, 0x90, 0x3b, 0x80, 0xa6, 0x5a, 0x40,
	0x75, 0x97, 0x55, 0x63, 0xef, 0x0a, 0x65, 0xd2, 0x79, 0x0a, 0xb5, 0xa1, 0xf4, 0xa9, 0x81, 0x94,
	0x5e, 0x3c, 0x33, 0xf4, 0x6a, 0x8d, 0x18, 0xfe, 0xd7, 0x69, 0x48, 0xd5, 0xda, 0xf9, 0xbd, 0xa8,
	0xa6, 0xd4, 0x84, 0xae, 0xa1, 0x71, 0xe0, 0xc9, 0x41, 0x73, 0xaa, 0x35, 0xd9, 0x84, 0x2a, 0xbb,
	0x4a, 0xc3, 0x6c, 0x38, 0x12, 0x06, 0x9f, 0x64, 0x15, 0xca, 0x81, 0x8f, 0xc9, 0x29, 0x19, 0x73,
	0xbf, 0x15, 0x90, 0x67, 0xd0, 0x08, 0x53, 0x17, 0xdd, 0xb8, 0x51, 0x28, 0x70, 0xb8, 0x97, 0xa6,
	0x0b, 0x35, 0x05, 0xfd, 0xf7, 0x30, 0x14, 0xd2, 0x79, 0xa2, 0xe6, 0x37, 0xbe, 0x45, 0x7c, 0x84,
	0xe6, 0x41, 0xde, 0xdc, 0xc9, 0xce, 0x27, 0xb0, 0x7a, 0x72, 0xe8, 0x76, 0x99, 0x1c, 0x6f, 0x7f,
	0x6c, 0xf0, 0x7e, 0x6c, 0x42, 0xc0, 0xa5, 0xe3, 0xe8, 0x8e, 0xc5, 0x9f, 0xc3, 0x56, 0x6b, 0x16,
	0xc7, 0x5a, 0xf3, 0x67, 0x35, 0x36, 0xd5, 0x9e, 0x2a, 0x91, 0x1b, 0x84, 0xc2, 0x4f, 0x38, 0x67,
	0xbe, 0x9c, 0x79, 0x88, 0x7c, 0x0a, 0xcb, 0x23, 0x33, 0x53, 0x5a, 0x9d, 0xa3, 0xa5, 0x11, 0xae,
	0x2a, 0xec, 0x3c, 0x55, 0x01, 0xe6, 0x5a, 0xf8, 0x43, 0xdd, 0xfb, 0x47, 0x11, 0xee, 0x9d, 0x1c,
	0x62, 0x89, 0x24, 0x13, 0xd2, 0x15, 0xde, 0x05, 0x3b, 0x60, 0x17, 0x2c, 0x4a, 0x52, 0x96, 0xa9,
	0xff, 0xda, 0x56, 0xa1, 0x7c, 0x71, 0x3e, 0x38, 0x5a, 0xa6, 0xf3, 0x17, 0xe7, 0x5a, 0xd7, 0xb8,
	0x17, 0x0f, 0xa6, 0xa5, 0x5a, 0x93, 0x87, 0xd0, 0x48, 0xcf, 0x12, 0xce, 0x5c, 0xde, 0x8f, 0x4f,
	0x59, 0xa6, 0x2a, 0x56, 0xa3, 0x75, 0x85, 0x1d, 0x2b, 0x08, 0xf3, 0x86, 0x33, 0x56, 0xab, 0x09,
	0x2e, 0x91, 0xc8, 0x0f, 0xe5, 0xf5, 0x66, 0x59, 0x13, 0xe1, 0x7a, 0xff, 0x11, 0x6c, 0xf9, 0x49,
	0xbc, 0xcb, 0xd9, 0x69, 0x3f, 0xf2, 0xc2, 0x78, 0x97, 0xf1, 0x6e, 0xc8, 0xd9, 0xa0, 0xba, 0xfb,
	0xd5, 0xa3, 0x93, 0xb7, 0xb8, 0x68, 0xce, 0x9d, 0x56, 0x14, 0xf2, 0xf4, 0xbf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x22, 0xfc, 0x0e, 0x2e, 0x04, 0x11, 0x00, 0x00,
}
