// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.tl.core_types.proto

package mtproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// /////////////////////////////////////////////////////////////////////////////
// Error <--
//  + TL_error
//
type Error_Data struct {
	Code int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Text string `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
}

func (m *Error_Data) Reset()                    { *m = Error_Data{} }
func (m *Error_Data) String() string            { return proto.CompactTextString(m) }
func (*Error_Data) ProtoMessage()               {}
func (*Error_Data) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Error_Data) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error_Data) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Error struct {
	Constructor TLConstructor `protobuf:"varint,1,opt,name=constructor,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2       *Error_Data   `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Error) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *Error) GetData2() *Error_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// error#c4b9f9bb code:int text:string = Error;
type TLError struct {
	Data2 *Error_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLError) Reset()                    { *m = TLError{} }
func (m *TLError) String() string            { return proto.CompactTextString(m) }
func (*TLError) ProtoMessage()               {}
func (*TLError) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *TLError) GetData2() *Error_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// Null <--
//  + TL_null
//
type Null_Data struct {
}

func (m *Null_Data) Reset()                    { *m = Null_Data{} }
func (m *Null_Data) String() string            { return proto.CompactTextString(m) }
func (*Null_Data) ProtoMessage()               {}
func (*Null_Data) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

type Null struct {
	Constructor TLConstructor `protobuf:"varint,1,opt,name=constructor,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2       *Null_Data    `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *Null) Reset()                    { *m = Null{} }
func (m *Null) String() string            { return proto.CompactTextString(m) }
func (*Null) ProtoMessage()               {}
func (*Null) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *Null) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *Null) GetData2() *Null_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// null#56730bcc = Null;
type TLNull struct {
	Data2 *Null_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLNull) Reset()                    { *m = TLNull{} }
func (m *TLNull) String() string            { return proto.CompactTextString(m) }
func (*TLNull) ProtoMessage()               {}
func (*TLNull) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *TLNull) GetData2() *Null_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// Bool <--
//  + TL_boolFalse
//  + TL_boolTrue
//
type Bool_Data struct {
}

func (m *Bool_Data) Reset()                    { *m = Bool_Data{} }
func (m *Bool_Data) String() string            { return proto.CompactTextString(m) }
func (*Bool_Data) ProtoMessage()               {}
func (*Bool_Data) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

type Bool struct {
	Constructor TLConstructor `protobuf:"varint,1,opt,name=constructor,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2       *Bool_Data    `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *Bool) Reset()                    { *m = Bool{} }
func (m *Bool) String() string            { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()               {}
func (*Bool) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *Bool) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *Bool) GetData2() *Bool_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// boolFalse#bc799737 = Bool;
type TLBoolFalse struct {
	Data2 *Bool_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLBoolFalse) Reset()                    { *m = TLBoolFalse{} }
func (m *TLBoolFalse) String() string            { return proto.CompactTextString(m) }
func (*TLBoolFalse) ProtoMessage()               {}
func (*TLBoolFalse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *TLBoolFalse) GetData2() *Bool_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// boolTrue#997275b5 = Bool;
type TLBoolTrue struct {
	Data2 *Bool_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLBoolTrue) Reset()                    { *m = TLBoolTrue{} }
func (m *TLBoolTrue) String() string            { return proto.CompactTextString(m) }
func (*TLBoolTrue) ProtoMessage()               {}
func (*TLBoolTrue) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *TLBoolTrue) GetData2() *Bool_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// True <--
//  + TL_true
//
type True_Data struct {
}

func (m *True_Data) Reset()                    { *m = True_Data{} }
func (m *True_Data) String() string            { return proto.CompactTextString(m) }
func (*True_Data) ProtoMessage()               {}
func (*True_Data) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

type True struct {
	Constructor TLConstructor `protobuf:"varint,1,opt,name=constructor,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2       *True_Data    `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *True) Reset()                    { *m = True{} }
func (m *True) String() string            { return proto.CompactTextString(m) }
func (*True) ProtoMessage()               {}
func (*True) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *True) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *True) GetData2() *True_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// true#3fedd339 = True;
type TLTrue struct {
	Data2 *True_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLTrue) Reset()                    { *m = TLTrue{} }
func (m *TLTrue) String() string            { return proto.CompactTextString(m) }
func (*TLTrue) ProtoMessage()               {}
func (*TLTrue) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *TLTrue) GetData2() *True_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

func init() {
	proto.RegisterType((*Error_Data)(nil), "mtproto.Error_Data")
	proto.RegisterType((*Error)(nil), "mtproto.Error")
	proto.RegisterType((*TLError)(nil), "mtproto.TL_error")
	proto.RegisterType((*Null_Data)(nil), "mtproto.Null_Data")
	proto.RegisterType((*Null)(nil), "mtproto.Null")
	proto.RegisterType((*TLNull)(nil), "mtproto.TL_null")
	proto.RegisterType((*Bool_Data)(nil), "mtproto.Bool_Data")
	proto.RegisterType((*Bool)(nil), "mtproto.Bool")
	proto.RegisterType((*TLBoolFalse)(nil), "mtproto.TL_boolFalse")
	proto.RegisterType((*TLBoolTrue)(nil), "mtproto.TL_boolTrue")
	proto.RegisterType((*True_Data)(nil), "mtproto.True_Data")
	proto.RegisterType((*True)(nil), "mtproto.True")
	proto.RegisterType((*TLTrue)(nil), "mtproto.TL_true")
}

func init() { proto.RegisterFile("schema.tl.core_types.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x91, 0xcf, 0x4f, 0xc2, 0x30,
	0x14, 0xc7, 0x03, 0x01, 0x71, 0xaf, 0xc6, 0x43, 0x8d, 0x86, 0xe0, 0x85, 0xec, 0x34, 0x2f, 0x3d,
	0x0c, 0x8d, 0x9c, 0xf1, 0x47, 0x3c, 0x4c, 0x63, 0x96, 0xde, 0x97, 0x52, 0x1a, 0xc5, 0x74, 0x7b,
	0xa4, 0xeb, 0x12, 0xfd, 0xef, 0x4d, 0x0b, 0x14, 0xf0, 0x60, 0x24, 0x86, 0xdb, 0xeb, 0xeb, 0xf7,
	0xb3, 0xcf, 0xb7, 0x19, 0x0c, 0x6a, 0xf9, 0xae, 0x4a, 0xc1, 0xac, 0x66, 0x12, 0x8d, 0x2a, 0xec,
	0xd7, 0x42, 0xd5, 0x6c, 0x61, 0xd0, 0x22, 0xed, 0x95, 0xd6, 0x0f, 0x83, 0xf3, 0xad, 0x90, 0x91,
	0xa3, 0x74, 0x79, 0x1f, 0x5f, 0x03, 0x3c, 0x18, 0x83, 0xa6, 0xb8, 0x17, 0x56, 0x50, 0x0a, 0x1d,
	0x89, 0x33, 0xd5, 0x6f, 0x0d, 0x5b, 0x49, 0x37, 0xf7, 0xb3, 0xdb, 0x59, 0xf5, 0x69, 0xfb, 0xed,
	0x61, 0x2b, 0x89, 0x72, 0x3f, 0xc7, 0x1a, 0xba, 0x9e, 0xa2, 0x63, 0x20, 0x12, 0xab, 0xda, 0x9a,
	0x46, 0x5a, 0x34, 0x9e, 0x3b, 0x4d, 0x2f, 0xd8, 0x4a, 0xca, 0x78, 0x76, 0xb7, 0xb9, 0xcd, 0xb7,
	0xa3, 0xf4, 0x0a, 0xba, 0x33, 0x61, 0x45, 0xea, 0xbf, 0x4b, 0xd2, 0xb3, 0xc0, 0x6c, 0xea, 0xe4,
	0xcb, 0x44, 0x7c, 0x03, 0xc7, 0x3c, 0x2b, 0x94, 0x17, 0xee, 0x81, 0x11, 0x88, 0x5e, 0x1a, 0xad,
	0xfd, 0x2e, 0xfe, 0x80, 0x8e, 0x3b, 0xfc, 0xa3, 0x70, 0xb2, 0x6b, 0xa6, 0x81, 0x09, 0x92, 0xb5,
	0x78, 0x04, 0x3d, 0x9e, 0x15, 0x95, 0xd3, 0xfd, 0x1d, 0x22, 0x10, 0x4d, 0x10, 0x37, 0x6d, 0xdd,
	0xe1, 0x10, 0x6d, 0x83, 0x64, 0x2d, 0x1e, 0xc3, 0x09, 0xcf, 0x8a, 0x29, 0xa2, 0x7e, 0x14, 0xba,
	0x56, 0x7b, 0x90, 0xb7, 0x40, 0x56, 0x24, 0x37, 0xcd, 0x3e, 0x20, 0x81, 0xc8, 0x11, 0xe1, 0xad,
	0x1e, 0x3f, 0xc0, 0x5b, 0x83, 0x64, 0xf7, 0xcf, 0xd8, 0x5f, 0xdb, 0xfe, 0x84, 0x26, 0x09, 0x5c,
	0x4a, 0x2c, 0x59, 0xa5, 0xa6, 0x8d, 0x16, 0xf3, 0x92, 0xa9, 0xea, 0x6d, 0x5e, 0xa9, 0x75, 0x7e,
	0xd2, 0x7b, 0xe6, 0xaf, 0x6e, 0x78, 0x6a, 0x4f, 0x8f, 0xfc, 0x66, 0xf4, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0x41, 0x6d, 0x23, 0xb7, 0x91, 0x03, 0x00, 0x00,
}
