// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.tl.transport.proto

package mtproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// /////////////////////////////////////////////////////////////////////////////
// FutureSalt <--
//  + TL_future_salt
//
type FutureSalt_Data struct {
	ValidSince int32 `protobuf:"varint,1,opt,name=valid_since,json=validSince" json:"valid_since,omitempty"`
	ValidUntil int32 `protobuf:"varint,2,opt,name=valid_until,json=validUntil" json:"valid_until,omitempty"`
	Salt       int64 `protobuf:"varint,3,opt,name=salt" json:"salt,omitempty"`
}

func (m *FutureSalt_Data) Reset()                    { *m = FutureSalt_Data{} }
func (m *FutureSalt_Data) String() string            { return proto.CompactTextString(m) }
func (*FutureSalt_Data) ProtoMessage()               {}
func (*FutureSalt_Data) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

func (m *FutureSalt_Data) GetValidSince() int32 {
	if m != nil {
		return m.ValidSince
	}
	return 0
}

func (m *FutureSalt_Data) GetValidUntil() int32 {
	if m != nil {
		return m.ValidUntil
	}
	return 0
}

func (m *FutureSalt_Data) GetSalt() int64 {
	if m != nil {
		return m.Salt
	}
	return 0
}

type FutureSalt struct {
	Constructor TLConstructor    `protobuf:"varint,1,opt,name=constructor,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2       *FutureSalt_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *FutureSalt) Reset()                    { *m = FutureSalt{} }
func (m *FutureSalt) String() string            { return proto.CompactTextString(m) }
func (*FutureSalt) ProtoMessage()               {}
func (*FutureSalt) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{1} }

func (m *FutureSalt) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *FutureSalt) GetData2() *FutureSalt_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// future_salt#0949d9dc valid_since:int valid_until:int salt:long = FutureSalt;
type TLFutureSalt struct {
	Data2 *FutureSalt_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLFutureSalt) Reset()                    { *m = TLFutureSalt{} }
func (m *TLFutureSalt) String() string            { return proto.CompactTextString(m) }
func (*TLFutureSalt) ProtoMessage()               {}
func (*TLFutureSalt) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{2} }

func (m *TLFutureSalt) GetData2() *FutureSalt_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// Pong <--
//  + TL_pong
//
type Pong_Data struct {
	MsgId  int64 `protobuf:"varint,1,opt,name=msg_id,json=msgId" json:"msg_id,omitempty"`
	PingId int64 `protobuf:"varint,2,opt,name=ping_id,json=pingId" json:"ping_id,omitempty"`
}

func (m *Pong_Data) Reset()                    { *m = Pong_Data{} }
func (m *Pong_Data) String() string            { return proto.CompactTextString(m) }
func (*Pong_Data) ProtoMessage()               {}
func (*Pong_Data) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{3} }

func (m *Pong_Data) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *Pong_Data) GetPingId() int64 {
	if m != nil {
		return m.PingId
	}
	return 0
}

type Pong struct {
	Constructor TLConstructor `protobuf:"varint,1,opt,name=constructor,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2       *Pong_Data    `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *Pong) Reset()                    { *m = Pong{} }
func (m *Pong) String() string            { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()               {}
func (*Pong) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{4} }

func (m *Pong) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *Pong) GetData2() *Pong_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// pong#347773c5 msg_id:long ping_id:long = Pong;
type TLPong struct {
	Data2 *Pong_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLPong) Reset()                    { *m = TLPong{} }
func (m *TLPong) String() string            { return proto.CompactTextString(m) }
func (*TLPong) ProtoMessage()               {}
func (*TLPong) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{5} }

func (m *TLPong) GetData2() *Pong_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// DestroySessionRes <--
//  + TL_destroy_session_ok
//  + TL_destroy_session_none
//
type DestroySessionRes_Data struct {
	SessionId int64 `protobuf:"varint,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
}

func (m *DestroySessionRes_Data) Reset()                    { *m = DestroySessionRes_Data{} }
func (m *DestroySessionRes_Data) String() string            { return proto.CompactTextString(m) }
func (*DestroySessionRes_Data) ProtoMessage()               {}
func (*DestroySessionRes_Data) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{6} }

func (m *DestroySessionRes_Data) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type DestroySessionRes struct {
	Constructor TLConstructor           `protobuf:"varint,1,opt,name=constructor,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2       *DestroySessionRes_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *DestroySessionRes) Reset()                    { *m = DestroySessionRes{} }
func (m *DestroySessionRes) String() string            { return proto.CompactTextString(m) }
func (*DestroySessionRes) ProtoMessage()               {}
func (*DestroySessionRes) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{7} }

func (m *DestroySessionRes) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *DestroySessionRes) GetData2() *DestroySessionRes_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// destroy_session_ok#e22045fc session_id:long = DestroySessionRes;
type TLDestroySessionOk struct {
	Data2 *DestroySessionRes_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLDestroySessionOk) Reset()                    { *m = TLDestroySessionOk{} }
func (m *TLDestroySessionOk) String() string            { return proto.CompactTextString(m) }
func (*TLDestroySessionOk) ProtoMessage()               {}
func (*TLDestroySessionOk) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{8} }

func (m *TLDestroySessionOk) GetData2() *DestroySessionRes_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// destroy_session_none#62d350c9 session_id:long = DestroySessionRes;
type TLDestroySessionNone struct {
	Data2 *DestroySessionRes_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLDestroySessionNone) Reset()                    { *m = TLDestroySessionNone{} }
func (m *TLDestroySessionNone) String() string            { return proto.CompactTextString(m) }
func (*TLDestroySessionNone) ProtoMessage()               {}
func (*TLDestroySessionNone) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{9} }

func (m *TLDestroySessionNone) GetData2() *DestroySessionRes_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// NewSession <--
//  + TL_new_session_created
//
type NewSession_Data struct {
	FirstMsgId int64 `protobuf:"varint,1,opt,name=first_msg_id,json=firstMsgId" json:"first_msg_id,omitempty"`
	UniqueId   int64 `protobuf:"varint,2,opt,name=unique_id,json=uniqueId" json:"unique_id,omitempty"`
	ServerSalt int64 `protobuf:"varint,3,opt,name=server_salt,json=serverSalt" json:"server_salt,omitempty"`
}

func (m *NewSession_Data) Reset()                    { *m = NewSession_Data{} }
func (m *NewSession_Data) String() string            { return proto.CompactTextString(m) }
func (*NewSession_Data) ProtoMessage()               {}
func (*NewSession_Data) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{10} }

func (m *NewSession_Data) GetFirstMsgId() int64 {
	if m != nil {
		return m.FirstMsgId
	}
	return 0
}

func (m *NewSession_Data) GetUniqueId() int64 {
	if m != nil {
		return m.UniqueId
	}
	return 0
}

func (m *NewSession_Data) GetServerSalt() int64 {
	if m != nil {
		return m.ServerSalt
	}
	return 0
}

type NewSession struct {
	Constructor TLConstructor    `protobuf:"varint,1,opt,name=constructor,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2       *NewSession_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *NewSession) Reset()                    { *m = NewSession{} }
func (m *NewSession) String() string            { return proto.CompactTextString(m) }
func (*NewSession) ProtoMessage()               {}
func (*NewSession) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{11} }

func (m *NewSession) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *NewSession) GetData2() *NewSession_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// new_session_created#9ec20908 first_msg_id:long unique_id:long server_salt:long = NewSession;
type TLNewSessionCreated struct {
	Data2 *NewSession_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLNewSessionCreated) Reset()                    { *m = TLNewSessionCreated{} }
func (m *TLNewSessionCreated) String() string            { return proto.CompactTextString(m) }
func (*TLNewSessionCreated) ProtoMessage()               {}
func (*TLNewSessionCreated) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{12} }

func (m *TLNewSessionCreated) GetData2() *NewSession_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// help_ConfigSimple <--
//  + TL_help_configSimple
//
type Help_ConfigSimple_Data struct {
	Date       int32       `protobuf:"varint,1,opt,name=date" json:"date,omitempty"`
	Expires    int32       `protobuf:"varint,2,opt,name=expires" json:"expires,omitempty"`
	DcId       int32       `protobuf:"varint,3,opt,name=dc_id,json=dcId" json:"dc_id,omitempty"`
	IpPortList []*TLIpPort `protobuf:"bytes,4,rep,name=ip_port_list,json=ipPortList" json:"ip_port_list,omitempty"`
}

func (m *Help_ConfigSimple_Data) Reset()                    { *m = Help_ConfigSimple_Data{} }
func (m *Help_ConfigSimple_Data) String() string            { return proto.CompactTextString(m) }
func (*Help_ConfigSimple_Data) ProtoMessage()               {}
func (*Help_ConfigSimple_Data) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{13} }

func (m *Help_ConfigSimple_Data) GetDate() int32 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *Help_ConfigSimple_Data) GetExpires() int32 {
	if m != nil {
		return m.Expires
	}
	return 0
}

func (m *Help_ConfigSimple_Data) GetDcId() int32 {
	if m != nil {
		return m.DcId
	}
	return 0
}

func (m *Help_ConfigSimple_Data) GetIpPortList() []*TLIpPort {
	if m != nil {
		return m.IpPortList
	}
	return nil
}

type Help_ConfigSimple struct {
	Constructor TLConstructor           `protobuf:"varint,1,opt,name=constructor,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2       *Help_ConfigSimple_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *Help_ConfigSimple) Reset()                    { *m = Help_ConfigSimple{} }
func (m *Help_ConfigSimple) String() string            { return proto.CompactTextString(m) }
func (*Help_ConfigSimple) ProtoMessage()               {}
func (*Help_ConfigSimple) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{14} }

func (m *Help_ConfigSimple) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *Help_ConfigSimple) GetData2() *Help_ConfigSimple_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// help.configSimple#d997c3c5 date:int expires:int dc_id:int ip_port_list:Vector<ipPort> = help.ConfigSimple;
type TLHelpConfigSimple struct {
	Data2 *Help_ConfigSimple_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLHelpConfigSimple) Reset()                    { *m = TLHelpConfigSimple{} }
func (m *TLHelpConfigSimple) String() string            { return proto.CompactTextString(m) }
func (*TLHelpConfigSimple) ProtoMessage()               {}
func (*TLHelpConfigSimple) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{15} }

func (m *TLHelpConfigSimple) GetData2() *Help_ConfigSimple_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// MsgsStateReq <--
//  + TL_msgs_state_req
//
type MsgsStateReq_Data struct {
	MsgIds []int64 `protobuf:"varint,1,rep,packed,name=msg_ids,json=msgIds" json:"msg_ids,omitempty"`
}

func (m *MsgsStateReq_Data) Reset()                    { *m = MsgsStateReq_Data{} }
func (m *MsgsStateReq_Data) String() string            { return proto.CompactTextString(m) }
func (*MsgsStateReq_Data) ProtoMessage()               {}
func (*MsgsStateReq_Data) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{16} }

func (m *MsgsStateReq_Data) GetMsgIds() []int64 {
	if m != nil {
		return m.MsgIds
	}
	return nil
}

type MsgsStateReq struct {
	Constructor TLConstructor      `protobuf:"varint,1,opt,name=constructor,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2       *MsgsStateReq_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *MsgsStateReq) Reset()                    { *m = MsgsStateReq{} }
func (m *MsgsStateReq) String() string            { return proto.CompactTextString(m) }
func (*MsgsStateReq) ProtoMessage()               {}
func (*MsgsStateReq) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{17} }

func (m *MsgsStateReq) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *MsgsStateReq) GetData2() *MsgsStateReq_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// msgs_state_req#da69fb52 msg_ids:Vector<long> = MsgsStateReq;
type TLMsgsStateReq struct {
	Data2 *MsgsStateReq_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLMsgsStateReq) Reset()                    { *m = TLMsgsStateReq{} }
func (m *TLMsgsStateReq) String() string            { return proto.CompactTextString(m) }
func (*TLMsgsStateReq) ProtoMessage()               {}
func (*TLMsgsStateReq) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{18} }

func (m *TLMsgsStateReq) GetData2() *MsgsStateReq_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// MsgsAllInfo <--
//  + TL_msgs_all_info
//
type MsgsAllInfo_Data struct {
	MsgIds []int64 `protobuf:"varint,1,rep,packed,name=msg_ids,json=msgIds" json:"msg_ids,omitempty"`
	Info   string  `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *MsgsAllInfo_Data) Reset()                    { *m = MsgsAllInfo_Data{} }
func (m *MsgsAllInfo_Data) String() string            { return proto.CompactTextString(m) }
func (*MsgsAllInfo_Data) ProtoMessage()               {}
func (*MsgsAllInfo_Data) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{19} }

func (m *MsgsAllInfo_Data) GetMsgIds() []int64 {
	if m != nil {
		return m.MsgIds
	}
	return nil
}

func (m *MsgsAllInfo_Data) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type MsgsAllInfo struct {
	Constructor TLConstructor     `protobuf:"varint,1,opt,name=constructor,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2       *MsgsAllInfo_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *MsgsAllInfo) Reset()                    { *m = MsgsAllInfo{} }
func (m *MsgsAllInfo) String() string            { return proto.CompactTextString(m) }
func (*MsgsAllInfo) ProtoMessage()               {}
func (*MsgsAllInfo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{20} }

func (m *MsgsAllInfo) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *MsgsAllInfo) GetData2() *MsgsAllInfo_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// msgs_all_info#8cc0d131 msg_ids:Vector<long> info:string = MsgsAllInfo;
type TLMsgsAllInfo struct {
	Data2 *MsgsAllInfo_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLMsgsAllInfo) Reset()                    { *m = TLMsgsAllInfo{} }
func (m *TLMsgsAllInfo) String() string            { return proto.CompactTextString(m) }
func (*TLMsgsAllInfo) ProtoMessage()               {}
func (*TLMsgsAllInfo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{21} }

func (m *TLMsgsAllInfo) GetData2() *MsgsAllInfo_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// MsgResendReq <--
//  + TL_msg_resend_req
//
type MsgResendReq_Data struct {
	MsgIds []int64 `protobuf:"varint,1,rep,packed,name=msg_ids,json=msgIds" json:"msg_ids,omitempty"`
}

func (m *MsgResendReq_Data) Reset()                    { *m = MsgResendReq_Data{} }
func (m *MsgResendReq_Data) String() string            { return proto.CompactTextString(m) }
func (*MsgResendReq_Data) ProtoMessage()               {}
func (*MsgResendReq_Data) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{22} }

func (m *MsgResendReq_Data) GetMsgIds() []int64 {
	if m != nil {
		return m.MsgIds
	}
	return nil
}

type MsgResendReq struct {
	Constructor TLConstructor      `protobuf:"varint,1,opt,name=constructor,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2       *MsgResendReq_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *MsgResendReq) Reset()                    { *m = MsgResendReq{} }
func (m *MsgResendReq) String() string            { return proto.CompactTextString(m) }
func (*MsgResendReq) ProtoMessage()               {}
func (*MsgResendReq) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{23} }

func (m *MsgResendReq) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *MsgResendReq) GetData2() *MsgResendReq_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// msg_resend_req#7d861a08 msg_ids:Vector<long> = MsgResendReq;
type TLMsgResendReq struct {
	Data2 *MsgResendReq_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLMsgResendReq) Reset()                    { *m = TLMsgResendReq{} }
func (m *TLMsgResendReq) String() string            { return proto.CompactTextString(m) }
func (*TLMsgResendReq) ProtoMessage()               {}
func (*TLMsgResendReq) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{24} }

func (m *TLMsgResendReq) GetData2() *MsgResendReq_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// RpcDropAnswer <--
//  + TL_rpc_answer_unknown
//  + TL_rpc_answer_dropped_running
//  + TL_rpc_answer_dropped
//
type RpcDropAnswer_Data struct {
	MsgId int64 `protobuf:"varint,1,opt,name=msg_id,json=msgId" json:"msg_id,omitempty"`
	SeqNo int32 `protobuf:"varint,2,opt,name=seq_no,json=seqNo" json:"seq_no,omitempty"`
	Bytes int32 `protobuf:"varint,3,opt,name=bytes" json:"bytes,omitempty"`
}

func (m *RpcDropAnswer_Data) Reset()                    { *m = RpcDropAnswer_Data{} }
func (m *RpcDropAnswer_Data) String() string            { return proto.CompactTextString(m) }
func (*RpcDropAnswer_Data) ProtoMessage()               {}
func (*RpcDropAnswer_Data) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{25} }

func (m *RpcDropAnswer_Data) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *RpcDropAnswer_Data) GetSeqNo() int32 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

func (m *RpcDropAnswer_Data) GetBytes() int32 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

type RpcDropAnswer struct {
	Constructor TLConstructor       `protobuf:"varint,1,opt,name=constructor,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2       *RpcDropAnswer_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *RpcDropAnswer) Reset()                    { *m = RpcDropAnswer{} }
func (m *RpcDropAnswer) String() string            { return proto.CompactTextString(m) }
func (*RpcDropAnswer) ProtoMessage()               {}
func (*RpcDropAnswer) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{26} }

func (m *RpcDropAnswer) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *RpcDropAnswer) GetData2() *RpcDropAnswer_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// rpc_answer_unknown#5e2ad36e = RpcDropAnswer;
type TLRpcAnswerUnknown struct {
	Data2 *RpcDropAnswer_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLRpcAnswerUnknown) Reset()                    { *m = TLRpcAnswerUnknown{} }
func (m *TLRpcAnswerUnknown) String() string            { return proto.CompactTextString(m) }
func (*TLRpcAnswerUnknown) ProtoMessage()               {}
func (*TLRpcAnswerUnknown) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{27} }

func (m *TLRpcAnswerUnknown) GetData2() *RpcDropAnswer_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// rpc_answer_dropped_running#cd78e586 = RpcDropAnswer;
type TLRpcAnswerDroppedRunning struct {
	Data2 *RpcDropAnswer_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLRpcAnswerDroppedRunning) Reset()                    { *m = TLRpcAnswerDroppedRunning{} }
func (m *TLRpcAnswerDroppedRunning) String() string            { return proto.CompactTextString(m) }
func (*TLRpcAnswerDroppedRunning) ProtoMessage()               {}
func (*TLRpcAnswerDroppedRunning) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{28} }

func (m *TLRpcAnswerDroppedRunning) GetData2() *RpcDropAnswer_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// rpc_answer_dropped#a43ad8b7 msg_id:long seq_no:int bytes:int = RpcDropAnswer;
type TLRpcAnswerDropped struct {
	Data2 *RpcDropAnswer_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLRpcAnswerDropped) Reset()                    { *m = TLRpcAnswerDropped{} }
func (m *TLRpcAnswerDropped) String() string            { return proto.CompactTextString(m) }
func (*TLRpcAnswerDropped) ProtoMessage()               {}
func (*TLRpcAnswerDropped) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{29} }

func (m *TLRpcAnswerDropped) GetData2() *RpcDropAnswer_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// BadMsgNotification <--
//  + TL_bad_msg_notification
//  + TL_bad_server_salt
//
type BadMsgNotification_Data struct {
	BadMsgId      int64 `protobuf:"varint,1,opt,name=bad_msg_id,json=badMsgId" json:"bad_msg_id,omitempty"`
	BadMsgSeqno   int32 `protobuf:"varint,2,opt,name=bad_msg_seqno,json=badMsgSeqno" json:"bad_msg_seqno,omitempty"`
	ErrorCode     int32 `protobuf:"varint,3,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	NewServerSalt int64 `protobuf:"varint,4,opt,name=new_server_salt,json=newServerSalt" json:"new_server_salt,omitempty"`
}

func (m *BadMsgNotification_Data) Reset()                    { *m = BadMsgNotification_Data{} }
func (m *BadMsgNotification_Data) String() string            { return proto.CompactTextString(m) }
func (*BadMsgNotification_Data) ProtoMessage()               {}
func (*BadMsgNotification_Data) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{30} }

func (m *BadMsgNotification_Data) GetBadMsgId() int64 {
	if m != nil {
		return m.BadMsgId
	}
	return 0
}

func (m *BadMsgNotification_Data) GetBadMsgSeqno() int32 {
	if m != nil {
		return m.BadMsgSeqno
	}
	return 0
}

func (m *BadMsgNotification_Data) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *BadMsgNotification_Data) GetNewServerSalt() int64 {
	if m != nil {
		return m.NewServerSalt
	}
	return 0
}

type BadMsgNotification struct {
	Constructor TLConstructor            `protobuf:"varint,1,opt,name=constructor,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2       *BadMsgNotification_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *BadMsgNotification) Reset()                    { *m = BadMsgNotification{} }
func (m *BadMsgNotification) String() string            { return proto.CompactTextString(m) }
func (*BadMsgNotification) ProtoMessage()               {}
func (*BadMsgNotification) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{31} }

func (m *BadMsgNotification) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *BadMsgNotification) GetData2() *BadMsgNotification_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// bad_msg_notification#a7eff811 bad_msg_id:long bad_msg_seqno:int error_code:int = BadMsgNotification;
type TLBadMsgNotification struct {
	Data2 *BadMsgNotification_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLBadMsgNotification) Reset()                    { *m = TLBadMsgNotification{} }
func (m *TLBadMsgNotification) String() string            { return proto.CompactTextString(m) }
func (*TLBadMsgNotification) ProtoMessage()               {}
func (*TLBadMsgNotification) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{32} }

func (m *TLBadMsgNotification) GetData2() *BadMsgNotification_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// bad_server_salt#edab447b bad_msg_id:long bad_msg_seqno:int error_code:int new_server_salt:long = BadMsgNotification;
type TLBadServerSalt struct {
	Data2 *BadMsgNotification_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLBadServerSalt) Reset()                    { *m = TLBadServerSalt{} }
func (m *TLBadServerSalt) String() string            { return proto.CompactTextString(m) }
func (*TLBadServerSalt) ProtoMessage()               {}
func (*TLBadServerSalt) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{33} }

func (m *TLBadServerSalt) GetData2() *BadMsgNotification_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// MsgsStateInfo <--
//  + TL_msgs_state_info
//
type MsgsStateInfo_Data struct {
	ReqMsgId int64  `protobuf:"varint,1,opt,name=req_msg_id,json=reqMsgId" json:"req_msg_id,omitempty"`
	Info     string `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *MsgsStateInfo_Data) Reset()                    { *m = MsgsStateInfo_Data{} }
func (m *MsgsStateInfo_Data) String() string            { return proto.CompactTextString(m) }
func (*MsgsStateInfo_Data) ProtoMessage()               {}
func (*MsgsStateInfo_Data) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{34} }

func (m *MsgsStateInfo_Data) GetReqMsgId() int64 {
	if m != nil {
		return m.ReqMsgId
	}
	return 0
}

func (m *MsgsStateInfo_Data) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type MsgsStateInfo struct {
	Constructor TLConstructor       `protobuf:"varint,1,opt,name=constructor,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2       *MsgsStateInfo_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *MsgsStateInfo) Reset()                    { *m = MsgsStateInfo{} }
func (m *MsgsStateInfo) String() string            { return proto.CompactTextString(m) }
func (*MsgsStateInfo) ProtoMessage()               {}
func (*MsgsStateInfo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{35} }

func (m *MsgsStateInfo) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *MsgsStateInfo) GetData2() *MsgsStateInfo_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// msgs_state_info#04deb57d req_msg_id:long info:string = MsgsStateInfo;
type TLMsgsStateInfo struct {
	Data2 *MsgsStateInfo_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLMsgsStateInfo) Reset()                    { *m = TLMsgsStateInfo{} }
func (m *TLMsgsStateInfo) String() string            { return proto.CompactTextString(m) }
func (*TLMsgsStateInfo) ProtoMessage()               {}
func (*TLMsgsStateInfo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{36} }

func (m *TLMsgsStateInfo) GetData2() *MsgsStateInfo_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// MsgDetailedInfo <--
//  + TL_msg_detailed_info
//  + TL_msg_new_detailed_info
//
type MsgDetailedInfo_Data struct {
	MsgId       int64 `protobuf:"varint,1,opt,name=msg_id,json=msgId" json:"msg_id,omitempty"`
	AnswerMsgId int64 `protobuf:"varint,2,opt,name=answer_msg_id,json=answerMsgId" json:"answer_msg_id,omitempty"`
	Bytes       int32 `protobuf:"varint,3,opt,name=bytes" json:"bytes,omitempty"`
	Status      int32 `protobuf:"varint,4,opt,name=status" json:"status,omitempty"`
}

func (m *MsgDetailedInfo_Data) Reset()                    { *m = MsgDetailedInfo_Data{} }
func (m *MsgDetailedInfo_Data) String() string            { return proto.CompactTextString(m) }
func (*MsgDetailedInfo_Data) ProtoMessage()               {}
func (*MsgDetailedInfo_Data) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{37} }

func (m *MsgDetailedInfo_Data) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *MsgDetailedInfo_Data) GetAnswerMsgId() int64 {
	if m != nil {
		return m.AnswerMsgId
	}
	return 0
}

func (m *MsgDetailedInfo_Data) GetBytes() int32 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

func (m *MsgDetailedInfo_Data) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type MsgDetailedInfo struct {
	Constructor TLConstructor         `protobuf:"varint,1,opt,name=constructor,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2       *MsgDetailedInfo_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *MsgDetailedInfo) Reset()                    { *m = MsgDetailedInfo{} }
func (m *MsgDetailedInfo) String() string            { return proto.CompactTextString(m) }
func (*MsgDetailedInfo) ProtoMessage()               {}
func (*MsgDetailedInfo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{38} }

func (m *MsgDetailedInfo) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *MsgDetailedInfo) GetData2() *MsgDetailedInfo_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// msg_detailed_info#276d3ec6 msg_id:long answer_msg_id:long bytes:int status:int = MsgDetailedInfo;
type TLMsgDetailedInfo struct {
	Data2 *MsgDetailedInfo_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLMsgDetailedInfo) Reset()                    { *m = TLMsgDetailedInfo{} }
func (m *TLMsgDetailedInfo) String() string            { return proto.CompactTextString(m) }
func (*TLMsgDetailedInfo) ProtoMessage()               {}
func (*TLMsgDetailedInfo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{39} }

func (m *TLMsgDetailedInfo) GetData2() *MsgDetailedInfo_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// msg_new_detailed_info#809db6df answer_msg_id:long bytes:int status:int = MsgDetailedInfo;
type TLMsgNewDetailedInfo struct {
	Data2 *MsgDetailedInfo_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLMsgNewDetailedInfo) Reset()                    { *m = TLMsgNewDetailedInfo{} }
func (m *TLMsgNewDetailedInfo) String() string            { return proto.CompactTextString(m) }
func (*TLMsgNewDetailedInfo) ProtoMessage()               {}
func (*TLMsgNewDetailedInfo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{40} }

func (m *TLMsgNewDetailedInfo) GetData2() *MsgDetailedInfo_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// RpcError <--
//  + TL_rpc_error
//
type RpcError_Data struct {
	ErrorCode    int32  `protobuf:"varint,1,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
}

func (m *RpcError_Data) Reset()                    { *m = RpcError_Data{} }
func (m *RpcError_Data) String() string            { return proto.CompactTextString(m) }
func (*RpcError_Data) ProtoMessage()               {}
func (*RpcError_Data) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{41} }

func (m *RpcError_Data) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *RpcError_Data) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type RpcError struct {
	Constructor TLConstructor  `protobuf:"varint,1,opt,name=constructor,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2       *RpcError_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *RpcError) Reset()                    { *m = RpcError{} }
func (m *RpcError) String() string            { return proto.CompactTextString(m) }
func (*RpcError) ProtoMessage()               {}
func (*RpcError) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{42} }

func (m *RpcError) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *RpcError) GetData2() *RpcError_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// rpc_error#2144ca19 error_code:int error_message:string = RpcError;
type TLRpcError struct {
	Data2 *RpcError_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLRpcError) Reset()                    { *m = TLRpcError{} }
func (m *TLRpcError) String() string            { return proto.CompactTextString(m) }
func (*TLRpcError) ProtoMessage()               {}
func (*TLRpcError) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{43} }

func (m *TLRpcError) GetData2() *RpcError_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// HttpWait <--
//  + TL_http_wait
//
type HttpWait_Data struct {
	MaxDelay  int32 `protobuf:"varint,1,opt,name=max_delay,json=maxDelay" json:"max_delay,omitempty"`
	WaitAfter int32 `protobuf:"varint,2,opt,name=wait_after,json=waitAfter" json:"wait_after,omitempty"`
	MaxWait   int32 `protobuf:"varint,3,opt,name=max_wait,json=maxWait" json:"max_wait,omitempty"`
}

func (m *HttpWait_Data) Reset()                    { *m = HttpWait_Data{} }
func (m *HttpWait_Data) String() string            { return proto.CompactTextString(m) }
func (*HttpWait_Data) ProtoMessage()               {}
func (*HttpWait_Data) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{44} }

func (m *HttpWait_Data) GetMaxDelay() int32 {
	if m != nil {
		return m.MaxDelay
	}
	return 0
}

func (m *HttpWait_Data) GetWaitAfter() int32 {
	if m != nil {
		return m.WaitAfter
	}
	return 0
}

func (m *HttpWait_Data) GetMaxWait() int32 {
	if m != nil {
		return m.MaxWait
	}
	return 0
}

type HttpWait struct {
	Constructor TLConstructor  `protobuf:"varint,1,opt,name=constructor,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2       *HttpWait_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *HttpWait) Reset()                    { *m = HttpWait{} }
func (m *HttpWait) String() string            { return proto.CompactTextString(m) }
func (*HttpWait) ProtoMessage()               {}
func (*HttpWait) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{45} }

func (m *HttpWait) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *HttpWait) GetData2() *HttpWait_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// http_wait#9299359f max_delay:int wait_after:int max_wait:int = HttpWait;
type TLHttpWait struct {
	Data2 *HttpWait_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLHttpWait) Reset()                    { *m = TLHttpWait{} }
func (m *TLHttpWait) String() string            { return proto.CompactTextString(m) }
func (*TLHttpWait) ProtoMessage()               {}
func (*TLHttpWait) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{46} }

func (m *TLHttpWait) GetData2() *HttpWait_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// IpPort <--
//  + TL_ipPort
//
type IpPort_Data struct {
	Ipv4 int32 `protobuf:"varint,1,opt,name=ipv4" json:"ipv4,omitempty"`
	Port int32 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *IpPort_Data) Reset()                    { *m = IpPort_Data{} }
func (m *IpPort_Data) String() string            { return proto.CompactTextString(m) }
func (*IpPort_Data) ProtoMessage()               {}
func (*IpPort_Data) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{47} }

func (m *IpPort_Data) GetIpv4() int32 {
	if m != nil {
		return m.Ipv4
	}
	return 0
}

func (m *IpPort_Data) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type IpPort struct {
	Constructor TLConstructor `protobuf:"varint,1,opt,name=constructor,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2       *IpPort_Data  `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *IpPort) Reset()                    { *m = IpPort{} }
func (m *IpPort) String() string            { return proto.CompactTextString(m) }
func (*IpPort) ProtoMessage()               {}
func (*IpPort) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{48} }

func (m *IpPort) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *IpPort) GetData2() *IpPort_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// ipPort#d433ad73 ipv4:int port:int = IpPort;
type TLIpPort struct {
	Data2 *IpPort_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLIpPort) Reset()                    { *m = TLIpPort{} }
func (m *TLIpPort) String() string            { return proto.CompactTextString(m) }
func (*TLIpPort) ProtoMessage()               {}
func (*TLIpPort) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{49} }

func (m *TLIpPort) GetData2() *IpPort_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// MsgsAck <--
//  + TL_msgs_ack
//
type MsgsAck_Data struct {
	MsgIds []int64 `protobuf:"varint,1,rep,packed,name=msg_ids,json=msgIds" json:"msg_ids,omitempty"`
}

func (m *MsgsAck_Data) Reset()                    { *m = MsgsAck_Data{} }
func (m *MsgsAck_Data) String() string            { return proto.CompactTextString(m) }
func (*MsgsAck_Data) ProtoMessage()               {}
func (*MsgsAck_Data) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{50} }

func (m *MsgsAck_Data) GetMsgIds() []int64 {
	if m != nil {
		return m.MsgIds
	}
	return nil
}

type MsgsAck struct {
	Constructor TLConstructor `protobuf:"varint,1,opt,name=constructor,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2       *MsgsAck_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *MsgsAck) Reset()                    { *m = MsgsAck{} }
func (m *MsgsAck) String() string            { return proto.CompactTextString(m) }
func (*MsgsAck) ProtoMessage()               {}
func (*MsgsAck) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{51} }

func (m *MsgsAck) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *MsgsAck) GetData2() *MsgsAck_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// msgs_ack#62d6b459 msg_ids:Vector<long> = MsgsAck;
type TLMsgsAck struct {
	Data2 *MsgsAck_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLMsgsAck) Reset()                    { *m = TLMsgsAck{} }
func (m *TLMsgsAck) String() string            { return proto.CompactTextString(m) }
func (*TLMsgsAck) ProtoMessage()               {}
func (*TLMsgsAck) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{52} }

func (m *TLMsgsAck) GetData2() *MsgsAck_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// FutureSalts <--
//  + TL_future_salts
//
type FutureSalts_Data struct {
	ReqMsgId int64           `protobuf:"varint,1,opt,name=req_msg_id,json=reqMsgId" json:"req_msg_id,omitempty"`
	Now      int32           `protobuf:"varint,2,opt,name=now" json:"now,omitempty"`
	Salts    []*TLFutureSalt `protobuf:"bytes,3,rep,name=salts" json:"salts,omitempty"`
}

func (m *FutureSalts_Data) Reset()                    { *m = FutureSalts_Data{} }
func (m *FutureSalts_Data) String() string            { return proto.CompactTextString(m) }
func (*FutureSalts_Data) ProtoMessage()               {}
func (*FutureSalts_Data) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{53} }

func (m *FutureSalts_Data) GetReqMsgId() int64 {
	if m != nil {
		return m.ReqMsgId
	}
	return 0
}

func (m *FutureSalts_Data) GetNow() int32 {
	if m != nil {
		return m.Now
	}
	return 0
}

func (m *FutureSalts_Data) GetSalts() []*TLFutureSalt {
	if m != nil {
		return m.Salts
	}
	return nil
}

type FutureSalts struct {
	Constructor TLConstructor     `protobuf:"varint,1,opt,name=constructor,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2       *FutureSalts_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *FutureSalts) Reset()                    { *m = FutureSalts{} }
func (m *FutureSalts) String() string            { return proto.CompactTextString(m) }
func (*FutureSalts) ProtoMessage()               {}
func (*FutureSalts) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{54} }

func (m *FutureSalts) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *FutureSalts) GetData2() *FutureSalts_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// future_salts#ae500895 req_msg_id:long now:int salts:vector<future_salt> = FutureSalts;
type TLFutureSalts struct {
	Data2 *FutureSalts_Data `protobuf:"bytes,2,opt,name=data2" json:"data2,omitempty"`
}

func (m *TLFutureSalts) Reset()                    { *m = TLFutureSalts{} }
func (m *TLFutureSalts) String() string            { return proto.CompactTextString(m) }
func (*TLFutureSalts) ProtoMessage()               {}
func (*TLFutureSalts) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{55} }

func (m *TLFutureSalts) GetData2() *FutureSalts_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

func init() {
	proto.RegisterType((*FutureSalt_Data)(nil), "mtproto.FutureSalt_Data")
	proto.RegisterType((*FutureSalt)(nil), "mtproto.FutureSalt")
	proto.RegisterType((*TLFutureSalt)(nil), "mtproto.TL_future_salt")
	proto.RegisterType((*Pong_Data)(nil), "mtproto.Pong_Data")
	proto.RegisterType((*Pong)(nil), "mtproto.Pong")
	proto.RegisterType((*TLPong)(nil), "mtproto.TL_pong")
	proto.RegisterType((*DestroySessionRes_Data)(nil), "mtproto.DestroySessionRes_Data")
	proto.RegisterType((*DestroySessionRes)(nil), "mtproto.DestroySessionRes")
	proto.RegisterType((*TLDestroySessionOk)(nil), "mtproto.TL_destroy_session_ok")
	proto.RegisterType((*TLDestroySessionNone)(nil), "mtproto.TL_destroy_session_none")
	proto.RegisterType((*NewSession_Data)(nil), "mtproto.NewSession_Data")
	proto.RegisterType((*NewSession)(nil), "mtproto.NewSession")
	proto.RegisterType((*TLNewSessionCreated)(nil), "mtproto.TL_new_session_created")
	proto.RegisterType((*Help_ConfigSimple_Data)(nil), "mtproto.help_ConfigSimple_Data")
	proto.RegisterType((*Help_ConfigSimple)(nil), "mtproto.help_ConfigSimple")
	proto.RegisterType((*TLHelpConfigSimple)(nil), "mtproto.TL_help_configSimple")
	proto.RegisterType((*MsgsStateReq_Data)(nil), "mtproto.MsgsStateReq_Data")
	proto.RegisterType((*MsgsStateReq)(nil), "mtproto.MsgsStateReq")
	proto.RegisterType((*TLMsgsStateReq)(nil), "mtproto.TL_msgs_state_req")
	proto.RegisterType((*MsgsAllInfo_Data)(nil), "mtproto.MsgsAllInfo_Data")
	proto.RegisterType((*MsgsAllInfo)(nil), "mtproto.MsgsAllInfo")
	proto.RegisterType((*TLMsgsAllInfo)(nil), "mtproto.TL_msgs_all_info")
	proto.RegisterType((*MsgResendReq_Data)(nil), "mtproto.MsgResendReq_Data")
	proto.RegisterType((*MsgResendReq)(nil), "mtproto.MsgResendReq")
	proto.RegisterType((*TLMsgResendReq)(nil), "mtproto.TL_msg_resend_req")
	proto.RegisterType((*RpcDropAnswer_Data)(nil), "mtproto.RpcDropAnswer_Data")
	proto.RegisterType((*RpcDropAnswer)(nil), "mtproto.RpcDropAnswer")
	proto.RegisterType((*TLRpcAnswerUnknown)(nil), "mtproto.TL_rpc_answer_unknown")
	proto.RegisterType((*TLRpcAnswerDroppedRunning)(nil), "mtproto.TL_rpc_answer_dropped_running")
	proto.RegisterType((*TLRpcAnswerDropped)(nil), "mtproto.TL_rpc_answer_dropped")
	proto.RegisterType((*BadMsgNotification_Data)(nil), "mtproto.BadMsgNotification_Data")
	proto.RegisterType((*BadMsgNotification)(nil), "mtproto.BadMsgNotification")
	proto.RegisterType((*TLBadMsgNotification)(nil), "mtproto.TL_bad_msg_notification")
	proto.RegisterType((*TLBadServerSalt)(nil), "mtproto.TL_bad_server_salt")
	proto.RegisterType((*MsgsStateInfo_Data)(nil), "mtproto.MsgsStateInfo_Data")
	proto.RegisterType((*MsgsStateInfo)(nil), "mtproto.MsgsStateInfo")
	proto.RegisterType((*TLMsgsStateInfo)(nil), "mtproto.TL_msgs_state_info")
	proto.RegisterType((*MsgDetailedInfo_Data)(nil), "mtproto.MsgDetailedInfo_Data")
	proto.RegisterType((*MsgDetailedInfo)(nil), "mtproto.MsgDetailedInfo")
	proto.RegisterType((*TLMsgDetailedInfo)(nil), "mtproto.TL_msg_detailed_info")
	proto.RegisterType((*TLMsgNewDetailedInfo)(nil), "mtproto.TL_msg_new_detailed_info")
	proto.RegisterType((*RpcError_Data)(nil), "mtproto.RpcError_Data")
	proto.RegisterType((*RpcError)(nil), "mtproto.RpcError")
	proto.RegisterType((*TLRpcError)(nil), "mtproto.TL_rpc_error")
	proto.RegisterType((*HttpWait_Data)(nil), "mtproto.HttpWait_Data")
	proto.RegisterType((*HttpWait)(nil), "mtproto.HttpWait")
	proto.RegisterType((*TLHttpWait)(nil), "mtproto.TL_http_wait")
	proto.RegisterType((*IpPort_Data)(nil), "mtproto.IpPort_Data")
	proto.RegisterType((*IpPort)(nil), "mtproto.IpPort")
	proto.RegisterType((*TLIpPort)(nil), "mtproto.TL_ipPort")
	proto.RegisterType((*MsgsAck_Data)(nil), "mtproto.MsgsAck_Data")
	proto.RegisterType((*MsgsAck)(nil), "mtproto.MsgsAck")
	proto.RegisterType((*TLMsgsAck)(nil), "mtproto.TL_msgs_ack")
	proto.RegisterType((*FutureSalts_Data)(nil), "mtproto.FutureSalts_Data")
	proto.RegisterType((*FutureSalts)(nil), "mtproto.FutureSalts")
	proto.RegisterType((*TLFutureSalts)(nil), "mtproto.TL_future_salts")
}

func init() { proto.RegisterFile("schema.tl.transport.proto", fileDescriptor7) }

var fileDescriptor7 = []byte{
	// 1358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xdb, 0x73, 0x1b, 0xb5,
	0x17, 0x1e, 0xd7, 0x71, 0x1c, 0x1f, 0xc7, 0x4d, 0xba, 0xbf, 0x5c, 0xdc, 0xa6, 0x9d, 0x66, 0xf6,
	0x37, 0x03, 0x19, 0x28, 0x06, 0x92, 0x16, 0x18, 0x60, 0x06, 0x72, 0x69, 0xa9, 0xc1, 0x0e, 0x61,
	0x6d, 0x06, 0xde, 0x34, 0xca, 0xae, 0xec, 0x2e, 0x59, 0x6b, 0xd7, 0x92, 0x9c, 0xa4, 0x4c, 0x67,
	0xe0, 0x81, 0xe1, 0x9d, 0x7f, 0x81, 0xbf, 0x94, 0xd1, 0x65, 0x6f, 0x71, 0xda, 0xc6, 0x76, 0xfd,
	0x64, 0xed, 0xd1, 0x39, 0x9f, 0xbe, 0xf3, 0x49, 0x3a, 0x92, 0x0c, 0x77, 0xb9, 0xfb, 0x82, 0x0c,
	0x70, 0x43, 0x04, 0x0d, 0xc1, 0x30, 0xe5, 0x51, 0xc8, 0x44, 0x23, 0x62, 0xa1, 0x08, 0xad, 0xf2,
	0x40, 0xa8, 0xc6, 0xbd, 0xf5, 0xd4, 0xc7, 0x65, 0xee, 0xde, 0xae, 0xee, 0xb7, 0xfb, 0xb0, 0xf2,
	0x6c, 0x24, 0x46, 0x8c, 0x74, 0x70, 0x20, 0xd0, 0x11, 0x16, 0xd8, 0x7a, 0x08, 0xd5, 0x73, 0x1c,
	0xf8, 0x1e, 0xe2, 0x3e, 0x75, 0x49, 0xbd, 0xb0, 0x5d, 0xd8, 0x29, 0x39, 0xa0, 0x4c, 0x1d, 0x69,
	0x49, 0x1d, 0x46, 0x54, 0xf8, 0x41, 0xfd, 0x56, 0xc6, 0xe1, 0x67, 0x69, 0xb1, 0x2c, 0x58, 0xe0,
	0x38, 0x10, 0xf5, 0xe2, 0x76, 0x61, 0xa7, 0xe8, 0xa8, 0xb6, 0x7d, 0x0e, 0x90, 0x0e, 0x64, 0x7d,
	0x01, 0x55, 0x37, 0xa4, 0x5c, 0xb0, 0x91, 0x2b, 0x42, 0xa6, 0xc6, 0xb8, 0xbd, 0xbb, 0xd1, 0x30,
	0x64, 0x1b, 0xdd, 0xd6, 0x61, 0xda, 0xeb, 0x64, 0x5d, 0xad, 0x06, 0x94, 0x3c, 0x2c, 0xf0, 0xae,
	0x1a, 0xb6, 0xba, 0x5b, 0x4f, 0x62, 0xae, 0xa4, 0xe1, 0x68, 0x37, 0xfb, 0x5b, 0xb8, 0xdd, 0x6d,
	0xa1, 0x9e, 0xea, 0x44, 0x92, 0xc9, 0xc4, 0x08, 0x5f, 0x41, 0xe5, 0x24, 0xa4, 0x7d, 0x2d, 0xce,
	0x3a, 0x2c, 0x0e, 0x78, 0x1f, 0xf9, 0x9e, 0xe2, 0x5c, 0x74, 0x4a, 0x03, 0xde, 0x6f, 0x7a, 0xd6,
	0x26, 0x94, 0x23, 0x9f, 0x2a, 0xfb, 0x2d, 0x65, 0x5f, 0x94, 0x9f, 0x4d, 0xcf, 0xfe, 0x0d, 0x16,
	0x64, 0xf0, 0x0c, 0x09, 0xef, 0xe4, 0xe9, 0x5a, 0x49, 0x4c, 0x42, 0x2a, 0x26, 0xba, 0x07, 0xe5,
	0x6e, 0x0b, 0x45, 0x72, 0xb8, 0x9b, 0x07, 0x7d, 0x0e, 0x1b, 0x47, 0x84, 0x0b, 0x16, 0xbe, 0xec,
	0x10, 0xce, 0xfd, 0x90, 0x3a, 0x84, 0xeb, 0x54, 0x1f, 0x00, 0x70, 0x6d, 0x4a, 0xd3, 0xad, 0x18,
	0x4b, 0xd3, 0xb3, 0xff, 0x2a, 0xc0, 0x9d, 0xb1, 0xc8, 0x19, 0xf2, 0x7c, 0x92, 0xa7, 0xfc, 0x30,
	0x89, 0xb9, 0x9e, 0x5e, 0xcc, 0xff, 0x18, 0xd6, 0xbb, 0x2d, 0xe4, 0x69, 0x1f, 0x14, 0x13, 0x0e,
	0xcf, 0xa6, 0xc5, 0x3b, 0x81, 0xcd, 0x6b, 0xf0, 0x68, 0x48, 0xc9, 0xb4, 0x88, 0x43, 0x58, 0x39,
	0x26, 0x17, 0xa6, 0x53, 0x4b, 0xbb, 0x0d, 0xcb, 0x3d, 0x9f, 0x71, 0x81, 0x72, 0x6b, 0x09, 0x94,
	0xad, 0xad, 0x16, 0xd4, 0x16, 0x54, 0x46, 0xd4, 0x1f, 0x8e, 0x48, 0xba, 0xa4, 0x96, 0xb4, 0xa1,
	0xe9, 0xc9, 0x0d, 0xc8, 0x09, 0x3b, 0x27, 0x0c, 0x65, 0xb6, 0x19, 0x68, 0x53, 0xc7, 0x6c, 0xb6,
	0x74, 0xc8, 0x79, 0x6c, 0xb6, 0x2b, 0x09, 0xc5, 0xa9, 0x3e, 0x87, 0x8d, 0x6e, 0x0b, 0x51, 0x72,
	0x91, 0x08, 0xe7, 0x32, 0x82, 0x05, 0xf1, 0x26, 0x46, 0xfa, 0xa7, 0x00, 0x1b, 0x2f, 0x48, 0x10,
	0xa1, 0xc3, 0x90, 0xf6, 0xfc, 0x7e, 0xc7, 0x1f, 0x44, 0x01, 0xd1, 0xe2, 0x59, 0xb0, 0xe0, 0x61,
	0x11, 0x17, 0x26, 0xd5, 0xb6, 0xea, 0x50, 0x26, 0x97, 0x91, 0xcf, 0x08, 0x37, 0xe5, 0x28, 0xfe,
	0xb4, 0xfe, 0x07, 0x25, 0xcf, 0x95, 0x22, 0x16, 0x8d, 0xbb, 0xdb, 0xf4, 0xac, 0xc7, 0xb0, 0xec,
	0x47, 0x48, 0x96, 0x49, 0x14, 0xf8, 0x5c, 0xd4, 0x17, 0xb6, 0x8b, 0xb9, 0x5d, 0xd2, 0x6d, 0x21,
	0x3f, 0x3a, 0x09, 0x99, 0x70, 0x40, 0xff, 0xb6, 0x7c, 0x2e, 0xd4, 0x8a, 0x1f, 0xe3, 0x34, 0x8f,
	0x15, 0x7f, 0x7d, 0xe2, 0xb1, 0x34, 0x6d, 0x58, 0xeb, 0xb6, 0x90, 0xf2, 0x71, 0xb3, 0x44, 0xa6,
	0x84, 0x7b, 0x04, 0x77, 0xda, 0xbc, 0xcf, 0x3b, 0x02, 0x0b, 0xe2, 0x90, 0xa1, 0xd6, 0x78, 0x13,
	0xca, 0x7a, 0x69, 0xf2, 0x7a, 0x61, 0xbb, 0x28, 0xeb, 0x99, 0xaa, 0x73, 0xdc, 0xfe, 0x1d, 0x96,
	0xb3, 0xde, 0x33, 0x64, 0xff, 0x49, 0x9e, 0xee, 0xbd, 0x24, 0x66, 0x8c, 0x4d, 0xcc, 0xf4, 0x29,
	0xdc, 0xe9, 0xb6, 0xe4, 0x96, 0xe1, 0x88, 0xcb, 0x7e, 0xc4, 0xc8, 0x70, 0x0a, 0x98, 0x6f, 0x60,
	0x55, 0xf6, 0xed, 0x07, 0x41, 0x93, 0xf6, 0xc2, 0x37, 0xe7, 0x2b, 0x17, 0x9b, 0x4f, 0x7b, 0xa1,
	0x42, 0xaf, 0x38, 0xaa, 0x6d, 0x5f, 0x42, 0x35, 0x03, 0x30, 0x83, 0x04, 0x1f, 0xe7, 0xb9, 0xdf,
	0xcd, 0x71, 0xcf, 0xf2, 0x8b, 0xa9, 0x1f, 0xc2, 0x6a, 0xac, 0x00, 0x0e, 0x02, 0x24, 0xd9, 0x4c,
	0x0e, 0xa2, 0x27, 0xdc, 0x21, 0x9c, 0x50, 0xef, 0xa6, 0x13, 0x9e, 0x78, 0xcf, 0x69, 0xc2, 0xf3,
	0x6c, 0xc6, 0x26, 0x1c, 0x31, 0xd5, 0xff, 0xd6, 0x09, 0xbf, 0x1e, 0xe6, 0x57, 0xb0, 0x9c, 0xc8,
	0x3d, 0x62, 0x61, 0xb4, 0x4f, 0xf9, 0x05, 0x61, 0x6f, 0x3c, 0xc9, 0xd7, 0x61, 0x91, 0x93, 0x21,
	0xa2, 0xa1, 0x29, 0x24, 0x25, 0x4e, 0x86, 0xc7, 0xa1, 0xb5, 0x06, 0xa5, 0xd3, 0x97, 0x82, 0x70,
	0x53, 0x46, 0xf4, 0x87, 0xfd, 0x0a, 0x6a, 0x39, 0xe4, 0x19, 0xd4, 0xf9, 0x34, 0x9f, 0xd6, 0x56,
	0x12, 0x33, 0x4e, 0x3d, 0xce, 0xeb, 0x7b, 0x75, 0xf4, 0xb1, 0xc8, 0x45, 0x58, 0x77, 0x8e, 0xe8,
	0x19, 0x0d, 0x2f, 0xe8, 0x34, 0x58, 0x0e, 0x3c, 0xc8, 0x63, 0x79, 0x2c, 0x8c, 0x22, 0xe2, 0x21,
	0x36, 0xa2, 0xd4, 0xa7, 0xfd, 0x77, 0xc2, 0xcf, 0x60, 0x4e, 0x83, 0xf5, 0x6f, 0x01, 0x36, 0x0f,
	0xb0, 0xd7, 0xe6, 0xfd, 0xe3, 0x50, 0xf8, 0x3d, 0xdf, 0xc5, 0x22, 0x39, 0x4d, 0xef, 0x03, 0x9c,
	0x62, 0x2f, 0x7f, 0x96, 0x2e, 0x9d, 0x2a, 0xe7, 0xa6, 0x67, 0xd9, 0x50, 0x8b, 0x7b, 0x39, 0x19,
	0x26, 0xf3, 0x5a, 0xd5, 0x0e, 0x1d, 0x69, 0x92, 0x57, 0x1d, 0xc2, 0x58, 0xc8, 0x90, 0x1b, 0x7a,
	0xc4, 0x4c, 0x71, 0x45, 0x59, 0x0e, 0x43, 0x8f, 0x58, 0xef, 0xc1, 0x8a, 0x3e, 0xd3, 0xd2, 0x33,
	0x77, 0x41, 0x8d, 0x52, 0xa3, 0xf2, 0xf4, 0x4a, 0x8e, 0xdd, 0xbf, 0x0b, 0x60, 0x8d, 0x93, 0x9c,
	0x61, 0x51, 0x7c, 0x96, 0x17, 0x6a, 0x3b, 0x89, 0x79, 0x8d, 0x14, 0xb1, 0x5a, 0x3f, 0xa9, 0x4b,
	0x4c, 0x9c, 0x36, 0xcd, 0x92, 0x99, 0x16, 0xb2, 0x05, 0x96, 0x81, 0xcc, 0xc8, 0x30, 0x35, 0xda,
	0x33, 0xb0, 0x92, 0xfa, 0x9c, 0x56, 0xe1, 0xfb, 0x00, 0x8c, 0x0c, 0xaf, 0x4c, 0x24, 0x23, 0x43,
	0x3d, 0x91, 0xd7, 0x95, 0xe2, 0x57, 0x50, 0xcb, 0xe1, 0xcc, 0x63, 0x03, 0x8e, 0x13, 0x8d, 0xb3,
	0xf8, 0x4e, 0x69, 0x92, 0x39, 0x90, 0x54, 0x41, 0x9e, 0x02, 0xe8, 0x0f, 0x58, 0x6b, 0xf3, 0xfe,
	0x11, 0x11, 0xd8, 0x0f, 0x88, 0x97, 0x0a, 0xf2, 0x9a, 0x1a, 0x65, 0x43, 0xcd, 0xec, 0x28, 0xd3,
	0xab, 0x2f, 0x88, 0x55, 0x6d, 0xd4, 0x6a, 0x5d, 0x5b, 0xb0, 0xac, 0x0d, 0x58, 0x94, 0x4c, 0x47,
	0x5c, 0x2d, 0xe0, 0x92, 0x63, 0xbe, 0xec, 0x3f, 0x0b, 0xb0, 0x72, 0x85, 0xc1, 0x0c, 0x52, 0xee,
	0xe5, 0x15, 0x78, 0x90, 0x55, 0x60, 0x2c, 0xc9, 0x58, 0x83, 0x1f, 0xd4, 0xb5, 0x46, 0x26, 0xe4,
	0x19, 0x17, 0x2d, 0xe7, 0x54, 0x60, 0x3f, 0x42, 0xdd, 0x80, 0xc9, 0x8d, 0xfb, 0x0e, 0x00, 0x3b,
	0xaa, 0xd2, 0x3f, 0x55, 0x45, 0x22, 0x7e, 0x1d, 0x65, 0x4a, 0x46, 0xe1, 0x6a, 0xc9, 0xf8, 0x3f,
	0xd4, 0x74, 0xf7, 0x80, 0x70, 0x8e, 0xfb, 0xc4, 0xac, 0xda, 0x65, 0x65, 0x6c, 0x6b, 0x9b, 0xcd,
	0x60, 0x29, 0x06, 0x9d, 0x41, 0xed, 0x47, 0xf9, 0x7c, 0x36, 0xb2, 0xd5, 0x34, 0x25, 0x1c, 0x27,
	0xf2, 0x35, 0x2c, 0x9b, 0xa2, 0xac, 0xa8, 0x4c, 0x18, 0xdd, 0x83, 0xda, 0x73, 0x21, 0xa2, 0x5f,
	0xb0, 0x6f, 0xfe, 0x2c, 0xd8, 0x82, 0xca, 0x00, 0x5f, 0x22, 0x8f, 0x04, 0xf8, 0xa5, 0x51, 0x61,
	0x69, 0x80, 0x2f, 0x8f, 0xe4, 0xb7, 0xd4, 0xe8, 0x42, 0x7a, 0xe2, 0x9e, 0x20, 0xcc, 0xd4, 0xdd,
	0x8a, 0xb4, 0xec, 0x4b, 0x83, 0x75, 0x17, 0xa4, 0x2b, 0x92, 0x06, 0xb3, 0x4a, 0xcb, 0x03, 0x7c,
	0x29, 0xb1, 0xa5, 0x32, 0xf1, 0x38, 0xf3, 0x50, 0x26, 0x97, 0x43, 0x5e, 0x99, 0x17, 0x42, 0x44,
	0x8a, 0xd2, 0x84, 0xd1, 0x4f, 0xa0, 0xda, 0x54, 0x4f, 0x85, 0xe4, 0x91, 0xe2, 0x47, 0xe7, 0x8f,
	0xe3, 0x47, 0x8a, 0x6c, 0x4b, 0x9b, 0x7c, 0x72, 0x18, 0x21, 0x54, 0xdb, 0xa6, 0xb0, 0xa8, 0xc3,
	0x66, 0x48, 0xf3, 0x83, 0x3c, 0xd1, 0xb5, 0x24, 0x26, 0x43, 0x28, 0x7d, 0xee, 0x57, 0x92, 0xc7,
	0xcd, 0x44, 0x81, 0xef, 0xeb, 0x8b, 0xff, 0xbe, 0x7b, 0xf6, 0x96, 0x0b, 0x63, 0x04, 0x65, 0xe3,
	0x38, 0x43, 0x4a, 0x1f, 0xe6, 0x99, 0xad, 0xe7, 0x2f, 0xb5, 0x86, 0x43, 0x4c, 0xed, 0x4b, 0xa8,
	0x26, 0xb7, 0x62, 0xf7, 0x6c, 0xb2, 0xd8, 0x21, 0xac, 0xa6, 0x7f, 0xfb, 0xf0, 0x9b, 0x1c, 0x43,
	0xab, 0x50, 0xa4, 0xe1, 0x85, 0x99, 0x44, 0xd9, 0xb4, 0x3e, 0x82, 0x92, 0x3c, 0x0c, 0x65, 0xa9,
	0x95, 0xcf, 0xc8, 0xcd, 0xec, 0x33, 0x32, 0xf3, 0xc7, 0x93, 0xa3, 0xbd, 0xe4, 0xf3, 0x21, 0x33,
	0xe4, 0x3c, 0x9e, 0x0f, 0x57, 0x33, 0x8a, 0x93, 0x3d, 0x80, 0x95, 0x3c, 0x25, 0x3e, 0x31, 0xc6,
	0xc1, 0x0e, 0x6c, 0xb9, 0xe1, 0xa0, 0x41, 0xc9, 0xe9, 0x28, 0xc0, 0xfe, 0xa0, 0x41, 0x68, 0xdf,
	0xa7, 0x24, 0x0e, 0x3b, 0x28, 0xb7, 0xbb, 0x27, 0xb2, 0xf1, 0xfc, 0xd6, 0xe9, 0xa2, 0xb2, 0xec,
	0xfd, 0x17, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x85, 0x2d, 0x5f, 0x9e, 0x14, 0x00, 0x00,
}
