// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sync.proto

package zproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// /////////////////////////////////////////////////////////////////////
// ServerAuthReq ==> VoidRsp
// SERVER_AUTH_REQ
type ServerAuthReq struct {
	ServerId   int32  `protobuf:"varint,1,opt,name=server_id,json=serverId" json:"server_id,omitempty"`
	ServerName string `protobuf:"bytes,2,opt,name=server_name,json=serverName" json:"server_name,omitempty"`
}

func (m *ServerAuthReq) Reset()                    { *m = ServerAuthReq{} }
func (m *ServerAuthReq) String() string            { return proto.CompactTextString(m) }
func (*ServerAuthReq) ProtoMessage()               {}
func (*ServerAuthReq) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *ServerAuthReq) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *ServerAuthReq) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

//
type DeliveryUpdatesToUsers struct {
	MyAuthKeyId       int64   `protobuf:"varint,1,opt,name=my_auth_key_id,json=myAuthKeyId" json:"my_auth_key_id,omitempty"`
	MySessionId       int64   `protobuf:"varint,2,opt,name=my_session_id,json=mySessionId" json:"my_session_id,omitempty"`
	MyNetlibSessionId int64   `protobuf:"varint,3,opt,name=my_netlib_session_id,json=myNetlibSessionId" json:"my_netlib_session_id,omitempty"`
	SendtoUserIdList  []int32 `protobuf:"varint,4,rep,packed,name=sendto_user_id_list,json=sendtoUserIdList" json:"sendto_user_id_list,omitempty"`
	// uint32 raw_data_header = 4;
	RawData []byte `protobuf:"bytes,5,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
}

func (m *DeliveryUpdatesToUsers) Reset()                    { *m = DeliveryUpdatesToUsers{} }
func (m *DeliveryUpdatesToUsers) String() string            { return proto.CompactTextString(m) }
func (*DeliveryUpdatesToUsers) ProtoMessage()               {}
func (*DeliveryUpdatesToUsers) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *DeliveryUpdatesToUsers) GetMyAuthKeyId() int64 {
	if m != nil {
		return m.MyAuthKeyId
	}
	return 0
}

func (m *DeliveryUpdatesToUsers) GetMySessionId() int64 {
	if m != nil {
		return m.MySessionId
	}
	return 0
}

func (m *DeliveryUpdatesToUsers) GetMyNetlibSessionId() int64 {
	if m != nil {
		return m.MyNetlibSessionId
	}
	return 0
}

func (m *DeliveryUpdatesToUsers) GetSendtoUserIdList() []int32 {
	if m != nil {
		return m.SendtoUserIdList
	}
	return nil
}

func (m *DeliveryUpdatesToUsers) GetRawData() []byte {
	if m != nil {
		return m.RawData
	}
	return nil
}

type PushUpdatesData struct {
	AuthKeyId       int64  `protobuf:"varint,1,opt,name=auth_key_id,json=authKeyId" json:"auth_key_id,omitempty"`
	SessionId       int64  `protobuf:"varint,2,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	NetlibSessionId int64  `protobuf:"varint,3,opt,name=netlib_session_id,json=netlibSessionId" json:"netlib_session_id,omitempty"`
	RawDataHeader   uint32 `protobuf:"varint,4,opt,name=raw_data_header,json=rawDataHeader" json:"raw_data_header,omitempty"`
	RawData         []byte `protobuf:"bytes,5,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
}

func (m *PushUpdatesData) Reset()                    { *m = PushUpdatesData{} }
func (m *PushUpdatesData) String() string            { return proto.CompactTextString(m) }
func (*PushUpdatesData) ProtoMessage()               {}
func (*PushUpdatesData) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *PushUpdatesData) GetAuthKeyId() int64 {
	if m != nil {
		return m.AuthKeyId
	}
	return 0
}

func (m *PushUpdatesData) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *PushUpdatesData) GetNetlibSessionId() int64 {
	if m != nil {
		return m.NetlibSessionId
	}
	return 0
}

func (m *PushUpdatesData) GetRawDataHeader() uint32 {
	if m != nil {
		return m.RawDataHeader
	}
	return 0
}

func (m *PushUpdatesData) GetRawData() []byte {
	if m != nil {
		return m.RawData
	}
	return nil
}

func init() {
	proto.RegisterType((*ServerAuthReq)(nil), "zproto.ServerAuthReq")
	proto.RegisterType((*DeliveryUpdatesToUsers)(nil), "zproto.DeliveryUpdatesToUsers")
	proto.RegisterType((*PushUpdatesData)(nil), "zproto.PushUpdatesData")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RPCSync service

type RPCSyncClient interface {
	// frontend --> sync
	PushUpdatesStream(ctx context.Context, in *ServerAuthReq, opts ...grpc.CallOption) (RPCSync_PushUpdatesStreamClient, error)
	// rpc ServerAuth(ServerAuthReq) returns (VoidRsp);
	DeliveryUpdates(ctx context.Context, in *DeliveryUpdatesToUsers, opts ...grpc.CallOption) (*VoidRsp, error)
	DeliveryUpdatesNotMe(ctx context.Context, in *DeliveryUpdatesToUsers, opts ...grpc.CallOption) (*VoidRsp, error)
}

type rPCSyncClient struct {
	cc *grpc.ClientConn
}

func NewRPCSyncClient(cc *grpc.ClientConn) RPCSyncClient {
	return &rPCSyncClient{cc}
}

func (c *rPCSyncClient) PushUpdatesStream(ctx context.Context, in *ServerAuthReq, opts ...grpc.CallOption) (RPCSync_PushUpdatesStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RPCSync_serviceDesc.Streams[0], c.cc, "/zproto.RPCSync/PushUpdatesStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &rPCSyncPushUpdatesStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RPCSync_PushUpdatesStreamClient interface {
	Recv() (*PushUpdatesData, error)
	grpc.ClientStream
}

type rPCSyncPushUpdatesStreamClient struct {
	grpc.ClientStream
}

func (x *rPCSyncPushUpdatesStreamClient) Recv() (*PushUpdatesData, error) {
	m := new(PushUpdatesData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rPCSyncClient) DeliveryUpdates(ctx context.Context, in *DeliveryUpdatesToUsers, opts ...grpc.CallOption) (*VoidRsp, error) {
	out := new(VoidRsp)
	err := grpc.Invoke(ctx, "/zproto.RPCSync/DeliveryUpdates", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCSyncClient) DeliveryUpdatesNotMe(ctx context.Context, in *DeliveryUpdatesToUsers, opts ...grpc.CallOption) (*VoidRsp, error) {
	out := new(VoidRsp)
	err := grpc.Invoke(ctx, "/zproto.RPCSync/DeliveryUpdatesNotMe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RPCSync service

type RPCSyncServer interface {
	// frontend --> sync
	PushUpdatesStream(*ServerAuthReq, RPCSync_PushUpdatesStreamServer) error
	// rpc ServerAuth(ServerAuthReq) returns (VoidRsp);
	DeliveryUpdates(context.Context, *DeliveryUpdatesToUsers) (*VoidRsp, error)
	DeliveryUpdatesNotMe(context.Context, *DeliveryUpdatesToUsers) (*VoidRsp, error)
}

func RegisterRPCSyncServer(s *grpc.Server, srv RPCSyncServer) {
	s.RegisterService(&_RPCSync_serviceDesc, srv)
}

func _RPCSync_PushUpdatesStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServerAuthReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RPCSyncServer).PushUpdatesStream(m, &rPCSyncPushUpdatesStreamServer{stream})
}

type RPCSync_PushUpdatesStreamServer interface {
	Send(*PushUpdatesData) error
	grpc.ServerStream
}

type rPCSyncPushUpdatesStreamServer struct {
	grpc.ServerStream
}

func (x *rPCSyncPushUpdatesStreamServer) Send(m *PushUpdatesData) error {
	return x.ServerStream.SendMsg(m)
}

func _RPCSync_DeliveryUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryUpdatesToUsers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCSyncServer).DeliveryUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zproto.RPCSync/DeliveryUpdates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCSyncServer).DeliveryUpdates(ctx, req.(*DeliveryUpdatesToUsers))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCSync_DeliveryUpdatesNotMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryUpdatesToUsers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCSyncServer).DeliveryUpdatesNotMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zproto.RPCSync/DeliveryUpdatesNotMe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCSyncServer).DeliveryUpdatesNotMe(ctx, req.(*DeliveryUpdatesToUsers))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPCSync_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zproto.RPCSync",
	HandlerType: (*RPCSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeliveryUpdates",
			Handler:    _RPCSync_DeliveryUpdates_Handler,
		},
		{
			MethodName: "DeliveryUpdatesNotMe",
			Handler:    _RPCSync_DeliveryUpdatesNotMe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushUpdatesStream",
			Handler:       _RPCSync_PushUpdatesStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sync.proto",
}

func init() { proto.RegisterFile("sync.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x86, 0xe5, 0x76, 0xdd, 0xd6, 0x53, 0x42, 0xa8, 0x37, 0x20, 0x14, 0x31, 0xa2, 0x22, 0x50,
	0x84, 0x44, 0x41, 0xf0, 0x04, 0x94, 0x21, 0x56, 0xc1, 0xaa, 0x2a, 0x65, 0x5c, 0x70, 0x63, 0xb9,
	0xf5, 0x11, 0x8d, 0xa8, 0x93, 0xe2, 0xe3, 0x6c, 0x32, 0x2f, 0xc7, 0x8b, 0xc0, 0xbb, 0xa0, 0x24,
	0xcd, 0x18, 0x2d, 0x20, 0x71, 0x65, 0xe9, 0xfb, 0xff, 0x38, 0xe7, 0x93, 0x0f, 0x00, 0xb9, 0x74,
	0x3e, 0x58, 0x99, 0xcc, 0x66, 0x7c, 0xf7, 0x6b, 0x79, 0xf6, 0x3c, 0x8d, 0x44, 0xf2, 0x13, 0x56,
	0xb8, 0x7f, 0x0a, 0xde, 0x14, 0xcd, 0x39, 0x9a, 0x97, 0xb9, 0x5d, 0xc4, 0xf8, 0x85, 0xdf, 0x85,
	0x36, 0x95, 0x40, 0x24, 0x2a, 0x60, 0x21, 0x8b, 0x5a, 0xf1, 0x7e, 0x05, 0x46, 0x8a, 0xdf, 0x87,
	0xce, 0x3a, 0x4c, 0xa5, 0xc6, 0xa0, 0x11, 0xb2, 0xa8, 0x1d, 0x43, 0x85, 0xc6, 0x52, 0x63, 0xff,
	0x3b, 0x83, 0x5b, 0xc7, 0xb8, 0x4c, 0xce, 0xd1, 0xb8, 0xb3, 0x95, 0x92, 0x16, 0xe9, 0x7d, 0x76,
	0x46, 0x68, 0x88, 0x3f, 0x80, 0xeb, 0xda, 0x09, 0x99, 0xdb, 0x85, 0xf8, 0x8c, 0xae, 0xbe, 0xbd,
	0x19, 0x77, 0xb4, 0x2b, 0xfe, 0xfd, 0x16, 0xdd, 0x48, 0xf1, 0x3e, 0x78, 0xda, 0x09, 0x42, 0xa2,
	0x24, 0x4b, 0x8b, 0x4e, 0xa3, 0xee, 0x4c, 0x2b, 0x36, 0x52, 0xfc, 0x29, 0x1c, 0x6a, 0x27, 0x52,
	0xb4, 0xcb, 0x64, 0x76, 0xb5, 0xda, 0x2c, 0xab, 0x5d, 0xed, 0xc6, 0x65, 0xf4, 0xeb, 0x83, 0x27,
	0x70, 0x40, 0x98, 0x2a, 0x9b, 0x89, 0x9c, 0x4a, 0x2f, 0xb1, 0x4c, 0xc8, 0x06, 0x3b, 0x61, 0x33,
	0x6a, 0xc5, 0x37, 0xaa, 0xa8, 0x98, 0x71, 0xa4, 0xde, 0x25, 0x64, 0xf9, 0x1d, 0xd8, 0x37, 0xf2,
	0x42, 0x28, 0x69, 0x65, 0xd0, 0x0a, 0x59, 0x74, 0x2d, 0xde, 0x33, 0xf2, 0xe2, 0x58, 0x5a, 0xd9,
	0xff, 0xc6, 0xc0, 0x9f, 0xe4, 0xb4, 0x58, 0xab, 0x15, 0x8c, 0x1f, 0x41, 0x67, 0x5b, 0xaa, 0x2d,
	0x2f, 0x95, 0xee, 0x01, 0x6c, 0xf9, 0xb4, 0xe9, 0x72, 0xb8, 0xc7, 0xd0, 0xfd, 0x9b, 0x8a, 0x9f,
	0x6e, 0x88, 0x3c, 0x02, 0xbf, 0x9e, 0x4c, 0x2c, 0x50, 0x2a, 0x34, 0xc1, 0x4e, 0xc8, 0x22, 0x2f,
	0xf6, 0xd6, 0x03, 0x9e, 0x94, 0xf0, 0x1f, 0x06, 0xcf, 0x7f, 0x30, 0xd8, 0x8b, 0x27, 0xaf, 0xa6,
	0x2e, 0x9d, 0xf3, 0xd7, 0xd0, 0xbd, 0x22, 0x33, 0xb5, 0x06, 0xa5, 0xe6, 0x37, 0x07, 0xd5, 0xa2,
	0x0c, 0x7e, 0x5b, 0x8b, 0xde, 0xed, 0x1a, 0x6f, 0xe8, 0x3f, 0x63, 0x7c, 0x08, 0xfe, 0xc6, 0x93,
	0xf3, 0xa3, 0xba, 0xfd, 0xe7, 0x5d, 0xe8, 0xf9, 0x75, 0xfe, 0x21, 0x4b, 0x54, 0x4c, 0x2b, 0xfe,
	0x06, 0x0e, 0x37, 0xaa, 0xe3, 0xcc, 0x9e, 0xe2, 0x7f, 0x5f, 0x34, 0x7c, 0x08, 0x07, 0xf3, 0x4c,
	0x0f, 0x52, 0x9c, 0xe5, 0x4b, 0x99, 0xe8, 0x75, 0x3c, 0x84, 0x8f, 0x93, 0xe2, 0x2c, 0xb4, 0x4f,
	0x1a, 0x13, 0x36, 0xdb, 0x2d, 0xf1, 0x8b, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x4e, 0xe1,
	0x92, 0x22, 0x03, 0x00, 0x00,
}
